### PR TITLE
Add new neophyten layers

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by loicgasser** [comment]
Is that for tomorrow?

**Comment by daguer** [comment]
No...

**Comment by loicgasser** [comment]
@daguer this seems to be a duplicate of https://github.com/geoadmin/mf-chsdi3/pull/2796/files

Can you confirm and close if this is the case?

**Comment by loicgasser** [comment]
ah no too many neophyten layers. confusing stuff.

**Pull request merged**
