### PR TITLE
Autotranslate without empty.po

### PR DESCRIPTION
**Pull request by loicgasser**
4'000 translations not used in chsdi, some stuff that doesn't make sense as well.

I think there are a couple that are not used. Maybe the chance for a cleanup as well.

### CODE REVIEW

**Comment by loicgasser** [comment]
@gjn This PR is ready. Only thing is in the PR description, it introduces a lot of extra translations. I think that we may have a lot of unused translations as well.
These are used in chsdi and wms. @ltclm is there a way to know which ones are in the WMS?

Otherwise review can already be performed as this is technically ready.

**Comment by gjn** [comment]
This LGTM. I think we can live with the extra stuff that is not needed. Should have a great impact on performance and size.

**Comment by loicgasser** [comment]
Ok, I'll update wiki and send an email to the integrators then.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/issues/2336

**Pull request merged**
