### PR TITLE
ch.swisstopo.images-swissimage-dop10.metadata

### PR DESCRIPTION
**Pull request by ltclm**
[Testlink](https://mf-chsdi3.dev.bgdi.ch/dev_ltclm_dop10/shorten/78007a66f3)
adds new metadata layer for swissimage dop10
done:
* basic tooltip (no shop) with temporary mako template
* legends
* translation

@loicgasser could you please help me with the following points:
todo:
* shop_perimeter
* shop link

@pauloamado  which parameters have to be sent to the shop service: 
```
layer: ???
clipper: ch.swisstopo.images-swissimage-dop10.metadata
featureid: 1168-41
```
 @AFoletti 
could you please specifiy the desired shop options (tile, whole dataset, canton, etc.)

### CODE REVIEW

**Comment by AFoletti** [comment]
no highlight? Is that right?
...And I hate the 100 transparency that is transparent on those metadata layers... it's impossible to understand the colors

**Comment by ltclm** [comment]
i have fixed the highlight, wrong setting in bod

**Comment by pauloamado** [comment]
Same principle as SWISSIMAGE request for id and clipper :

https://shop.swisstopo.admin.ch/fr/dispatcher?layer=ch.swisstopo.swissimage-product&clipper=ch.swisstopo.images-swissimage.metadata&featureid=1151-34

But in the case of dop10, we don't have any layer similar to "ch.swisstopo.swissimage-product"
Should we create a "noscale" layer?

**Comment by ltclm** [comment]
Data will be visualized with ch.swisstopo.swissimage-product. the tile_id will be ``[0-9]{4}_[0-9]{4}`` p.e. [2632_1133](https://mf-chsdi3.dev.bgdi.ch/ltclm/rest/services/ech/MapServer/ch.swisstopo.images-swissimage-dop10.metadata/2632_1133/htmlPopup?coord=2632551.1268172828,1133568.9191752593&imageDisplay=882,780,96&lang=de&mapExtent=2621519.5894450424,1122777.19783285,2647959.3067339454,1146159.2607414036)
is that doable on shop-side?

**Comment by pauloamado** [comment]
Yes, the Shop will just display the tile_id.

**Comment by ltclm** [comment]
I have activated the shop options ``{tile,whole}`` in the bod  and tried to adapt the chsdi model stuff.
@loicgasser could you please help me. 
I have added a new view with the perimeter of dop10 [1], it will grow with the data (autoamata). in the model i have registered this view as perimeter for the dop10 metadata layer.

The shop price service returns a 404:
https://shop-bgdi.dev.bgdi.ch/shop-server/resources/products/price?layer=ch.swisstopo.images-swissimage-dop10.metadata

[1]
```sql
CREATE OR REPLACE VIEW shop_perimeter_swissimage_dop10 AS
 SELECT min(bgdi_id) AS bgdi_id,
    st_union(the_geom) AS the_geom
   FROM datenstand.view_gridstand_datenhaltung_swissimage_dop10_tilecache;

ALTER TABLE shop_perimeter_swissimage_dop10
  OWNER TO pgkogis;
GRANT ALL ON TABLE shop_perimeter_swissimage_dop10 TO pgkogis;
GRANT SELECT ON TABLE shop_perimeter_swissimage_dop10 TO "www-data";

```

**Comment by pauloamado** [comment]
The shop price service returns a 404 because this product has not been declared yet.
It will come soon.

**Comment by AFoletti** [comment]
About the shop options, I have to ask @mariokeusen

**Comment by mariokeusen** [comment]
I think, we just have to wait the product definition in shop as noted by @pauloamado

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/shop/ShopService.js#L30

**Pull request merged**
