### PR TITLE
Deshopify ch.swisstopo.geologie-geocover

### PR DESCRIPTION
**Pull request by b4l**
https://sys-s.dev.bgdi.ch/649321283906

### CODE REVIEW

**Comment by faselm** [comment]
No legends? Looks good otherwise

**Comment by ltshb** [comment]
@b4l the CI test have been solved in `master` branch. I plan to update the `develop-2022-05-18` this noon see #3852, as soon this PR is merged you can rebase your PR on top of `develop-2022-05-18` and CI should then work.

**Comment by b4l** [comment]
@faselm no legends here, that is correct.
@ltshb thanks for the heads up, will do that.

**Review by ltclm — APPROVED** [review]
great,
thank you!

**Comment by ltshb** [comment]
@b4l milestone branch has been updated and now the CI should hopefully work :-)

**Pull request merged**
