### PR TITLE
biosphaeren

### PR DESCRIPTION
**Pull request by Brunim28**

### CODE REVIEW

**Comment by Brunim28** [comment]
change the bod before merging (bod_ltbrg to bod_master)

**Comment by ltclm** [comment]
is this for next weeks deploy?

**Comment by Brunim28** [comment]
no it will be for 2019-01-23

**Comment by ltclm** [comment]
Salut Morgane, you can remove the old model from the chsdi code, just like you did it in this pr. once the new code is deployed, please remove the old table (in bafu_master database).

**Pull request merged**
