### PR TITLE
Add config json for ch.bafu.hydroweb-messstationen_grundwasserzustand

### PR DESCRIPTION
**Pull request by Sgachet**
[test link](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgas_hydroweb_grundwasserzustand&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&X=196104.15&Y=613149.25&zoom=3&layers=ch.bafu.hydroweb-messstationen_grundwasserzustand)

### CODE REVIEW

**Comment by loicgasser** [comment]
@Sgachet is still WIP ?

**Comment by Sgachet** [comment]
@loicgasser Yep, the customer test it

**Comment by Sgachet** [comment]
@loicgasser please have a look and then merge, it's for tomorrow

**Comment by Sgachet** [comment]
@loicgasser please have a look and merge, it's for today deploy

**Pull request merged**
