### PR TITLE
chsdi integration NAWA layers

### PR DESCRIPTION
**Pull request by rfrancel**

### CODE REVIEW

**Comment by loicgasser** [comment]
Due this week?

**Comment by rfrancel** [comment]
No!

De : Gasser Loïc [mailto:notifications@github.com]
Envoyé : mardi 14 juin 2016 09:51
À : geoadmin/mf-chsdi3 <mf-chsdi3@noreply.github.com>
Cc : Francelet Rebecca swisstopo <Rebecca.Francelet@swisstopo.ch>; Author <author@noreply.github.com>
Objet : Re: [geoadmin/mf-chsdi3] [WIP] chsdi integration NAWA layers (#2123)


Due this week?

**Comment by rfrancel** [comment]
The layers are ready. Here is a [test link](https://mf-geoadmin3.dev.bgdi.ch/?api_url=frr_nawa_layers&X=307090.01&Y=651192.31&zoom=1&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_timestamp=,,,,,,,,,&layers=ch.bafu.gewaesserschutz-chemischer_zustand_nitrat,ch.bafu.gewaesserschutz-chemischer_zustand_nitrit,ch.bafu.gewaesserschutz-chemischer_zustand_ammonium,ch.bafu.gewaesserschutz-chemischer_zustand_doc,ch.bafu.gewaesserschutz-chemischer_zustand_phosphor_gesamt,ch.bafu.gewaesserschutz-biologischer_zustand_fische,ch.bafu.gewaesserschutz-biologischer_zustand_makrozoobenthos,ch.bafu.gewaesserschutz-biologischer_zustand_makrophyten,ch.bafu.gewaesserschutz-biologischer_zustand_diatomeen,ch.bafu.gewaesserschutz-chemischer_zustand_phosphat&layers_visibility=false,false,false,false,false,false,false,false,false,true) with the ten layers.

They are due for july 13, I let you see with Mario exactly when you can go on prod with it.
They are not searchable. The only think to do is to change the stanging to prod in the table bod.dataset and to change the wms metadata in the table re3.layers_js.
I assign this to you @AFoletti so you can finish the integration. Thanks!

**Comment by loicgasser** [comment]
Very nice, this looks good to me. I did not test.

**Comment by AFoletti** [comment]
I did test and it looks to be OK. @mariokeusen could you please check too?
This should be merged today or tomorrow, pending @mariokeusen's OK

**Comment by mariokeusen** [comment]
Ok, I checked these layers about 3 weeks ago already. Go for publication if there were no changes since then. BTW @gjn : the dev link is not available right now...

**Pull request merged**
