### PR TITLE
Update legends for ch.swisstopo-vd.geometa-los

### PR DESCRIPTION
**Pull request by Sgachet**

### CODE REVIEW

**Comment by Sgachet** [comment]
[Test link](ch.swisstopo-vd.geometa-los)

It's just an legend update

**Comment by loicgasser** [comment]
Are you  sure about removing the `Annerkant` here? I remember data owner coming to my office recently because this category was not displayed anymore in the WMS.
And it doesn't seem to be part of the deploy next week.

**Comment by Sgachet** [comment]
See in [Ticket] (https://jira.swisstopo.ch/projects/BGDIDI_KB/issues/BGDIDI_KB-940)
@mariokeusen Can you confirm that the only change to do is to remove the "Annerkant" in legend ?

**Comment by Sgachet** [comment]
Hi @loicgasser , 
Mario just confirmed that only the png change

**Pull request merged**
