### PR TITLE
update windenergieanlagen legends

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by gjn** [comment]
White background instead of transparent background? Is this wanted?

**Comment by AFoletti** [comment]
not really.
I'll ask the datenherr to deliver updated pngs

**Comment by gjn** [comment]
@daguer Next time, please have a look at the differences of your Pull Requests. They show quite clearly the change (Files changed tab above)

https://github.com/geoadmin/mf-chsdi3/pull/2025/files

**Comment by daguer** [comment]
Transparent legends are ready...

**Comment by gjn** [comment]
They look wider than necessary. No problem?

Also, could you please squash the commits?

**Comment by daguer** [comment]
New symbols are wider.
It's the solution of the Datenherr for having correct size of symbols in the legend...

commits are squashed.

**Comment by daguer** [comment]
New symbols:

https://github.com/geoadmin/wms-mapfile_include/commit/cad5ae79ad09236056584dddf291d07c6401c778

**Comment by gjn** [comment]
This is how it looks on the iPhone 6:

image
image

Content is cut off and user has to scroll to see everything. It's even worse on iPhone 4 and some smaller phones. We have a mobile first strategy. I doub't @davidoesch / @cedricmoullet can accept this.

You can simluate any device in the chrome developer tools. Use it.

**Comment by gjn** [comment]
@AFoletti what's the max-width for legend images again? 480px?

480px will also create the need to scroll on smaller mobile devices. hmm.

**Comment by AFoletti** [comment]
ah sorry, that's totally my fault. I did not check the new delivery for width
Yes, max width is officially 480px. @mariokeusen is now preparing a small help doc for the datenherren. If we want to change that limit, I think it's the right moment to think about it

**Comment by AFoletti** [comment]
@daguer about current legends. You could simply cut it a little to the right and you're within official limits ;)

**Comment by gjn** [comment]
@mariokeusen Please make sure to discuss this max-width requirement with @davidoesch before communicating it officially with clients.

I'm aware that we currently have some legends that are wider and that even 480px will require panning on mobile devices.

**Comment by daguer** [comment]
the width of legends is now < 480px and commits are squashed...

**Comment by gjn** [comment]
Please merge if @davidoesch @mariokeusen give their go.

**Comment by davidoesch** [comment]
The standard min width is the one of iPhone 5SE - has a higher dpi as the 4s . but you can n still stick to the 4s width. I know the arguments of @cedricmoullet that 6s has bigger screens but 5SE will dominate.

**Comment by gjn** [comment]
As it fullfills our limits, I'll merge.

**Pull request merged**
