### PR TITLE
Limit search bbox area

### PR DESCRIPTION
**Pull request by procrastinatio**

### CODE REVIEW

**Comment by danduk82** [comment]
@procrastinatio , could you please reslove the conflicts before @ltclm reviews it? Would be great to include in next deploy.

**Comment by danduk82** [comment]
@ltclm, is this solved on sphinx level?

**Comment by ltclm** [comment]
yes, the memory issues have been solved on sphinx level. index/dictionary types have been changed to legacy type crc.
memory usage is stable now  https://grafana.bgdi.ch/d/FU8IPh8iz/sphinx-prod?refresh=1m&orgId=5

**Comment by danduk82** [comment]
after discussion, the problem is fixed on sphinx side. So I close this as `won't do`

**Pull request closed without merging**
