### PR TITLE
[WIP] MapFish Print Server v3

### PR DESCRIPTION
**Pull request by procrastinatio**
This very WIP, it's only install the java .war in tomcat.

Documentation (broken on the main site)
http://mf-chsdi3.dev.bgdi.ch/~ltmom/mapfish-printV3/#/overview

### CODE REVIEW

**Comment by procrastinatio** [comment]
So what do we do with Print v3 ?

**Comment by kandre** [comment]
I suggest I look first at emapis to be more comfortable with it and then come back to you

**Comment by procrastinatio** [comment]
Canton Basel-Land uses this Mapfish Print v3 (at least two presentation from c2c):

http://geoview.bl.ch/  (bottom-left to print)

**Comment by procrastinatio** [comment]
Well, at last we have WMTS support...

And then in _http://mf-chsdi3.dev.bgdi.ch/{kurzel}/print/_, choose _Print app/Example_ `geoadmin3` (you may edit the `spec`before sending it to the server...

**Comment by procrastinatio** [comment]
This is no longer needed

**Pull request closed without merging**
