### PR TITLE
[WIP] add new attributes to lubis extended tooltip

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by ltclm** [comment]
data with new columns is already deployed on dev,int,prod

**Comment by AFoletti** [comment]
There are some strange things in the translations in this PR. This is due to some DB/chsdi changes ongoing on some layers
See https://github.com/geoadmin/mf-chsdi3/compare/ltfoa_fix_queryable

Maybe it would be good to merge that branch first and then rebase this one to avoid messing up?

**Comment by ltclm** [comment]
i have cleaned the pr, ready to merge

**Comment by gjn** [comment]
@AFoletti Could you review this?

**Comment by AFoletti** [comment]
LGTM

**Comment by gjn** [comment]
Thanks @AFoletti .

**Pull request merged**
