### PR TITLE
Use pyproj instead of gdal

### PR DESCRIPTION
**Pull request by loicgasser**
As we are using gdal in a single function `transform_coordinate`, it is better to use something else, much much lighter like pyproj.

Build is now shorter. (will tell you exactly how much in a sec)

### CODE REVIEW

**Comment by loicgasser** [comment]
Build time now:
2m12.980s

Build time before:
2m13.256s

not much of a change but cleaner install and code for the same result.

**Comment by gjn** [comment]
Both GDal and pyproj are using the same transformation?

Which?

**Comment by gjn** [comment]
I think it's grid based transformation.

**Comment by loicgasser** [comment]
yes grid based, test returns exactly the same result

**Comment by gjn** [comment]
+1

Unfortunately, now a conflict because of the other PR. But once solved, please merge this.

**Pull request merged**
