### PR TITLE
Update ch.swisstopo.swisstlm3d-strassen

### PR DESCRIPTION
**Pull request by faselm**
Test: https://mf-chsdi3.dev.bgdi.ch/ltfas_swisstopo_swisstlm3d_strassen/shorten/94d143f6e6

### CODE REVIEW

**Review by b4l — COMMENTED** [review]
The test link shows the tank relocation routes which seems to be the wrong layer.

**Comment by faselm** [comment]
Here is the good one:) https://mf-chsdi3.dev.bgdi.ch/shorten/94d0f45b34

**Comment by b4l** [comment]
Looks much better, still no streetname in the tooltip. You are using plain dev, i think you have to deploy the branch and adapt the link accordingly.

**Comment by faselm** [comment]
This is the good one! -> https://mf-chsdi3.dev.bgdi.ch/ltfas_swisstopo_swisstlm3d_strassen/shorten/94d143f6e6

**Review by b4l — APPROVED** [review]
Looks fantastic!

**Pull request merged**
