### PR TITLE
Remove mapproxy ref, everything points to wmts(1-9)

### PR DESCRIPTION
**Pull request by loicgasser**
After LV95 or before?

ping @gjn @procrastinatio

This assumes that public wmts will always be wmts[20-24]

### CODE REVIEW

**Comment by gjn** [comment]
I don't understand this. Why everything wmts20?

I wouldn't change the doc at all for the moment. We will consolidate the WMTS addresses at a later time.

**Comment by gjn** [comment]
I think our official domain for the getcapabilities should be: wmts.geo.admin.ch. This should probably also be the wmts url in the getcapabilities document.

Then for the tiles, we offer ranges wmts1-wmts9.

**Comment by loicgasser** [comment]
yes, it's maybe better to keep those instead. Anyway we should always use the same range since TOD is in the place. We'll have to change the codepens to be consistent, as well as a lot of those are still pointing to 20-24.

**Comment by gjn** [comment]
Yes, we need to get rid of all the old ones. Cleaning up will be big early 2018.

**Comment by loicgasser** [comment]
adapted according to your comments.

**Comment by loicgasser** [comment]
@gjn @procrastinatio please review

**Pull request merged**
