### PR TITLE
[WIP] set a custom user agent for python requests

### PR DESCRIPTION
**Pull request by ltclm**
replace get with head requests
set custom user agent
set height service url to root

[Testlink](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fdev_ltclm_fix_user_agent&layers=ch.swisstopo-vd.amtliche-vermessung,ch.bfe.windenergie-geschwindigkeit_h50&X=217242.78&Y=600610.03&zoom=10&layers_visibility=true,false&layers_opacity=1,0.75)

### CODE REVIEW

**Comment by gjn** [comment]
Code looks good to me. Tested.

**Comment by gjn** [comment]
@loicgasser Why does build fail?

**Comment by ltclm** [comment]
i have integrated gwr address data today from gdwh, apparently the gdwh copy of the bfs data has the shortened version of street names, this is breaking most of address search tests. i will revert this import and ask the gdwh to change their data import script.

**Comment by ltclm** [comment]
jenkins test

**Comment by ltclm** [comment]
The first test seems to fail because of the user agent blocking -> http status 503.
```
FAIL: test_resource_exists (chsdi.tests.functional.test_helpers.Test_Helpers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/PR_chsdi3/chsdi/tests/functional/test_helpers.py", line 53, in test_resource_exists
    self.assertTrue(test_result)
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api3.geo.admin.ch
requests.packages.urllib3.connectionpool: DEBUG: "HEAD / HTTP/1.1" 503 0
--------------------- >> end captured logging << ---------------------
```

the second test is related to the data content. is it possible to do the tests with prod data?

**Comment by ltclm** [comment]
jenkins test

**Comment by loicgasser** [comment]
LGTM thanks for fixing the many errors

**Pull request merged**
