### PR TITLE
remove queryable and selectbyrectangle attributes 

### PR DESCRIPTION
**Pull request by ltclm**
remove queryable and selectbyrectangle attributes  and replace them with tooltip

Not sure if we have to adapt https://github.com/geoadmin/ol3.git too.

### CODE REVIEW

**Comment by loicgasser** [comment]
Make sure this works as well.
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/static/doc/source/api/faq/index.rst

**Comment by ltclm** [comment]
@procrastinatio could you please verify if one of these attributes ``queryable`` ``selectbyrectangle`` is used in mapproxy?

**Comment by loicgasser** [comment]
https://github.com/geoadmin/ol3/blob/master/src/ga/layer/layer.js#L217
and
for JS API
https://github.com/geoadmin/ol3/blob/master/src/ga/tooltip.js#L142

**Comment by ltclm** [comment]
mapproxy does not use these attributes
https://github.com/geoadmin/service-mapproxy/search?utf8=%E2%9C%93&q=queryable

@loicgasser could you please prepare a pr in https://github.com/geoadmin/ol3.git

**Comment by loicgasser** [comment]
Will do

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
we need to update geoadmin js api as well

**Comment by gjn** [comment]
Yes, PR is ready https://github.com/geoadmin/ol3/pull/136 (I've noticed you also created a PR)

But I was not able to update the ga.js and ga-debug.js with this yet. Could you try?

**Comment by gjn** [comment]
btw: just merge the ol3 PR.

**Comment by loicgasser** [comment]
@ltclm you can get rid of queryable and selectbyrectangle attributes in DB and in the views.

In addition, you can create your first schema migration in https://github.com/geoadmin/dbmanagement

Have a look at the doc:
http://alembic.readthedocs.io/en/latest/ops.html

If you need help we can do it on Friday.

**Comment by ltclm** [comment]
Hi Loic

Thank you, i will remove the attributes.
If i find some time i will try tomorrow to create the schema migratio. This friday i wont be there, so next week....

**Pull request merged**
