### PR TITLE
Fix decimals for gewaesserschutz layers

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by ltclm** [comment]
and in the identify result we wont change the precision?

**Comment by daguer** [comment]
@ltclm : For that, we have to modify the data... That's what you propose? 
Is it really worth it? 
I think that it is not necessary...

**Comment by ltclm** [comment]
if @gjn agrees we keep it as it is.

**Comment by gjn** [comment]
To me, change it tooltip only is ok. It's what appears.

The identify result might be seen as technichal. So I'll merge this for today.

**Pull request merged**
