### PR TITLE
Added ch.swisstopo.geologie-tiefengeothermie_projekte

### PR DESCRIPTION
**Pull request by MartinaJoelle**
@AFoletti Can you please check, thank you
[Link](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fltmae_tiefengeothermie_projekte&wms_url=%2F%2Fwms-bod.dev.bgdi.ch%2Fltmae_demo%2F%3Flang%3Dxx&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-tiefengeothermie_projekte&X=239297.38&Y=685152.50&zoom=3)

### CODE REVIEW

**Comment by AFoletti** [comment]
ah, I hate those labels. I'll try to convince the datenherr to abandon them.
Aside from that, the layer works fine.
Just a thing: please separate tooltip and extended tooltip as described in the DIF

**Comment by MartinaJoelle** [comment]
@AFoletti Tooltip and extended tooltip should now be seperated, please check, thank you.
[Link](https://mf-geoadmin3.dev.bgdi.ch/ltmae/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-tiefengeothermie_projekte&X=216550.00&Y=657750.00&zoom=3&wms_url=%2F%2Fwms-bod.dev.bgdi.ch%2Fltmae_demo%2F%3Flang%3Dxx)

**Comment by AFoletti** [comment]
yes! thank you.
I just saw it: the layer name is not translated, and this comes up in the selected layer list. Please add this translation and I'll then send the link to the customer for acceptance

**Comment by MartinaJoelle** [comment]
[New Link](https://mf-geoadmin3.int.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fltmae_tiefengeothermie_projekte&wms_url=%2F%2Fwms-bod.dev.bgdi.ch%2Fltmae_demo%2F%3Flang%3Dxx&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-tiefengeothermie_projekte&X=239297.38&Y=685152.50&zoom=3)

**Comment by loicgasser** [comment]
It seems there is a small encoding problem in the legends.
See:
chsdi/static/images/legends/ch.swisstopo.geologie-tiefengeothermie_projekte_fr.png

**Comment by MartinaJoelle** [comment]
Thanks for the hint. Here is the new link:
[Link](https://mf-geoadmin3.int.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fltmae_tiefengeothermie_projekte&wms_url=%2F%2Fwms-bod.dev.bgdi.ch%2Fltmae_demo%2F%3Flang%3Dxx&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-tiefengeothermie_projekte&X=239297.38&Y=685152.50&zoom=3)

**Comment by loicgasser** [comment]
very nice thank you

**Pull request merged**
