### PR TITLE
Add new layer ch.bfe.solarprofis

### PR DESCRIPTION
**Pull request by Sgachet**
[Test link](https://mf-chsdi3.dev.bgdi.ch/gas_solarprofis/shorten/7a8f0cee72)

### CODE REVIEW

**Comment by Sgachet** [comment]
@rebert Coud you please have a look on my code ? I think we can optimize

**Comment by pakb** [comment]
@Sgachet status on this layer?

**Comment by Sgachet** [comment]
@pakb in stand-by for the moment

**Comment by ltclm** [comment]
@mariokeusen can we remove this layer from the bod?

**Pull request closed without merging**
