### PR TITLE
Change image legend in it for bebeco

### PR DESCRIPTION
**Pull request by pfanguin**

### CODE REVIEW

**Comment by pfanguin** [comment]
Test link : http://mf-chsdi3.dev.bgdi.ch/fix_legend_bebeco/rest/services/api/MapServer/ch.vbs.bundestankstellen-bebeco/legend?lang=it

**Comment by pfanguin** [comment]
jenkins test

**Comment by oterral** [comment]
@pfanguin can you optimize the image please?

**Comment by pfanguin** [comment]
It's done

**Pull request merged**
