### PR TITLE
BGDIDIC-1998: Add ch.bfe.elektrizitaetsproduktionsanlagen

### PR DESCRIPTION
**Pull request by b4l**
Test link: https://mf-chsdi3.dev.bgdi.ch/feature_BGDIDIC-1998/shorten/8edfa2ce70

### CODE REVIEW

**Review by faselm — COMMENTED** [review]
Map, tooltip, legends look good!

OK, the address looks good so I guess it's OK... The nuclear thing here looks odd however....
https://mf-chsdi3.dev.bgdi.ch/feature_BGDIDIC-1998/shorten/8edfad7b35

**Comment by AFoletti** [comment]
> The nuclear thing here looks odd however: https://mf-chsdi3.dev.bgdi.ch/feature_BGDIDIC-1998/shorten/8edfad7b35

You are correct, but it is only dummy data for the moment being 😃 

Please check the WMS gutter. It looks too small to me and some symbols near the tile border are cut out
image

Thanks!

**Comment by b4l** [comment]
@AFoletti the wms gutter has been increased from 15 to 30 which resolves the issue in your example.

**Comment by faselm** [comment]
@AFoletti Alright ^^ I was wondering if I missed a nuclear power plant somewhere :D

**Review by ltclm — APPROVED** [review]

**Comment by procrastinatio** [comment]
@b4l Please clean up your commit history

**Pull request merged**
