### PR TITLE
relnotes for deploy 20190206

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Comment by ltclm** [comment]
@Brunim28 the following layer is not yet in the releasenotes:
ch.bfe.bikesharing

@pakb the following layer is not yet in the releasenotes:
ch.bazl.hindernisbegrenzungsflaechen-perimeter

**Comment by AFoletti** [comment]
Bikesharing does not need to appear in the relnotes. It's just a maintenance update

**Comment by pakb** [comment]
@ltclm As my layer is not visible on map.geo.admin.ch, do I need to mention it anyway in the relnote?

**Comment by danduk82** [comment]
@AFoletti , can you reivew the release notes please? Can we merge them?

**Comment by AFoletti** [comment]
I'd add the new ch.bazl.hindernisbegrenzungsflaechen-perimeter layer. True, it is not a mapgeoadmin layer but will be present and referenced in the API.
Otherwise, LGTM

**Comment by pakb** [comment]
Where can I find the english translated name of my layer?

**Comment by AFoletti** [comment]
LGTM

**Pull request merged**
