### PR TITLE
ch.bafu.hydrologie-hydromessstationen

### PR DESCRIPTION
**Pull request by simonevonheute**
Testlink: https://mf-geoadmin3.dev.bgdi.ch/src/?api_url=dai_lhg&topic=bafu&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bafu.hydrologie-hydromessstationen&X=164469.98&Y=623414.94&zoom=5&catalogNodes=687

New footprint (hydrological bassin) when clicking on measure point.

### CODE REVIEW

**Comment by simonevonheute** [comment]
Abgabedatum:
17.08.2016

**Comment by simonevonheute** [comment]
do not forget to deploy bafu_master on prod.

**Comment by oterral** [comment]
Fill the deploy doc. I sent you an email.

**Comment by loicgasser** [comment]
Shouldn't we have also the points in a geomtry collection? @simonevonheute ?

**Pull request merged**
