### PR TITLE
[WIP] add plz6 to identify result

### PR DESCRIPTION
**Pull request by ltclm**
@davidoesch please test [here](https://mf-geoadmin3.dev.bgdi.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.swissimage&layers=ch.bfs.gebaeude_wohnungs_register&api_url=dev_ltclm_bfs_plzz&X=246870.87&Y=682551.75&zoom=11)

### CODE REVIEW

**Comment by gjn** [comment]
With this solution, the identify request itself contains pzz, not plz6. Only the tooltip shows the plz6.

The manipulation should be done on model level - or best, during data import, as the pzz is pretty useless otherwise, no?

**Comment by ltclm** [comment]
youre right. i will create a view in the database.

**Comment by ltclm** [comment]
I have configured a view which is calculating plz6. Everything is working fine in the testlink above but
jenkins has some problems now:
```
LIGNE 2 : FROM (SELECT bfs.view_adr.gkody AS bfs_view_adr_gkody, bfs.v...
                       ^
 'SELECT count(*) AS count_1 \nFROM (SELECT bfs.view_adr.gkody AS bfs_view_adr_gkody, bfs.view_adr.gkodx AS bfs_view_adr_gkodx, bfs.view_adr.egid_edid AS bfs_view_adr_egid_edid, bfs.view_adr.egid AS bfs_view_adr_egid, bfs.view_adr.strname1 AS bfs_view_adr_strname1, bfs.view_adr.deinr AS bfs_view_adr_deinr, bfs.view_adr.plz4 AS bfs_view_adr_plz4, bfs.view_adr.plz6 AS bfs_view_adr_plz6, bfs.view_adr.plzname AS bfs_view_adr_plzname, bfs.view_adr.gdename AS bfs_view_adr_gdename, bfs.view_adr.gdekt AS bfs_view_adr_gdekt, bfs.view_adr.dstrid AS bfs_view_adr_dstrid, bfs.view_adr.gkplaus AS bfs_view_adr_gkplaus, bfs.view_adr.gstat AS bfs_view_adr_gstat, bfs.view_adr.gdenr AS bfs_view_adr_gdenr, bfs.view_adr.ggbkr AS bfs_view_adr_ggbkr, bfs.view_adr.bgdi_created AS bfs_view_adr_bgdi_created, bfs.view_adr.the_geom AS bfs_view_adr_the_geom \nFROM bfs.view_adr) AS anon_1' {}
```
the view has all the attributes which are configured in the model. Have no idea why the query above has been executed...

**Comment by ltclm** [comment]
the model [here ](https://github.com/geoadmin/mf-chsdi3/blob/dev_ltclm_bfs_plzz/chsdi/models/vector/kogis.py#L162) is using two more columns.
I have added them to the view and restartet jenkins.

**Comment by ltclm** [comment]
jenkins test

**Comment by gjn** [comment]
Thanks alot.

**Pull request merged**
