### PR TITLE
Add a extended tooltip for lubis layers

### PR DESCRIPTION
**Pull request by Sgachet**
@pfanguin could you please review this PR ? This is only an update of the tooltip (extended tooltip) 

[test link](https://mf-geoadmin3.dev.bgdi.ch/ltgas/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&layers_timestamp=&X=130690.00&Y=617280.00&zoom=5)

### CODE REVIEW

**Comment by loicgasser** [comment]
In the title you mean add extended tooltip?
Also in your testlink I still see the previous tooltip.
Could you deploy the branch and use the `api_url` permalink parameter. If you don't know how to do it, please ask @pfanguin and add it to the doc if it's missing.
So I am waiting for a correct test link.

**Comment by Sgachet** [comment]
Test link : https://mf-geoadmin3.dev.bgdi.ch/ltgas/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgas_luftbilder&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.lubis-luftbilder_schraegaufnahmen&layers_timestamp=

**Comment by pfanguin** [comment]
@davidoesch maybe an iframe for the map in the extended tooltip ?

**Comment by pfanguin** [comment]
Yes, but an iframe with black and white map ?

**Comment by davidoesch** [comment]
Use the same mako... Use the api with black and white map. Loads faster. Iframe components are too big for the mobile screen when used in expert  tooltips

**Comment by pfanguin** [comment]
@Sgachet : you can use the iframe for the map in the extended tooltip.

**Comment by procrastinatio** [comment]
jenkins test

**Comment by loicgasser** [comment]
error is related to bav.schienennetz_segment.id
ping @rebert 
See also https://github.com/geoadmin/mf-chsdi3/pull/2377

**Comment by loicgasser** [comment]
Is it still WIP or ready for review?

**Comment by loicgasser** [comment]
@Sgachet could you deploy a branch and provide a stable test link? Thanks, might be useful. Also could you edit the description (what you want to achieve, add, remove etc....)

**Comment by Sgachet** [comment]
@loicgasser now it's ready to review, 

and here a test link for the 5 layers ( ch.swisstopo.lubis-luftbilder_schwarzweiss, ch.swisstopo.lubis-luftbilder_farbe, ch.swisstopo.lubis-bildstreifen, ch.swisstopo.lubis-luftbilder_infrarot and ch.swisstopo.lubis-luftbilder_schraegaufnahmen

https://mf-geoadmin3.dev.bgdi.ch/ltgas/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgas_luftbilder&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.lubis-luftbilder_schraegaufnahmen,ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe,ch.swisstopo.lubis-bildstreifen,ch.swisstopo.lubis-luftbilder_infrarot&layers_timestamp=,99991231,99991231,,99991231&X=136650.00&Y=645500.00&zoom=1

**Comment by loicgasser** [comment]
Very good, tested also. Thanks

**Pull request merged**
