### PR TITLE
Remove bakom layers

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by ltclm — APPROVED** [review]
lgtm, thank you!
@consta-v do we have to deploy this before the next deploy?

**Review by rebert — APPROVED** [review]

**Comment by consta-v** [comment]
Hi @ltclm 
For me, it is not necessary to deploy this change. The effort to do so is not justified for such a small change. You can let it like this. These layers will be updated in the next weeks anyway.

**Comment by ltclm** [comment]
thank you for the feedback @consta-v 
we will publish this with the next deploy.

**Comment by b4l** [comment]
@ltclm & @faselm i think we can close this as there will be an actual update so that the announcement just proceeds it.

**Pull request closed without merging**
