### PR TITLE
update date format for energiestaedte

### PR DESCRIPTION
**Pull request by rfrancel**

### CODE REVIEW

**Comment by AFoletti** [comment]
LGTM, once the tests pass. But it's not this branch's fault in mz opinion ;)

**Comment by pfanguin** [comment]
jenkins test

**Comment by loicgasser** [comment]
Can we have just a function for that please?
Did you change the column type?
You shouldn't have to cast it to a date. Taht s the advantage of using the correct column type.

**Comment by AFoletti** [comment]
the column type change is initialized, but it will not be done in 5 minutes

**Comment by loicgasser** [comment]
Can you use one function from helpers instead?
Please stop duplicating code everywhere.

**Pull request merged**
