### PR TITLE
remove cadastral timestamp workaround

### PR DESCRIPTION
**Pull request by ltclm**
will fix timestamp issues with ToD
https://github.com/geoadmin/service-proxywms/pull/209

### CODE REVIEW

**Comment by ltclm** [comment]
we can revert the service-proxywms hack afterwards

**Comment by loicgasser** [comment]
what about the hack just after can we get rid of it?

**Comment by loicgasser** [comment]
All AWS related tests will fail because we couldn't use instance roles. Some cross account bucket policies issues with KML bucket...

**Comment by loicgasser** [comment]
I am deploying with the hack. It's ready.
I'll remove after.
Otherwise we'll have to redeploy bod as well.

**Comment by ltclm** [comment]
your're right, i have removed the zeitreihen workaround too.

**Comment by ltclm** [comment]
thank you @loicgasser

**Pull request merged**
