### PR TITLE
update energieforschung model

### PR DESCRIPTION
**Pull request by rfrancel**

### CODE REVIEW

**Comment by AFoletti** [comment]
test fails. Did you start from a clean and updated master? Is the new table available on dev?

**Comment by rfrancel** [comment]
i deployed th DB on dev, how can I run the jenkins test again to see if it passes?

**Comment by gjn** [comment]
By writing 'jenkins test', you launched it :)

**Comment by rfrancel** [comment]
Ah thanks!

**Comment by AFoletti** [comment]
all good now :)

**Comment by oterral** [comment]
@AFoletti can you fix your branches conf on apache please :)

**Pull request merged**
