### PR TITLE
Feature service should return valid GeoJSON

### LINKED ISSUE #3020: API returns invalid GeoJSON
e.g. this request:

http://api3.geo.admin.ch/rest/services/api/MapServer/ch.swisstopo.swissboundaries3d-kanton-flaeche.fill/1?geometryFormat=geojson

is invalid according to http://geojsonlint.com/:

1) response structure is not correct
2) coordinates do not follow the right-hand rule (see GeoJSON specs)

As far as 1) is concerned, the API returns the following structure (I filtered the coordinates out for readability):

https://gist.github.com/p1d1d1/af240b4261f8d0313d75ea56aae7d96e
This is valid JSON but invalid GeoJSON

You'll find a valid (I guess) GeoJSON here:
https://gist.github.com/p1d1d1/a33b090eefd7f2c883479d59b9e742aa

### PR DESCRIPTION
**Pull request by procrastinatio**
:bomb: Please carefully test with https://map.geo.admin.ch?api_url=http://mf-chsdi3.dev.bgdi.ch/fix_3020. 

## Feature Resource
Only service returning GeoJSON

**GeoJSON (one feature)**
http://mf-chsdi3.dev.bgdi.ch/fix_3020/rest/services/api/MapServer/ch.swisstopo.swissboundaries3d-kanton-flaeche.fill/1?geometryFormat=geojson

**GeoJSON (two features)**
http://mf-chsdi3.dev.bgdi.ch/fix_3020/rest/services/api/MapServer/ch.swisstopo.swissboundaries3d-kanton-flaeche.fill/1,2?geometryFormat=geojson

## Identify
A geoJSON feature inside a list of features (yuks!)

http://mf-chsdi3.dev.bgdi.ch/fix_3020/rest/services/api/MapServer/find?layer=ch.bafu.bundesinventare-bln&searchText=Lavaux&searchField=bln_name&returnGeometry=true&geometryFormat=geojson

## Find
A list of geoJSON feature (not a feature collection)
http://mf-chsdi3.dev.bgdi.ch/fix_3020/rest/services/api/MapServer/find?layer=ch.bafu.bundesinventare-bln&searchText=Lavaux&searchField=bln_name&returnGeometry=true&geometryFormat=geojson

Fix #3020

### CODE REVIEW

**Comment by p1d1d1** [comment]
1 and 3 are for me relevant and do their job.
2 and 4 are not relevant and i find the requests make also no sense: one asks for a specific geometryFormat and at the same time he doesn't want a geometry?

@davidoesch a point for the next version pf the API. IMHO the parameter "geometryFormat" should be changed to a more generic "outputFormat"

**Comment by davidoesch** [comment]
@p1d1d1 will take this into RE4 https://jira.swisstopo.ch/projects/BGDIRE4/summary  
-> Can you create there a ticket  follwoing the structure eg as in https://jira.swisstopo.ch/browse/BGDIRE4-39  , focus on the definiton of done

**Comment by p1d1d1** [comment]
I guess because of this?

https://github.com/geoadmin/mf-chsdi3/pull/3021/files#diff-3d6ec0899d4ddab81529319f9f6ee359L381

Won't be possible to have an IF THEN based on the value of the parameter "geometryFormat" ?

**Comment by danduk82** [comment]
I have to check usage

**Comment by pakb** [comment]
@p1d1d1 this will be merged tomorrow, if anything has to be done please notify us quickly.

**Comment by p1d1d1** [comment]
@pakb @procrastinatio the output is still not valid geojson according to http://geojsonlint.com/ --> 

> Line 1: "type" member required

**Pull request merged**
