### PR TITLE
Use general requests interface

### PR DESCRIPTION
**Pull request by loicgasser**
A reason why our `test_wms.py` fails is that we don't take into account the context.
http://docs.python-requests.org/en/v1.2.3/api/

### CODE REVIEW

**Comment by loicgasser** [comment]
@gjn @procrastinatio Quick review merge?

**Comment by gjn** [comment]
Tests failed because of wrong info in the bod (at least recently).

I don't fully understand what this PR adds.

**Comment by loicgasser** [comment]
It's essentially to use the retry option.

**Comment by procrastinatio** [comment]
Nice, for me. We already used `retry`for other tests. Dic you tests also against self-signed certificat we have ?

**Comment by gjn** [comment]
Doesn't having to re-try already say that something is fishy?

**Comment by loicgasser** [comment]
A lot of things can go wrong when performing HTTP requests, networking issue, WMS server being restarted, DB being restarted, Puppet, timeouts ... you got the picture. I don't think all the tests should fail if a request failed one time on a server. This is time consuming to analayse redeploy etcc... So a retry of 2 or 3 should be ok.

**Comment by loicgasser** [comment]
For external resources only of course.

**Comment by gjn** [comment]
I agree for external resources (not managed by us). I also agree on dev resources.

But for our integration and production resources, we should always be up. We should not accept downtimes there, even if they are mini downtimes.

And here we are testing wms production, no?

**Comment by loicgasser** [comment]
these tests are env dependent. dev tests WMS dev etcc.

**Comment by gjn** [comment]
So I would propose to not use retry for int/prod and to use retry=3 for dev.

**Comment by loicgasser** [comment]
ok done

**Comment by gjn** [comment]
Thanks alot!

**Pull request merged**
