### PR TITLE
Rewrite schema wmts validation

### PR DESCRIPTION
**Pull request by loicgasser**
This a rewrit of our schema validation test for wmts.

We give up on subprocesses and temp files. It's significantly faster.

https://github.com/geoadmin/mf-chsdi3/issues/1433

### CODE REVIEW

**Comment by gjn** [comment]
That's awesome. Two things though:

a) This test somehow introduces a side-effect that makes other tests of the same class fail. I couldn't track it down. Do you have any idea?
b) We should also add `21781` to the list of EPSG to be verified in this test.

**Comment by procrastinatio** [comment]
@gjn 

a/ It is not could practice to make loops within a test. Use generator to test each case individually (as in  [test_wmtsgettile.py](https://github.com/geoadmin/mf-chsdi3/blob/gal_schema_validate_getcap/chsdi/tests/mapproxy/test_wmtsgettile.py) )
b/ Yes, *21781* is missing

**Comment by loicgasser** [comment]
@procrastinatio @gjn adapted according to your comments

**Comment by gjn** [comment]
This is good for me.

I think we have to live with the external xsd. Usually, they should have high availability, as I assume other tools/apps are depending on it also.

**Pull request merged**
