### PR TITLE
[WIP]Optimization Makefile: Cache last value

### PR DESCRIPTION
**Pull request by nadine-piveteau**
Values of environment variables are cached. 
Related to PR #2619 .

### CODE REVIEW

**Comment by loicgasser** [comment]
thanks you can already debug it using Jenkins
Here is the message I get.

Creating apache/wsgi.conf...
usage: usage: %prog [FILENAME] [-h] [--var VAR] [--template-dir TEMPLATE_DIR]
                               [input]
usage: %prog [FILENAME]: error: unrecognized arguments: apache/wsgi.conf.in

**Comment by nadine-piveteau** [comment]
I fixed this error, however, I get now an integration test error:

`FAIL: test_identify_order_by_distance (chsdi.tests.integration.test_identify_service.TestIdentifyService)
Traceback (most recent call last):`
  `File "/var/lib/jenkins/workspace/PR_chsdi3/chsdi/tests/integration/test_identify_service.py", line 730, in test_identify_order_by_distance`
    `self.assertNotEqual(firstBefore, firstAfter)
AssertionError: u'75b' == u'75b'`

This test aimes to verify whether the function `order_by_distance` reorders the entries in the response according to the distance when the parameter `order=distance` given. 
If I run it on localhost  (be it in the master branch or in my branch) I get the same response in the same order, with and without parameter `order=distance`.
This is however not the case when I run it on api.geo.admin.ch: 
[link without order=distance](http://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometryType=esriGeometryPoint&layers=all:ch.bfs.gebaeude_wohnungs_register&geometryFormat=geojson&geometry=643952.5,164121.24999999997&imageDisplay=1920,765,96&mapExtent=641960.1008933608,163518.83578498938,646760.1008933608,165431.33578498938&tolerance=50)
[link with order=distance](http://api3.geo.admin.ch/rest/services/all/MapServer/identify?order=distance&geometryType=esriGeometryPoint&layers=all:ch.bfs.gebaeude_wohnungs_register&geometryFormat=geojson&geometry=643952.5,164121.24999999997&imageDisplay=1920,765,96&mapExtent=641960.1008933608,163518.83578498938,646760.1008933608,165431.33578498938&tolerance=50)

Doesn't api.geo.admin.ch correspond to the master branch? Or, any suggestion how to approach this issue?

**Comment by loicgasser** [comment]
Not related I ll fix

**Comment by oterral** [comment]
jenkins test

**Comment by gjn** [comment]
@nadine-piveteau will check again.

**Comment by nadine-piveteau** [comment]
There was one test regarding CadastralWebMap that failed. I address the failing test #2821. 
@loicgasser, is there anything more to do for this PR?

**Comment by loicgasser** [comment]
other PR has been open

**Pull request closed without merging**
