### PR TITLE
Add legends for ch.meteoschweiz.klimanormwerte-sonnenscheindauer-*

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by b4l — CHANGES_REQUESTED** [review]
@faselm could you please provide a test link? Thanks!

**Comment by faselm** [comment]
@b4l Here it is: https://mf-chsdi3.dev.bgdi.ch/ltfas_sonnenscheindauer/shorten/8c4d028e17

**Review by b4l — APPROVED** [review]

**Comment by b4l** [comment]
Looks good. Only rm is missing, maybe coppy from german or merge if its fine with the customer/boss.

**Review by rebert — CHANGES_REQUESTED** [review]
lgtm. but it is strange that your pr has commits from @procrastinatio

**Comment by faselm** [comment]
@rebert I removed the earlier commits from @procrastinatio by rebasing on data, I checked out from master at first

**Comment by rebert** [comment]
@faselm now there are just to legends in rm as change in this pr

**Comment by faselm** [comment]
Ok, it should be good now

**Review by marionb — APPROVED** [review]
LGTM now

**Pull request merged**
