### PR TITLE
ch.bav.lage-stoerfallverordnung_eisenbahnanlagen

### PR DESCRIPTION
**Pull request by Brunim28**
This is a first integration
No legend given
No tooltip needed
No Sphinx service

### CODE REVIEW

**Comment by Brunim28** [comment]
[test link](https://mf-geoadmin3.dev.bgdi.ch/ltbrg/index.html?wms_url=%2F%2Fwms-test.dev.bgdi.ch%2Fdev_ltbrg_abnahme%2F%3Flang%3Dxx&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fbrg_stoerfallverordnung_eisenbahnanlagen&topic=ech&config_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fbrg_stoerfallverordnung_eisenbahnanlagen%2Fconfigs&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bav.lage-stoerfallverordnung_eisenbahnanlagen&zoom=2&E=2676657.53&N=1195436.47&lang=de)

**Comment by Brunim28** [comment]
[test link](https://mf-chsdi3.dev.bgdi.ch/brg_stoerfallverordnung_eisenbahnanlagen/shorten/81193bb64b)

bav gave no translations for the legend for the moment. Right now: technical name is provided.

**Comment by Brunim28** [comment]
[updated link](https://mf-chsdi3.dev.bgdi.ch/ltbrg/shorten/8175f2de77)

**Comment by ltclm** [comment]
if there's no tooltip, i think we dont need to add a model at all.

**Comment by Brunim28** [comment]
@ltclm Hi Marcel, so I deleted the model. Can you please check if you can see the legends? I have some issues with my test link and Mario could not see them. 
[test link](https://mf-chsdi3.dev.bgdi.ch/brg_stoerfallverordnung_eisenbahnanlagen/shorten/81a34464cc)

**Comment by ltclm** [comment]
the legends are there, maybe some cache effect. It seems to work fine without model. lagtm.
If your work is finished, you should remove [WIP] from the pr name.

**Comment by Brunim28** [comment]
@ltclm Thank you for the confirmation! 
Yes my work is finished, I removed [WIP] and squashed the commits.
Last things to do are merging the wms and chsdi PRs and prepare the rel note for the deploy.

**Pull request merged**
