### PR TITLE
Add tilematrixes down to 20 for epsg:4326

### PR DESCRIPTION
**Pull request by procrastinatio**
Démo [GetCapabilities](http://mf-chsdi3.dev.bgdi.ch/mom_4326_tilematrixset/EPSG/4326/1.0.0/WMTSCapabilities.xml)

Integrated in [ArcGisOnline](http://www.arcgis.com/home/webmap/viewer.html?webmap=bdf240d7ba424329a1ee49bc7c04d582)

ArcGis REST JS [API integration](http://codepen.io/procrastinatio/full/b65a6267e8ff6e9a1942adaed8cfb988/)

See https://github.com/geoadmin/service-mapproxy/issues/42

:bomb: Must be merge/deployed togehther with https://github.com/geoadmin/service-mapproxy/pull/41

### CODE REVIEW

**Comment by loicgasser** [comment]
While you mention epsg:4326 in the title of this PR, all your demo links point to epsg:3857 (web mercator) which is confusing.
Which one do you want to change?

Also could you add a test?

For epsg:3857 we already go up to zoom 19.

One last question how did you get the scaledemnominator from? Could you put your source/formula?

**Comment by procrastinatio** [comment]
@loicgasser Corrected the links.

Checked values according to http://www.ngs.noaa.gov/GeoServer/gwc/service/wmts?REQUEST=getcapabilities

**Comment by procrastinatio** [comment]
From mapproxy, except we use a *2x1* matrix at level *0*, instead of *1x1*

```
$ .build-artefacts/python-venv/bin/mapproxy-util grids  \
         -f mapproxy/mapproxy.yaml -g GLOBAL_GEODETIC
GLOBAL_GEODETIC:
    Configuration:
        bbox*: [-180.0, -90.0, 180.0, 90.0]
        origin: 'sw'
        srs: 'EPSG:4326'
        tile_size*: [256, 256]
    Levels: Resolutions, # x * y = total tiles
        00:  1.40625,                #      1 * 1      =          1
        01:  0.703125,               #      2 * 1      =          2
        02:  0.3515625,              #      4 * 2      =          8
        03:  0.17578125,             #      8 * 4      =         32
        04:  0.087890625,            #     16 * 8      =        128
        05:  0.0439453125,           #     32 * 16     =        512
        06:  0.02197265625,          #     64 * 32     =       2048
        07:  0.010986328125,         #    128 * 64     =       8192
        08:  0.0054931640625,        #    256 * 128    =      32768
        09:  0.00274658203125,       #    512 * 256    =     131072
        10:  0.001373291015625,      #   1024 * 512    =     524288
        11:  0.0006866455078125,     #   2048 * 1024   =      2.10M
        12:  0.00034332275390625,    #   4096 * 2048   =      8.39M
        13:  0.000171661376953125,   #   8192 * 4096   =     33.55M
        14:  8.58306884765625e-05,   #  16384 * 8192   =    134.22M
        15:  4.291534423828125e-05,  #  32768 * 16384  =    536.87M
        16:  2.1457672119140625e-05, #  65536 * 32768  =   2147.48M
        17:  1.0728836059570312e-05, # 131072 * 65536  =   8589.93M
        18:  5.364418029785156e-06,  # 262144 * 131072 =  34359.74M
        19:  2.682209014892578e-06,  # 524288 * 262144 = 137438.95M
```

**Comment by loicgasser** [comment]
Looking good, I ll make a few tests and merge. Thanks a lot

**Comment by loicgasser** [comment]
I think there is a problem with the bounding box definition.
According to http://www.ogcnetwork.net/node/491 It lat/lon and we have lon/lat ..

4326 (axis order latitude, longitude)
I'll give it a try.

**Comment by loicgasser** [comment]
It is actually lon/lat for `<ows:WGS84BoundingBox>`

**Comment by loicgasser** [comment]
Ok I know why the zoom to layer in QGIS doesn't work:
https://hub.qgis.org/issues/12432
So it's actually a pretty nasty bug in QGIS, but other than that WMTS works as expected.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/service-mapproxy/pull/41

**Pull request merged**
