### PR TITLE
SIF integration. Ready to merge

### PR DESCRIPTION
**Pull request by AFoletti**

### CODE REVIEW

**Comment by oterral** [comment]
@AFoletti can we have a branch to test pls?

**Comment by oterral** [comment]
@AFoletti  can you optimize the images https://tinypng.com/ pls

**Comment by procrastinatio** [comment]
It also make the 'master' to fail.

**Comment by AFoletti** [comment]
the png should already be optimized.
About the master failure, I'm looking at it

**Comment by oterral** [comment]
@AFoletti  this one is not optimized: ch.bav.sachplan-infrastruktur-schifffahrt_ausgangslage_de . I haven't test the other.

**Comment by AFoletti** [comment]
ok, I'll pass them through the bloody website again

**Comment by AFoletti** [comment]
posted a fix for the crash and some PNGs which were not optimized somehow

**Comment by procrastinatio** [comment]
Squash ?

**Comment by gjn** [comment]
jenkins test

**Comment by oterral** [comment]
Is it normal that chsdi/static/images/legends/ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_it.png
and other legends are so different?

**Comment by AFoletti** [comment]
@oterral my bad. *censured* datenherr sent 4 different versions and I got the wrong one for 4 of them. Next commit will fix the issue

Now I need some help to rewrite history ehehe

**Comment by AFoletti** [comment]
phew...

**Comment by gjn** [comment]
Thanks @AFoletti for the round-trips, including elephants.

**Pull request merged**
