### PR TITLE
Notruf 143, 144 & 147

### PR DESCRIPTION
**Pull request by b4l**
Test link: https://mf-chsdi3.dev.bgdi.ch/ltbal_notruf/shorten/8abc517511

### CODE REVIEW

**Comment by b4l** [comment]
Tets link: https://mf-chsdi3.dev.bgdi.ch/bteuscher/shorten/89c4a7069f

**Comment by rebert** [comment]
cool. legends?

**Comment by ltclm** [comment]
is this for this weeks deploy? If yes please tag with milestone 2020-07-01

**Comment by b4l** [comment]
> is this for this weeks deploy? If yes please tag with milestone 2020-07-01

no this will come in a later milestone

**Review by rebert — APPROVED** [review]

**Pull request merged**
