### PR TITLE
wonder how this passed qs

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Review by faselm — APPROVED** [review]

**Comment by ltshb** [comment]
@rebert should not this be on `master` ? and PR title could be better.

**Comment by rebert** [comment]
@ltshb this is a cherry-pick from master

**Comment by ltshb** [comment]
Well no need for cherry pick does the `develop-2022-10-26` already contains commit ?

**Review by ltshb — CHANGES_REQUESTED** [review]
Avoid cherry-pick when not needed, this avoid later on git conflict.

**Pull request closed without merging**
