### PR TITLE
Searchable attribute

### PR DESCRIPTION
**Pull request by pfanguin**

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@procrastinatio could you please review ?

**Comment by loicgasser** [comment]
This looks good te me. This naming convention will generate a lot redundance accross the projekt, but if you're ok with it we can carry on and change everything.

**Comment by procrastinatio** [comment]
Why do some attributes follow the <layerId>.<attribute> convention and some not ?

**Comment by loicgasser** [comment]
@procrastinatio Do you have an exemple?

**Comment by pfanguin** [comment]
Because some mako are used by various layer. So I have defined these attributes lake that : 

ivs_slaname = c['layerBodId'] + '.' + 'ivs_slaname'
ivs_nummer = c['layerBodId'] + '.' + 'ivs_nummer'
ivs_signatur = c['layerBodId'] + '.' + 'ivs_signatur'

**Comment by procrastinatio** [comment]
OK, but this was `_(ivs_slaname)` and so one

**Comment by pfanguin** [comment]
_(ivs_slaname) is defined by this : ivs_slaname = c['layerBodId'] + '.' + 'ivs_slaname'

**Comment by procrastinatio** [comment]
OK, event. *squash* commits into one.

**Pull request closed without merging**
