### PR TITLE
Feature bgdiinf sb 1527 fix weighting of exact search result

### PR DESCRIPTION
**Pull request by ltclm**
This issue has been initially introduced with the combination of exact and wildcard search in swisssearch in a multi-query [1].
The multi query has been introduced, specified and updated here:
#3073
#3148

With this multi search search we have introduced a bug that has been first reported here:
https://github.com/geoadmin/mf-chsdi3/issues/3573

The main reason for the bug was the wrong combination of the two result objects in python code and the wrong ranking of the results.

**1st fix:**
A first attempt to solve the issue was not complete:
https://github.com/geoadmin/mf-chsdi3/pull/3575
There were still some exact match results when searching for single words to far down in the results, p.e. Esel, Rotten, Loch .

**2nd fix**
The second attempt fixed this and did a clean prepend of exact match before wildcard match results, but the weighting of the results was still wrong:
https://github.com/geoadmin/mf-chsdi3/pull/3581

This pr is building on top of these two fixes and is setting the correct weighting for exact match results. Until now both results of the multi query (exact and wildcard) have been weighted / ranked with the same sphinx ranker: SPH_RANK_WORDCOUNT

With this pr the exact match results will be weighted with the default rankig method: SPH_RANK_PROXIMITY_BM25

This will result in exact match results having a much higher weight than wildcard match results. 

[Testlink](https://mf-chsdi3.dev.bgdi.ch/feature_BGDIINF_SB-1527/shorten/8d7d65425b)
examples:
https://mf-chsdi3.dev.bgdi.ch/feature_BGDIINF_SB-1527/rest/services/ech/SearchServer?sr=2056&searchText=rotten&lang=de&type=locations
https://mf-chsdi3.dev.bgdi.ch/feature_BGDIINF_SB-1527/2012090912/rest/services/ech/SearchServer?sr=2056&searchText=dorfstrasse%201%205442%20Fislisbach&lang=de&type=locations

[1] http://sphinxsearch.com/docs/current/multi-queries.html

### CODE REVIEW

**Comment by davidoesch** [comment]
From my point of view:  good. 
we need to annoucne this to our customers in the release notes that we will change the request so they can test it for 2 months till the next deploy

**Comment by ltclm** [comment]
ok, i will prepare a test link on integration for that.

**Review by boecklic — APPROVED** [review]
Looks good.

**Review by rebert — APPROVED** [review]
thanks @ltclm

**Comment by ltclm** [comment]
thanks for solving the conflicts @rebert i missed adding this pr to the milestone, sorry.

**Comment by ltclm** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/3643

**Pull request merged**
