### PR TITLE
Add custom geoalchemy2 egg for 3D support

### PR DESCRIPTION
**Pull request by loicgasser**
This is to solve 
https://github.com/geoadmin/mf-chsdi3/issues/1224
and
https://github.com/geoadmin/mf-chsdi3/issues/1150

@ltclm Let me know what table should be used to use Lubis original 3D data.

FYI: vbs and are layers are really dumm 3D layers as the third dimension is always equal to 0... (??)
Hope it makes a little more sense for lubis data.

No issue in geoadmin, which is a good thing.

### CODE REVIEW

**Comment by ltclm** [comment]
Hi Loic
There is no 3d data anymore in the lubis database on db master (pg-0.dev.bgdi.ch). 

I have changed the FME workbench and just re-imported the 3d data directly in the pgcluster.dev.bgdi.ch database (the master is still in 2d mode). 
The mf dev staging should have access to the 3d data now, you can use the default tables.

**Comment by ltclm** [comment]
```sql
select ebkey,st_astext(the_geom),rotation FROM luftbilder_swisstopo_bw limit 5;
     ebkey      |          st_astext           | rotation
----------------+------------------------------+----------
 19542890031226 | POINT Z (745338 289100 4100) |        0
 19722800013381 | POINT Z (703248 280180 3500) |        0
 19609991096473 | POINT Z (574728 96866 4620)  |        0
 19662560045775 | POINT Z (689600 256000 3800) |        0
 19892360012393 | POINT Z (736826 236000 5200) |        0
(5 rows)

```

**Comment by procrastinatio** [comment]
As the solution is buried down in a tar.gz file, this how it was solved (thanks to @fredj)

```python
#######################################################
from sqlalchemy import create_engine, Table, MetaData from sqlalchemy.orm import sessionmaker

from geoalchemy2.shape import to_shape

engine = create_engine('postgresql://www-data:www-data@pgcluster.dev.bgdi.ch/vbs', echo=True) table = Table('territorialregionen', MetaData(), autoload=True, autoload_with=engine)

session = sessionmaker(bind=engine)()

item = session.query(table).first()

shape = to_shape(item.the_geom)
#######################################################

And I've the error but if I change:
diff --git a/geoalchemy2/types.py b/geoalchemy2/types.py index 54563fe..24561d6 100644
--- a/geoalchemy2/types.py
+++ b/geoalchemy2/types.py
@@ -100,7 +100,7 @@ class _GISType(UserDefinedType):
         return '%s(%s,%d)' % (self.name, self.geometry_type, self.srid)
 
     def column_expression(self, col):
-        return func.ST_AsBinary(col, type_=self)
+        return func.ST_AsEWKB(col, type_=self)
 
     def result_processor(self, dialect, coltype):
         def process(value):

```



See also https://github.com/geoalchemy/geoalchemy2/pull/92

**Comment by procrastinatio** [comment]
OK

[ch.are.alpenkonvention](http://mf-chsdi3.dev.bgdi.ch/gal_3d_support/rest/services/ech/MapServer/identify?geometry=704206.7132676127,133316.31032245018&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1280,939,96&layers=all:ch.are.alpenkonvention&mapExtent=286906.7132676126,-19433.689677549875,1118906.7132676127,590916.3103224501&tolerance=5)

[ch.vbs.territorialregionen](http://mf-chsdi3.dev.bgdi.ch/gal_3d_support/rest/services/ech/MapServer/identify?geometry=692124.830021982,220998.9882507511&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1600,1080,96&layers=all:ch.vbs.territorialregionen&mapExtent=681014.830021982,215908.9882507511,697014.830021982,226708.9882507511&tolerance=5)

**Comment by ltclm** [comment]
Hi Loic
Im not sure if these lubis db changes are breaking some tests on dev.
Anyway i have created a database **lubis_3d**. Please use this database for lubis tests.
I will now replace the lubis db with the original one.

Marcel

**Comment by procrastinatio** [comment]
@loicgasser we should event. add some systematic test for all layers and services, on one random features each, to see if something breaks.

**Comment by loicgasser** [comment]
Agree

**Comment by procrastinatio** [comment]
OK, LGTM

**Comment by loicgasser** [comment]
@ltclm We'll take care of Lubis in a separate PR.
Same for tests.

**Comment by gjn** [comment]
We should try to re-use the official geoalchemy release. The referrenced PR in geoAlchemy is still open (https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py), but I think we can still use current geoalchemy master and simply overrate the class with our needed functionality. 

Then there would be no need to use a custom egg.

I'm working on geoJson loading from DB where I will try the overwrite approach. If I'm successfull, I can try to do the same to revert/replace this PR.

**Pull request merged**
