### PR TITLE
add helper function to format datenstand dates with time

### PR DESCRIPTION
**Pull request by ltclm**
the function splits the text, detects YYYYMM and YYYYMMDD dates and reformats them to DD.MM.YYYY
will be used to publish dates with time https://github.com/geoadmin/mf-chsdi3/pull/1885

### CODE REVIEW

**Comment by loicgasser** [comment]
Ok that's nice I'am adding a test now. Thks a lot @ltclm !

**Comment by loicgasser** [comment]
So we don't have the time as before, but we now have the date and it comes from the DB. I think this should be enough.

**Comment by ltclm** [comment]
i will add the time part as soon as this pr is deployed to prod

**Comment by loicgasser** [comment]
ok great thanks @ltclm I'll merge this one then as we're deploying tomorrow.

**Pull request merged**
