### PR TITLE
Update model ch.bakom.notruf

### PR DESCRIPTION
**Pull request by faselm**
Test link: https://mf-chsdi3.dev.bgdi.ch/ltfas_bakom_notruf/shorten/9259fb9292

### CODE REVIEW

**Review by ltclm — CHANGES_REQUESTED** [review]
legends are not translated:
image

the rest looks good to me 👍

**Review by ltclm — APPROVED** [review]
perfect, thank you!

**Comment by b4l** [comment]
@faselm can you rebase on data? thanks!

**Comment by faselm** [comment]
@b4l rebased...

**Pull request merged**
