### PR TITLE
Remove default h filter from wmts getCap

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for layer title:
https://github.com/geoadmin/mf-chsdi3/issues/1215#issuecomment-69910527

probably related to mako update

### CODE REVIEW

**Comment by gjn** [comment]
Officially [1][2] apostrophe character (`'`) needs to be escaped in xml. But instead of what @ltclm sees (`&amp;amp;#39;`) it should be converted to `&apos;`. I'm not sure if this PR results in a valid XML as per the specification.

IMO, we should rather find out why the x filter does not put the correct replacement in.

[1] http://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents#1091953
[2] http://www.w3.org/TR/xml/#syntax

I'm on record saying that xml sucks...here's one reason.

**Comment by loicgasser** [comment]
Mmm... it might be &apos; already. you browser reads it as XML so you wouldn't see apos anyway. right?

**Comment by loicgasser** [comment]
check this one. http://www.w3schools.com/xml/note.xml you don't see apos anywhere..

**Comment by loicgasser** [comment]
http://docs.makotemplates.org/en/latest/filtering.html
none of those filters make sense. Could you enlight me?

**Comment by gjn** [comment]
It's `&#39;` in the raw response, which is apostrophe escaped for html, not for xml. I'm confused.

**Comment by loicgasser** [comment]
maybe pyramid take care of it when you define the content-type now (update 2 weeks ago). In the internal machinery, I'll try to find a refrence.

**Comment by loicgasser** [comment]
ok just saw your comment. previous one doesn't make sense then.

**Comment by gjn** [comment]
yes, might be pyramids

**Comment by cedricmoullet** [comment]
If we apply this PR, the XML is not valid anymore. @loicgasser is it not possible to generate a valid XML ?

**Comment by loicgasser** [comment]
Please have a look at mako's source code `'` are replaced with `&#39;`

so it should be valid. Here we simply avoid to escape multiple times.

**Comment by loicgasser** [comment]
See this link: https://bitbucket.org/zzzeek/mako/src/b6d0479034e4f379576caa6eb9ef3e32369c333f/mako/filters.py?at=master

Please merge if you are convinced otherwise, I'll make a utility function to transform `&#39;` into `&apos;`

**Comment by procrastinatio** [comment]
We could also use `<![CDATA[  ...   ]]>`to escape all contents

**Comment by procrastinatio** [comment]
Otherwise, all tests pass. So it is OK.

**Comment by loicgasser** [comment]
`<![CDATA[ ... ]]>` is mainly use for script no?
+ `Everything inside a CDATA section is ignored by the parser.`
Which is not really what we want.
I think this can merged.

**Comment by loicgasser** [comment]
@gjn Is it ok if I merge?

**Comment by gjn** [comment]
Sorry for being late. Are we sure we don't have `&`, `<`, `>` in the source? Because those need to be escaped by the filter Not sure if we can be sure, especially since data comes from geocat, which might change without us knowing.

Problem is that mako assumes we want to create html, even though doc says `x` filter is for xml.

On the other hand, it seems like original problem is that it was escaped twice, so maybe pyramids escaped it as well and this is now ok?

Can we try to read this data coming from this branch into ArcGis?

**Comment by loicgasser** [comment]
Found the line
default_filters = sget('default_filters', 'h')

So per default all mako template are escaped with h.
This is for security reasons apparently.
So I need to disable the default mako filter for xml and use x instead...

**Comment by loicgasser** [comment]
Also n disable all default filters. Might just need to add this filter first every time we need to escape xml. Page filters are ignored for some obscure reasons..

**Comment by loicgasser** [comment]
Ok PR updated. (Train rides can be useful)
It absolutely doesn't change a thing, but at least we fully understand what's going on.

It is really missing in the doc. As in developement.ini.in I did not specify anything for `default_filters` I did not excpect that.
Reference:
https://github.com/Pylons/pyramid_mako/blob/7e1c63e76c64c8599bd1d0563fce8665a91647ec/pyramid_mako/__init__.py#L189


Please merge.

**Comment by gjn** [comment]
Ha! This explains the double escaping. Can't test now, but according to your refs, this should be good now and assures it's well xml escaped. Good job.

**Pull request merged**
