### PR TITLE
Color service

### PR DESCRIPTION
**Pull request by oterral**
This PR adds a color service which color our maki icons from white to the color (rgb) specified in the url.

http://mf-chsdi3.dev.bgdi.ch/teo_color/color/128,0,25/marker-24@2x.png

### CODE REVIEW

**Comment by loicgasser** [comment]
I had a look at the service and it looks good, I would maybe add a few very simple integration tests.
I guess this PR is pending until we decided how many maki icons we'll be using.

**Comment by gjn** [comment]
jenkins test

**Comment by oterral** [comment]
@loicgasser @procrastinatio ready to merge

**Comment by oterral** [comment]
wait I add a test

**Comment by loicgasser** [comment]
no quite all tests are failing `ImportError: No module named Image`

**Comment by loicgasser** [comment]
Do we need chsdi/static/images/maki/.DS_Store ?

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/blob/teo_color/chsdi/views/color.py#L28
I guess you mean the image name must be defined.

**Comment by loicgasser** [comment]
Could you add this decorator ?
https://github.com/geoadmin/mf-chsdi3/blob/teo_color/chsdi/lib/decorators/__init__.py#L14

I don't want everybody to hack our maki solution.

**Comment by loicgasser** [comment]
`Pillow >= 1.0 no longer supports “import Image”. Please use “from PIL import Image” instead.`

**Comment by loicgasser** [comment]
yes one or 2 tests would be nice.

**Comment by oterral** [comment]
Tests added

**Comment by loicgasser** [comment]
Unrelated failure, due to spot view. It's corrected on master, I just haven't deployed stopo to dev yet.

**Comment by loicgasser** [comment]
What about this `@requires_authorization()` decorator?

**Comment by oterral** [comment]
Added

**Comment by loicgasser** [comment]
LGTM

**Pull request merged**
