### PR TITLE
[WIP] Mapfish Print v3

### PR DESCRIPTION
**Pull request by mariavkourouni**
[Pdf preview examples](http://mf-chsdi3.dev.bgdi.ch/~ltkom/)

### CODE REVIEW

**Comment by mariavkourouni** [comment]
jenkins

**Comment by procrastinatio** [comment]
May be closed once https://github.com/geoadmin/mf-chsdi3/pull/2126 is merged.

Then update in https://github.com/geoadmin/service-print

**Comment by gjn** [comment]
@mariavkourouni Could you tag the branch as a release?

**Comment by mariavkourouni** [comment]
@gjn it's released.

**Comment by mariavkourouni** [comment]
not yet released, I will confirm

**Comment by mariavkourouni** [comment]
ok now I can confirm, it's released

**Pull request closed without merging**
