### PR TITLE
keyword parcel,address can be anywhere in the search text

### PR DESCRIPTION
**Pull request by ltclm**
keyword can be anywhere in the search text, as proposed by @gjn it has to end with colon
https://github.com/geoadmin/mf-geoadmin3/issues/2164

### CODE REVIEW

**Comment by gjn** [comment]
I think such a change needs to be discussed with project managers :)

@davidoesch @cedricmoullet Do you think it's a good idea to change our keyword handling in the search from `parcel` to `parcel:*` ?

**Comment by davidoesch** [comment]
Ouch - what is the user need for this?

**Comment by gjn** [comment]
To avoid something like https://github.com/geoadmin/mf-geoadmin3/issues/2164 and it would open up the possibility to have more keywords.

But it's advanced usage and if not desired we can close this.

**Comment by cedricmoullet** [comment]
@davidoesch this was your idea (inspired from gmail search).
I still think something like that is needed.

**Comment by davidoesch** [comment]
Ok... The  initial idea was to handle it like gmail and operating with tags like "tag: parcel 12345"

**Comment by ponceta** [comment]
Why not separate a bit the things? If I want an adress I do not care about layers or parcels and vice versa?

image

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
Some tests fail with this PR. See https://jenkins.ci.bgdi.ch/job/chsdi3_pullrequests/32/console

**Pull request closed without merging**
