### PR TITLE
[WIP] Script for the differences between old and new catalog service

### PR DESCRIPTION
**Pull request by mariavkourouni**
[Diiferences between the new and old catalog](https://github.com/geoadmin/db/pull/2/commits/b14666eb4d5b9d9e881100bc266a30143478eb49)

### CODE REVIEW

**Comment by gjn** [comment]
To be 'merged' with #2174

**Comment by mariavkourouni** [comment]
Also not needed any more.

**Comment by gjn** [comment]
@mariavkourouni Can we close this? Or do you see use of it?

**Comment by mariavkourouni** [comment]
Yes, we close it

**Pull request closed without merging**
