### PR TITLE
[WIP] added layer ezv.lohnbrennereien

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Comment by loicgasser** [comment]
@mariokeusen @rebert what's the status here?

**Comment by rebert** [comment]
@mariokeusen status: waiting for feedback

**Comment by pakb** [comment]
@rebert : any status update on this?

**Comment by rebert** [comment]
@p1d1d1 can we close this?

**Comment by p1d1d1** [comment]
@rebert yes, this is dead

**Comment by rebert** [comment]
@p1d1d1 thanks for your imediate answer!

**Pull request closed without merging**
