### PR TITLE
Remove format and timebehaviour when not needed

### PR DESCRIPTION
**Pull request by loicgasser**
https://github.com/geoadmin/mf-chsdi3/pull/2510

sorry for the noise

### CODE REVIEW

**Comment by oterral** [comment]
We use it in https://github.com/geoadmin/mf-geoadmin3/blob/aa8628b362d871493880420d2ecbfd657be23f27/src/components/map/MapService.js , are you sure it doesn't impact mf-geoadmin?

**Comment by loicgasser** [comment]
[Test Link](https://mf-geoadmin3.int.bgdi.ch/?api_url=//mf-chsdi3.dev.bgdi.ch/gal_layersconfig)

It shouldn't.

**Comment by loicgasser** [comment]
@oterral Ok with you?
@procrastinatio this doesn't break mapproxy config generation?

**Comment by oterral** [comment]
Yes it's good merge it

**Pull request merged**
