### PR TITLE
geologie geocover add tooltip attributes

### PR DESCRIPTION
**Pull request by alcapat**
Display new attributes (litstrat_link) and (litho, chrono, harmos_rev) in multilingue (de + fr) in the tooltip.
https://jira.swisstopo.ch/browse/BGDIDI_KB-1104

### CODE REVIEW

**Comment by ltclm** [comment]
@alcapat , @AFoletti 
with the new database structure, the feature tooltip (lower zoomlevels) on the ga25 layer is not working anymore:
https://mf-geoadmin3.dev.bgdi.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-geocover,ch.swisstopo.geologie-geologischer_atlas,ch.swisstopo.geologie-geocover.metadata&layers_opacity=0.75,0.75,0.8&E=2680551.71&N=1181817.59&zoom=8&layers_visibility=false,true,false&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltclm

https://mf-chsdi3.dev.bgdi.ch/rest/services/all/MapServer/identify?geometry=2680639.21,1181225.09&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1352,1070,96&lang=de&layers=all:ch.swisstopo.geologie-geologischer_atlas&mapExtent=2678861.71,1180480.09,2682241.71,1183155.09&returnGeometry=true&sr=2056&tolerance=10

**Comment by AFoletti** [comment]
I'll let @alcapat check that in detail, but maybe master is still missing a couple commits?

**Comment by loicgasser** [comment]
please rebase and provide a testlink

**Comment by alcapat** [comment]
Rebase done.
Test link here: https://mf-chsdi3.dev.bgdi.ch/ltalp_geologie-geocover/shorten/77045d404b

**Comment by ltclm** [comment]
@loicgasser why did you merge this? As described above, the ga25 tooltip is not working anymore.

**Comment by AFoletti** [comment]
I think it's unrelated.
The code merged has nothing to do with GA25. Moreover, if you click somewhere else using as base hte same testlink (e.g. here: https://mf-chsdi3.dev.bgdi.ch/ltalp_geologie-geocover/shorten/77063ca505) the tooltip works
I think it's an issue with the shop availability. @alcapat and @pauloamado are on it

**Comment by ltclm** [comment]
@pauloamado @alcapat  
Geologischer Altas tooltip has been fixed with the following query:
```sql
update geol.geocover_basisdatensatz_label SET fk_ga25_tooltip = '146' where bgdi_geocover_nr in( '1191' );
update geol.geocover_basisdatensatz_label SET bgdi_geocover_nr = '146' where bgdi_geocover_nr in( '1211' );
```
ga25 feature tables: ``1191, 146``
geol.geocover_basisdatensatz_label: ``1191, 1211``
``1211`` did not exist in the feature tables, that's why we have to change the id in the label table.

**Pull request merged**
