### PR TITLE
Feature list branches

### PR DESCRIPTION
**Pull request by ltclm**
this will add the lastmodification date to the list of avialable branches with the following make targets:
* make deletebranch
* make deletebranchdev
* make deletebranchint

the output will be formatted like this:
```
$ make deletebranchdev
./scripts/delete_branch.sh dev
No branch name given.
        If you are using through make you need to add a parameter BRANCH_TO_DELETE:
            make deletebranch  BRANCH_TO_DELETE=[branch_name_to_delete]
            make deletebranchdev  BRANCH_TO_DELETE=[branch_name_to_delete]
            make deletebranchint  BRANCH_TO_DELETE=[branch_name_to_delete]
        If you are using the script directly:
            ./scripts/delete_branch.sh [dev|int] [branch_name_to_delete]
Possible values on dev:
bugfix                                                                                               2020-03-05 15:56:14
bugfix_wmts_cache_settings                                                                           2020-03-05 16:07:35
data                                                                                                 2020-12-01 08:39:44
dev_catalog_import                                                                                   2019-09-17 16:20:38
dev_ltclm_fix_chmobil_translations                                                                   2019-11-14 09:41:38
dev_ltclm_fix_search                                                                                 2019-09-26 09:04:17
...                                                                                 
```

### CODE REVIEW

**Review by rebert — CHANGES_REQUESTED** [review]
Good idea displaying the dates!. Buth when I make deletebranchint, I receive:
`
make deletebranchint
./scripts/delete_branch.sh int 
No branch name given.
        If you are using through make you need to add a parameter BRANCH_TO_DELETE:
            make deletebranch  BRANCH_TO_DELETE=[branch_name_to_delete]
            make deletebranchdev  BRANCH_TO_DELETE=[branch_name_to_delete]
            make deletebranchint  BRANCH_TO_DELETE=[branch_name_to_delete]
        If you are using the script directly:
            ./scripts/delete_branch.sh [dev|int] [branch_name_to_delete]
Possible values on ip-10-220-6-131.eu-west-1.compute.internal:
<BRANCH NAME>                                                                                        <LAST MODIFICATION>
bin                                                                                                  2019-11-06 06:50:06
boot                                                                                                 2020-06-25 18:29:17
dev                                                                                                  2020-10-29 11:42:30
etc                                                                                                  2020-10-29 11:42:28
home                                                                                                 2020-10-07 17:42:24
initrd.img                                                                                           2020-06-10 06:35:44
initrd.img.old                                                                                       2020-01-18 06:45:32
lib                                                                                                  2016-09-19 17:09:09
lib64                                                                                                2017-06-20 06:43:56
lost+found                                                                                           2016-09-19 17:06:25
media                                                                                                2016-09-19 17:07:12
mnt                                                                                                  2016-09-19 17:07:12
opt                                                                                                  2020-10-12 14:12:34
proc                                                                                                 2019-10-14 10:42:51
root                                                                                                 2020-06-25 17:42:00
run                                                                                                  2020-10-29 11:42:30
sbin                                                                                                 2020-03-25 06:29:33
srv                                                                                                  2016-11-16 16:36:55
sys                                                                                                  2019-10-14 10:42:53
tmp                                                                                                  2021-04-28 14:39:37
usr                                                                                                  2019-01-29 13:14:52
var                                                                                                  2016-11-16 16:36:55
vmlinuz                                                                                              2020-06-09 21:04:00
vmlinuz.old                                                                                          2020-01-17 22:22:26

`
make deletebranchdev seems to work fine

**Comment by ltclm** [comment]
thanks for testing / feedback @rebert 
should be better now.

**Review by rebert — APPROVED** [review]
Thanks

**Comment by b4l** [comment]
@ltclm will this end up in the next deploy?

**Comment by ltclm** [comment]
@b4l  yes please add it for the next deploy.

**Pull request merged**
