### PR TITLE
swissimage hist metadata and data layer

### PR DESCRIPTION
**Pull request by ltclm**
Testlink (Tod, Tooltips)
https://mf-chsdi3.dev.bgdi.ch/dev_ltclm_swissimage_hist/shorten/794c41b693

- [x] fix 2018 issue https://github.com/geoadmin/mf-geoadmin3/issues/4192

### CODE REVIEW

**Comment by loicgasser** [comment]
Very cool.

**Comment by loicgasser** [comment]
2018 is missing it seems. No data yet?

**Comment by ltclm** [comment]
2018: probably once again we need an ugly hack, but time enabled layers are known for that.
To be honest, i have no idea where 2018 comes from.
2018 appears in the time slider when ch.swisstopo.swissimage-product is activated.
for this layer we have current timestamp (automata) and YYYY timestamps (swissimage hist updates once a year).
For unknown reasons the frontend is adding 2018 to the list of available years, i have tried timeBehaviour ``all, last, current``.

@loicgasser @oterral @gjn any idea how to solve this?
timeBehaviour current:
https://mf-chsdi3.dev.bgdi.ch/ltclm/shorten/794c4060ba
timeBehaviour last:
https://mf-chsdi3.dev.bgdi.ch/dev_ltclm_swissimage_hist/shorten/794c41b693

**Comment by ltclm** [comment]
@loicgasser  @oterral  i have opened an issue for the current-timestamp / timeslider issue
https://github.com/geoadmin/mf-geoadmin3/issues/4192

**Comment by loicgasser** [comment]
Yes thks we have to look into that.

**Comment by ltclm** [comment]
its a mask overlay, it will be used to highlight the perimeter of the data published at the given ``TIME=2016``

**Comment by loicgasser** [comment]
Technically perfect, I wonder how people will understand this is a layer. I would add a border and display the year in the WMS. If I don't understand it, I doubt people will.

**Pull request merged**
