### PR TITLE
add new legends

### PR DESCRIPTION
**Pull request by ltclm**
* ch.bazl.landschaftsruhezonen
* ch.bazl.sachplan-infrastruktur-luftfahrt_kraft
* ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung

ch.bazl.sachplan-infrastruktur-luftfahrt_* legend images had to be postprocessed (RGBA->colormap 8bit) with pngquant:
```bash
$ for file in ch.bazl.sachplan-infrastruktur-luftfahrt_*; do pngquant 256 -f --output $file $file; done
```

### CODE REVIEW

**Comment by ltclm** [comment]
legends are obviously wrong, waiting for new delivery

**Comment by mariokeusen** [comment]
Thx @ltclm : I'll take back the JIRA ticks until further input by data provider

**Comment by mariokeusen** [comment]
Hi @ltclm The new legend PNG's are available now (see jira tickets) and should be handled together with https://github.com/geoadmin/mf-chsdi3/issues/3386

**Comment by ltclm** [comment]
@procrastinatio switchted this back go master. this has to be published before the next data deploy, at the latest before 26.02.2020.
details:
https://jira.swisstopo.ch/browse/BGDIDI_KB-898

**Comment by procrastinatio** [comment]
@ltclm I'll merge this PR and will deploy `master` today. Right?

**Comment by ltclm** [comment]
yes, thank you!

**Pull request merged**
