### PR TITLE
Introduce geoprtal url

### PR DESCRIPTION
**Pull request by b4l**
* ch.swisstopo-vd.amtliche-vermessung
* ch.kantone.cadastralwebmap-farbe

https://mf-chsdi3.dev.bgdi.ch/feature_BGDIDIC-1841/shorten/969081e56a

### CODE REVIEW

**Review by ltclm — APPROVED** [review]
thank you!

**Comment by rebert** [comment]
@b4l I don't know the context. But I realised that you adapted **two models** but only **one mako** (nice - what a simplification on this mako)...

**Review by rebert — COMMENTED** [review]
Changes on 2 models and only on 1 mako ?

**Comment by ltclm** [comment]
> Changes on 2 models and only on 1 mako ?

thats ok, this mako is shared between two layers.

**Pull request merged**
