### PR TITLE
ch.bafu.auen-vegetationskarten

### PR DESCRIPTION
**Pull request by b4l**

### CODE REVIEW

**Comment by ltclm** [comment]
did @rebert show you how to configure sphinx?

https://ltwiki.adr.admin.ch:8443/display/BGDI/03_VIEWER#id-03_VIEWER-Integratethelayerinsphinxsearchservice

https://ltwiki.adr.admin.ch:8443/display/BGDI/25+-+Sphinx+for+mf-chsdi

**Comment by b4l** [comment]
test link: https://mf-chsdi3.dev.bgdi.ch/ltbal_auen/shorten/8a0bf6ca6c

**Comment by ltclm** [comment]
htmlpopup is ok now, thank you.
please change the wmts timestamp of this layer to current in **bod_master.public.tileset**
see https://ltwiki.adr.admin.ch:8443/display/BGDI/05_ToD

> Pre-flight checklist
Before you start, please check the following:
are you supposed to generate Tiles? (update frequency vs. WMS performance)
is the Abnahmeprotokoll accepted and signed?
is the layer fully time-enabled (zeitstand will be  something like YYYYMMDD) or do we work with "current"?
do you need to generate Tiles up to which zoomlevel?

We are setting the timestamp to current to all layers which are not time-enabled.

if you're pr is ready for review, please remove WIP from title and assign it to @rebert or to me.
see https://github.com/geoadmin/doc-guidelines/blob/master/DEVELOPMENT.md#pull-requests-pr

I will take care of the sphinx pr.

Thank you

**Comment by b4l** [comment]
> please change the wmts timestamp of this layer to current in **bod_master.public.tileset**

This is done!

**Pull request merged**
