### PR TITLE
BGDIDIC-2494: add legends

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by ltclm — CHANGES_REQUESTED** [review]
de and fr are mandatory and the translations have to be delivered.

**Comment by faselm** [comment]
But where? all translations were inserted into ms_class (all in German for now even for fr, it, en, rm)

**Comment by ltclm** [comment]
yes that's the point. the data owner has to deliver french tranlsation.

**Comment by faselm** [comment]
Does it has to put it itself into the DB?

**Comment by ltclm** [comment]
> Does it has to put it itself into the DB?

Hi marc, please ask @mariokeusen for the missing translations and update the table ms_class. Thank you!

**Comment by faselm** [comment]
The test is passing now. Does that mean the data provider has put the translation? where can I find it?

**Comment by ltclm** [comment]
the legend translation is provided by dataowner / mario DIF to you. you have to update ms_class and update the legends.
There are no tests on the translation.

**Review by rebert — APPROVED** [review]
thx

**Review by ltclm — APPROVED** [review]
thanks!

**Pull request merged**
