### PR TITLE
Support 3D geometries for esriencoder

### PR DESCRIPTION
**Pull request by procrastinatio**
All test ` ./buildout/bin/nosetests chsdi/tests/integration/test_mapservice.py`pass.

Should fix https://github.com/geoadmin/mf-chsdi3/issues/1769

### CODE REVIEW

**Comment by loicgasser** [comment]
@procrastinatio jenkins still not happy.

**Comment by procrastinatio** [comment]
These errors are totally not related to my code:
* SSL error
* Missing index
* Rollback error

**Comment by procrastinatio** [comment]
jenkins test

**Comment by procrastinatio** [comment]
jenkins test

**Comment by loicgasser** [comment]
Now error comes from the fact that haltstelle layer has been set to prod in bod, but that tze model and legend were not there yet. it has been merged and if your rebase tests should pass.

**Comment by gjn** [comment]
jenkins test

**Pull request merged**
