### PR TITLE
update legends 4 skitouren and schneeschuhrouten

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Comment by oterral** [comment]
PNGs should stay transparent.

**Comment by rebert** [comment]
@oterral I only delivered as ordered...

**Comment by rebert** [comment]
@AFoletti : beside of the transparency nothing changed, shall we keep the old transparent legends?

**Comment by loicgasser** [comment]
Why would you order non transparent png? Sounds odd. We have standards for legends, I would like to keep those.

**Comment by AFoletti** [comment]
Not every customer is aware of the transparency rule (or remembers it). We remind it if we catch the issue but this slipped past.
I'd say to keep the old ones if they are the same, as suggested by @rebert

**Comment by rebert** [comment]
done

**Comment by loicgasser** [comment]
When should it be deployed?

**Comment by AFoletti** [comment]
22.11

**Pull request merged**
