### PR TITLE
Ltfoa gisgeol

### PR DESCRIPTION
**Pull request by AFoletti**

### CODE REVIEW

**Comment by AFoletti** [comment]
[Testlink](http://mf-chsdi3.dev.bgdi.ch/ltfoa_gisgeol/)

**Comment by loicgasser** [comment]
we could reduce the number of lines by around 200 lines if you factorized those models (with the same column each time) a bit.
much easier to maintain and update.

**Comment by gjn** [comment]
@AFoletti Can you take care of it until Tuesday?

**Comment by AFoletti** [comment]
can't promise anything but I'll for sure try

**Comment by AFoletti** [comment]
done factorizing

**Comment by gjn** [comment]
Is the testlink updated with latest version?

**Comment by gjn** [comment]
Would be nice to have direct testlink.

**Comment by AFoletti** [comment]
Sorry, the testlink is now updated.
I deployed a geoadmin branch too in order to better test it
[TestLink](https://mf-chsdi3.dev.bgdi.ch/ltfoa_gisgeol/shorten/6b7cbdce9c)

**Comment by loicgasser** [comment]
@AFoletti I rebased your branch and pushed force.

Can you translate.
"ch.swisstopo.geologie-gisgeol-flaechen-gt21000km2.orig_id"
please

**Comment by loicgasser** [comment]
once the translation has been updated please merge.

**Comment by AFoletti** [comment]
@ltclm I think I'm removing a couple of your translations with my last commit. Could you please check?

**Comment by ltclm** [comment]
yes, that's probably related to the trigger issue.
I have fixed the translations table. Could you please re-translate?
Thank you.

**Comment by AFoletti** [comment]
thanks. All good now. I'll merge

**Pull request merged**
