### PR TITLE
Support lang specific attrs

### PR DESCRIPTION
**Pull request by loicgasser**
This is a fix for:
https://github.com/geoadmin/mf-chsdi3/issues/1219

### CODE REVIEW

**Comment by loicgasser** [comment]
@procrastinatio could you have a look. Comments are in the code so it should be pretty easy to understand.

**Comment by loicgasser** [comment]
With this approach we detect if an attribute name define in `__queryable_attributes__` ends with `_(de|fr|rm|en|it)`

If it is the case, based on the lang parameter of the request, we filter out attributes that don't belong to the request language (with fallbacks for `it`, `en` and `rm`)

**Comment by procrastinatio** [comment]
Otherwise OK for me.

**Comment by loicgasser** [comment]
thanks  @procrastinatio for the review

**Pull request merged**
