### PR TITLE
Make sure the search text is not empty

### PR DESCRIPTION
**Pull request by loicgasser**
More robust validation of searchText, empty strings are not allowed.
Linked to https://github.com/geoadmin/mf-geoadmin3/pull/3351

### CODE REVIEW

**Comment by gjn** [comment]
Jenkins saying that [this test](identifyUrlTemplate) now fails. Obviously, we support bbox only search without any searchText - as described in our doc as well http://api3.geo.admin.ch/services/sdiservices.html#search

**Comment by loicgasser** [comment]
obviously... I will adapt it though.

**Comment by loicgasser** [comment]
I adapted the PR. Nothing will go through if not expected.

**Comment by gjn** [comment]
Fantastic.

**Pull request merged**
