### PR TITLE
Fix turbine number BGDIDIC-1700

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by ltclm — APPROVED** [review]
thank you!
please ask @ltshb how to apply this fix to develop-YYYY-MM-DD branch.

**Comment by ltclm** [comment]
@faselm 
other tests are failing too

**Review by ltclm — CHANGES_REQUESTED** [review]
please fix the other test(s) too.

**Comment by ltshb** [comment]
@faselm @ltclm once the test are passing and this PR has been merged into `master`, simply create a new PR to merge `master` into `develop-2022-05-18`.

**Review by b4l — APPROVED** [review]
Thanks!

**Review by ltclm — APPROVED** [review]

**Pull request merged**
