### PR TITLE
Config new bafu layer for Gewiss

### PR DESCRIPTION
**Pull request by alcapat**

### CODE REVIEW

**Comment by alcapat** [comment]
Link with PR shpinx https://github.com/geoadmin/service-sphinxsearch/pull/217

**Comment by cedricmoullet** [comment]
@procrastinatio please review

**Comment by procrastinatio** [comment]
jenkins test

**Comment by procrastinatio** [comment]
**Legend**

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bafu.hydrologischer-atlas_flussgebiete/legend

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bafu.vec25-seen/legend

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bafu.vec25-gewaessernetz_2000/legend

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bafu.hydrologischer-atlas_bilanzgebiete/legend
Looks OK


http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bafu.hydrologischer-atlas_basisgebiete/legend

**Identify**

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=545000,145000,555000,155000&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=1&layers=all:ch.bafu.hydrologischer-atlas_basisgebiete

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=545000,145000,555000,155000&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=1&layers=all:ch.bafu.hydrologischer-atlas_bilanzgebiete

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=545000,145000,555000,155000&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=1&layers=all:ch.bafu.hydrologischer-atlas_flussgebiete

http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=545000,145000,555000,155000&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=1&layers=all:ch.bafu.vec25-seen


http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=545000,145000,555000,155000&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=1&layers=all:ch.bafu.vec25-gewaessernetz_2000

**Pull request merged**
