### PR TITLE
Wegsperrungen und Umleitungen

### PR DESCRIPTION
**Pull request by rebert**
[try](https://mf-chsdi3.dev.bgdi.ch/ltrea_WESPE/shorten/89c99ed17f)

### CODE REVIEW

**Comment by ltclm** [comment]
@mariokeusen is it really necessary to add a query tool for this layer?
image

i thought we dont do that anymore and publish the attributes in sphinx fulltext search.

**Comment by rebert** [comment]
@ltclm not queriable any more

**Comment by ltclm** [comment]
@rebert could you please resolve the conflicts

**Comment by rebert** [comment]
@ltclm no more conflicts here

**Pull request merged**
