### PR TITLE
Faster deploy (when needed)

### PR DESCRIPTION
**Pull request by gjn**
This PR

- removes the pre-create hook. The hook is always run when creating a snapshot or when directly deploying remotely by hand. It is run against the dev backends and is of no use anymore as we a) have nightly/regular test runs with jenkins and b) we run nosetests before deploying snapshots against target (int/prod) backends.
- adds a `notests` parameter to the deploysnapshot script. This allows to not run the nosetests against target backends. Use it with care (in emergency, when re-running a validated snapshot)

### CODE REVIEW

**Comment by gjn** [comment]
@procrastinatio @loicgasser @oterral Thoughts?

**Comment by cedricmoullet** [comment]
I like it for emergency situation

2015-04-23 9:35 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> @procrastinatio <https://github.com/procrastinatio> @loicgasser
> <https://github.com/loicgasser> @oterral <https://github.com/oterral>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-chsdi3/pull/1394#issuecomment-95477505>.
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by oterral** [comment]
I like it !!!

**Comment by loicgasser** [comment]
+1 It's also nicer when we have to deploy a branch.
Ideally we should think about implementing https://github.com/geoadmin/mf-chsdi3/issues/1339
I know it's possible and it would reduce the time required for testing.

**Comment by gjn** [comment]
Ok. Thanks alot for the reviews.

**Comment by ponceta** [comment]
Fast and Furious deployment :+1:

**Pull request merged**
