### PR TITLE
ch.swisstopo.swissnames3d

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by ltclm** [comment]
jenkins test

**Comment by ltclm** [comment]
jenkins failes:
```
======================================================================
ERROR: test_all_htmlpopups (chsdi.tests.integration.test_mapservice.TestMapServiceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_mapservice.py", line 439, in test_all_htmlpopups
    model = models_from_name(layer)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
can anybody @procrastinatio @gjn @cedricmoullet help?

**Comment by ltclm** [comment]
jenkins test

**Comment by ltclm** [comment]
jenkins test

**Comment by ltclm** [comment]
jenkins test

**Comment by gjn** [comment]
@ltclm Can a data integrator review this?

**Comment by ltclm** [comment]
@alcapat, could you please review this?

**Comment by alcapat** [comment]
@gjn  ready to merge

**Pull request merged**
