### PR TITLE
Add geosjon style for diemo

### PR DESCRIPTION
**Pull request by procrastinatio**
See https://github.com/geoadmin/mf-geoadmin3/pull/4505

Please add symbols where it belongs (data.geo.admin.ch)

### CODE REVIEW

**Comment by procrastinatio** [comment]
@rebert Amazing

**Comment by rebert** [comment]
@AFoletti image has been scaled. If more, you have to get a new version from bfe (or the vector version).
@AFoletti we realised, that the title of this layer has not been translated to the French language yet. Who is taking care of this?

**Comment by AFoletti** [comment]
Thenks @rebert for the legends. Those are OK for the GoLive but I'll still ask the BFE to deliver new ones.
About translations: the geocat entry is OK in FR and the BOD looks good too. Where is the problem exactly?

**Comment by AFoletti** [comment]
Thanks! LG and ready to merge to me

**Pull request merged**
