### PR TITLE
Remove SearchServer type=featureidentify service

### PR DESCRIPTION
**Pull request by gjn**
See https://groups.google.com/forum/#!topic/geoadmin-api/u4a8jV6j0W4

Once this is deployed (not before 25th of March), we can update and merge https://github.com/geoadmin/service-sphinxsearch/pull/186 and remove all those queryable sphinx indices.

### CODE REVIEW

**Comment by gjn** [comment]
test this please

**Comment by gjn** [comment]
jenkins test

**Comment by loicgasser** [comment]
For next deploy I guess then?

**Comment by loicgasser** [comment]
needs rebase.

**Comment by gjn** [comment]
Should have been deployed yesterday. Ahh.

Anyway, rebased. Please review/test to merge ASAP.

**Comment by gjn** [comment]
@loicgasser Can you please review?

**Comment by gjn** [comment]
@procrastinatio @loicgasser Could you please review/merge this?

**Comment by ltclm** [comment]
@loicgasser please review and merge for tomorrows deploy

**Comment by loicgasser** [comment]
Please remove constant FEATURE_GEO_LIMIT

**Comment by loicgasser** [comment]
ok wih me, otherwise.

**Comment by loicgasser** [comment]
jenkins test

**Comment by gjn** [comment]
Thanks for the review.

**Pull request merged**
