### PR TITLE
BGDIDIC-1432: update legends

### PR DESCRIPTION
**Pull request by faselm**
Have the big legends to be in .pdf or .png also work?

### CODE REVIEW

**Review by ltclm — CHANGES_REQUESTED** [review]
i think the legends have to be transparent, but im not sure if that's still the case.
@rebert do you know that?

**Comment by faselm** [comment]
Hi, does it need to be transparent then?

**Comment by faselm** [comment]
Hi, can I merge this pr or do I have to ask the data provider to send transparent legends?

**Review by ltclm — APPROVED** [review]
yes @faselm we already have plenty of non-transparent legends.
this seems to be no longer a requirement.

**Pull request merged**
