### PR TITLE
BGDIINF_SB-2486: Moved the new config style url rewrite inside python - #3

### PR DESCRIPTION
**Pull request by ltshb**
For this support I had to move the `add_localizer()` hook from `NewRequest` to
`ContextFound` event. In the first one no routing is done and we cannot take
the `lang` parameter from the path for the new config style urls, while in the
ContextFound the routing has already be done and the `lang` url parameter has
already been parsed.

### CODE REVIEW

**Comment by ltshb** [comment]
@pakb @boecklic I'm don't know why those new config style url have been in the past added, but looking at the access logs they are not all used. @pakb could you check in the old viewer and new viewer to see which ones are effectively used by the viewers ?
1. `/configs/(de|fr|it|rm|en)/layersConfig.json`
2. `/configs/(de|fr|it|rm|en)/translations.json`
3. `/configs/(de|fr|it|rm|en)/catalog.<MAP>.json`
4. `/configs/(de|fr|it|rm|en)/services.json` (from my understanding this one is not used and could be removed ?)
5. `/configs/services.json`

**Review by procrastinatio — APPROVED** [review]
OK.

**Comment by pakb** [comment]
1. `/configs/(de|fr|it|rm|en)/layersConfig.json`
Doesn't seem to be used by either project

2. `/configs/(de|fr|it|rm|en)/translations.json`
Doesn't seem to be used by either project

3. `/configs/(de|fr|it|rm|en)/catalog.<MAP>.json`
Used only in tests, so maybe it's safe to remove... The main call (when creating the static files) is made through the standard enpoint (https://github.com/geoadmin/mf-geoadmin3/blob/da76d114559986fe2640684326907734178da72c/mk/serviceconfig.mk#L19-L28)
Potential usage:
https://github.com/geoadmin/mf-geoadmin3/blob/490a0f0e7d92768b3581cccf88b16b1b0164a505/test/specs/js/CatalogtreeController.spec.js#L41

4. `/configs/(de|fr|it|rm|en)/services.json`
https://github.com/geoadmin/mf-geoadmin3/blob/da76d114559986fe2640684326907734178da72c/mk/serviceconfig.mk#L19-L28
https://github.com/geoadmin/mf-geoadmin3/blob/e05e96ae7197e6d181478a7ba2a67ba64e66e39a/src/js/GaModule.js#L183-L191

5. `/configs/services.json`
It looks like it is also made static somehow in the Makefile, and is stored on the S3 bucket

**Comment by ltshb** [comment]
As discussed with @boecklic because we cannot get totally rid of Apache due to performance see #4022 we keep those URL rewrite in Apache config because it simpler to have them here as in the code.

**Pull request closed without merging**
