### PR TITLE
Use assertion in non-TestCase unit tests

### PR DESCRIPTION
**Pull request by gjn**
failUnless does not exist on this class because it's not based on TestCase. We don't want to base this class on TestCase because we want to use generators. So we need assert instead.

This PR also uses the new puppet managed http_proxy.

@procrastinatio Please review.

### CODE REVIEW

**Comment by gjn** [comment]
The `test_wmtsgettile.py` tests run up the memory until the end of the tests, consuming **more than 4GB** of RAM at the end. I think that's bad. I tried to mitigate this by using the yield in the get_tiles function, but that didn't help.

@procrastinatio Do you have an idea on how we could limit memory consumption during those tests?

**Comment by loicgasser** [comment]
LGTM.
MapProxy is probably the one to blame and which can explain the RAM consumption. We're performing more than 1'000 requests on MapProxy in a very short time window...

**Comment by loicgasser** [comment]
From doc:
http://www.python-requests.org/en/latest/user/advanced/#keep-alive

**Comment by gjn** [comment]
I was able to find a solution. Memory consumption is low now, it's faster and in addition tests can now be called the same way as all other tests (they will be found by nose without specifiying path/testname).

@loicgasser Please review.

**Comment by loicgasser** [comment]
Thanks a lot!

**Pull request merged**
