### PR TITLE
Using new param layerDefs for filtering features in identifiy

### PR DESCRIPTION
**Pull request by procrastinatio**
See https://github.com/geoadmin/mf-chsdi3/issues/3104

This PR is trying to mimick ESRI REST API [Identify (Map Service)](https://developers.arcgis.com/rest/services-reference/identify-map-service-.htm)

[Demo](https://mf-chsdi3.dev.bgdi.ch/mom_extend_find) and [doc](http://mf-chsdi3.dev.bgdi.ch/mom_extend_find/services/sdiservices.html#identify-features)

Using `lark` to parse SQL chunks (see https://github.com/geoadmin/mf-chsdi3/blob/mom_extend_find/chsdi/lib/parser.py#L6-L36)

TODO

* [ ] Load tests
* [x] Functional/integration tests
* [x] Documentation
* [ ] Documentation for the mere mortals
* [ ] Decide if it's worse the risiko
* [x] Check if attribute exists in the DB (will break stuff, until now even non queryable attributes were filterable with `where`)
* [ ] Check if query match DB type
* [ ] Valid with a real ESRI API (because this is what you want)

### CODE REVIEW

**Comment by stflustop** [comment]
many thanks for the implementation in indentify. For the described usecase I also need an implementation in find. See comment and example in base ticket

**Comment by stflustop** [comment]
possible usecase. You want to search for a street which lies in a certain postcode.
MapServer/find?searchText=Talstrasse&contains=false&searchFields=LABEL&layers=0&returnGeometry=false&layerDefs=0%3APLZO+like+%277250%25%27&f=pjson

**Comment by procrastinatio** [comment]
Some `bodID` have many models (e.g. `Hebungsraten`), how do we know on which model to filter?

**Comment by procrastinatio** [comment]
Anybody?

**Comment by procrastinatio** [comment]
@boecklic For tables with not many features (<10'000), indices are no advantage.
Only `queryable` attributes  (e.g. http://api3.geo.admin.ch/rest/services/api/MapServer/ch.swisstopo.geologie-gisgeol-punkte) of `queryable` layers (layers with an attribute `queryableAttributes` in the `layersConfig.json`) are queryable, but all attributes are `filterable`. 
However, since its inception 5 years ago, the `where` service is in beta.

Note: `query` and `queryable` is `find`+ filter (`where` or `layerDefs`). Not to be confused with `search` and `searchable` (sphinx search) and `find`, or even `identify` (spatial search).

**Comment by rebert** [comment]
Why do you have to put +=+ ?
This works:
http://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=2548945.5,1147956,2549402,1148103.5&geometryFormat=geojson&imageDisplay=1367,949,96&lang=en&layers=all:ch.bav.haltestellen-oev&mapExtent=2318250,952750,3001750,1427250&returnGeometry=false&sr=2056&tolerance=5000&layerDefs={%22ch.bav.haltestellen-oev%22:%22id+=+8500667%22}

This not:
http://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=2548945.5,1147956,2549402,1148103.5&geometryFormat=geojson&imageDisplay=1367,949,96&lang=en&layers=all:ch.bav.haltestellen-oev&mapExtent=2318250,952750,3001750,1427250&returnGeometry=false&sr=2056&tolerance=5000&layerDefs={%22ch.bav.haltestellen-oev%22:%22id=8500667%22}

**Comment by AFoletti** [comment]
@stflustop could you please attentively test this development? I was kindly asked (😉) to use that instead of "WHERE" for DIEMO and we need to have it working.
@rebert already found a strange implementation of "=" (see comment above)

**Comment by AFoletti** [comment]
So, I am about to send the new functionality to the BFE to test (like [this one](http://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometryType=esriGeometryEnvelope&geometry=2548945.5,1147956,2549402,1148103.5&geometryFormat=geojson&imageDisplay=1367,949,96&lang=en&layers=all:ch.bav.haltestellen-oev&mapExtent=2318250,952750,3001750,1427250&returnGeometry=false&sr=2056&tolerance=5000&layerDefs={"ch.bfe.ladestellen-elektromobilitaet":"OperatorID%20=%20CHEVP"}) )

...and I get this result.

```json
{
  "status": "error",
  "code": 400,
  "detail": "You can only filter on layer '[u'ch.bav.haltestellen-oev']' in 'layerDefs'"
}
```

Is there any reason why this is restricted? It was my understanding that this should replace WHERE sooner or later...
ping @procrastinatio @gjn @danduk82

**Comment by AFoletti** [comment]
> @procrastinatio @boecklic
> Why do you have to put +=+ ?

Actually, it looks like it's very sensible to whitespaces (and their absence). You can put a space instead of "+" and it works

**Comment by stflustop** [comment]
Try to do thalstrasse in PLZO=7250 Klosters
&layerDefs=%7B%22ch.swisstopo.amtliches-strassenverzeichnis%22%3A%20%22plzo%20%3D%208302%20Kloten%22%7D
and
&layerDefs=%7B%22ch.swisstopo.amtliches-strassenverzeichnis%22%3A%20%22plzo%20%3D%208302+Kloten%22%7D
did not work

**Comment by stflustop** [comment]
To build the query we need the following operators
= equal
<> not equal
> greater than
< less than
>= greater than or equal
<= less than or equal
like
in ({value1],[value2],...)

**Comment by stflustop** [comment]
It should be possible to combine expressions by AND and OR.
Nested queries or subqueries are not yet needed

**Comment by rebert** [comment]
@stflustop I reopend the pull request and mention, that it has not been approved yet!

**Comment by rebert** [comment]
@stflustop as far as I understood the doc https://developers.arcgis.com/rest/services-reference/identify-map-service-.htm OR is not possible

**Comment by rebert** [comment]
Hi here my 5 cents:

### General for testing: Get the queriable attributes of a layer?
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/ch.swisstopo.amtliches-strassenverzeichnis

**The streetnames of gemnr 2701**
*Find*
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/find?layer=ch.swisstopo.amtliches-strassenverzeichnis&searchField=gdenr&searchText=2701&returnGeometry=false&contains=false&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"gdenr%20=%202701"}

_Remark_
- Shouldn't it be possible to query layerDefs without the keys searchField, searchText -> right now the layerDefs is the OR...
- It is not very handy that the "relational operator" has to be emeded in space " = " 

**Identify**
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=fr&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"gdenr%20=%202701"}


### The streetnames of (gemnr >= 2701 AND gemnr <= 2710)

**Find**
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/find?layer=ch.swisstopo.amtliches-strassenverzeichnis&searchField=type&searchText=Strasse&returnGeometry=false&contains=false&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"gdenr%20>=%202701","ch.swisstopo.amtliches-strassenverzeichnis":"gdenr%20%3C=%202710"}

_Remark_
- query was possible with hack: searchField =  type, searchText "Strasse"

**Identify**
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=fr&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"gdenr%20>=%202701","ch.swisstopo.amtliches-strassenverzeichnis":"gdenr%20%3C=%202710"}


### label Hauptstrasse plzo AND ilike %Basel

**Does not work:**
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=de&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"plzo%20ilike%20'%Basel%'","ch.swisstopo.amtliches-strassenverzeichnis":"label%20ilike%20'%Hauptstrasse%'"}

**Works:**
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=de&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"label%20ilike%20'%Hauptstrasse%'"}

**Does not work**
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=de&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"label%20ilike%20'%Hauptstrasse%'"}

https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=de&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis":"gdename%20ilike%20'%Basel%'"}

**Comment by AFoletti** [comment]
MartinH tested it too. Here his feedback in short:

- overall clunky to use (why spaces??)
- doc is not sufficient. We need to state which operators are available and how do they work
- open question: does 'ilike not' work?

As info: we posted a little how-to here: https://github.com/SFOE/DIEMO-Documentation/blob/master/README.md

**Comment by procrastinatio** [comment]
Avaliable attributes, types and values for `ch.swisstopo.amtliches-strassenverzeichnis`

http://api3.geo.admin.ch/rest/services/api/MapServer/ch.swisstopo.amtliches-strassenverzeichnis

The attribute `plzo` is of type varchar, so value have to be between single quote.

This is wrong
```
&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis": "plzo = 8302 Kloten"}
```
This is correct:
```
https://mf-chsdi3.dev.bgdi.ch/mom_extend_find/rest/services/all/MapServer/identify?geometry=2577070,1184860&mapExtent=0,0,100,100&imageDisplay=100,100,100&geometryFormat=geojson&geometryType=esriGeometryPoint&lang=de&layers=all:ch.swisstopo.amtliches-strassenverzeichnis&returnGeometry=true&tolerance=500000&sr=2056&layerDefs={"ch.swisstopo.amtliches-strassenverzeichnis": "plzo = '8302 Kloten'"}

```

**Comment by procrastinatio** [comment]
Superseeded by https://github.com/geoadmin/mf-chsdi3/pull/3244

**Pull request closed without merging**
