### PR TITLE
switched the pdf linked in the tooltip

### PR DESCRIPTION
**Pull request by AFoletti**
This PR simply changes the attribute used for pdf linking

### CODE REVIEW

**Comment by loicgasser** [comment]
```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/templates/htmlpopup/base.mako", line 57, in render_body
    ${self.table_body(c, lang)}
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/templates/htmlpopup/projflughafenanlagen.mako", line 18, in render_table_body
    %if c['attributes']['weblink_ref']:
KeyError: 'weblink_ref'

-------------------- >> begin captured logging << --------------------
chsdi: DEBUG: route matched for url http://localhost/rest/services/all/MapServer/ch.bazl.projektierungszonen-flughafenanlagen/11/htmlPopup?callback=cb_&lang=de; route_name: 'htmlPopup', path_info: u'/rest/services/all/MapServer/ch.bazl.projektierungszonen-flughafenanlagen/11/htmlPopup', pattern: '/rest/services/{map}/MapServer/{layerId}/{featureId}/htmlPopup', matchdict: {'featureId': u'11', 'map': u'all', 'layerId': u'ch.bazl.projektierungszonen-flughafenanlagen'}, predicates: ''
chsdi: DEBUG: debug_authorization of url http://localhost/rest/services/all/MapServer/ch.bazl.projektierungszonen-flughafenanlagen/11/htmlPopup?callback=cb_&lang=de (view name u'' against context <pyramid.traversal.DefaultRootFactory instance at 0x2d6fecf8>): Allowed (no authorization policy in use)
--------------------- >> end captured logging << ---------------------
```

Please have a look at Jenkins when it fails

**Comment by loicgasser** [comment]
apparently you still try to access `weblink_ref` somewhere else.

**Comment by AFoletti** [comment]
updated :smile: 
Jenkins does not answer immediately, so I tend to have a look after a few hours

**Comment by loicgasser** [comment]
Yes makes sense. Thanks !

**Pull request merged**
