### PR TITLE
Feat bgdidic 2472 drohnen

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Comment by faselm** [comment]
Should anything related to ch.bazl.gebietsbeschraenkungen-drohnen be deleted ?

**Comment by faselm** [comment]
Does that means that both layers will point o the einschraenkungen_drohnen table?

**Comment by faselm** [comment]
Hi @rebert What do you mean by the (other) new table? einschraenkungen_drohnen or gebietsbeschraenkungen_drohnen? The tests fail when I replace einschraenkungen_drohnen by gebietsbeschraenkungen_drohnen.

**Comment by faselm** [comment]
OK, but the github tests are not passing when I try to use the gebietsbeschraenkungen_drohnen table with the model for einschraenkungen drohnen...

**Comment by faselm** [comment]
Hopefully, the names for this one should be fixed

**Review by rebert — APPROVED** [review]
lgtm

**Pull request merged**
