### PR TITLE
BGDIINF_SB-2169: remove cut service

### PR DESCRIPTION
**Pull request by ltclm**
since the shop is not using this service anymore we can safely remove this from mf-chsdi3.

the following views / tables can be removed from stopo_master once this pr is merged :

```sql
begin;
DROP VIEW shop_perimeter_pk25 CASCADE;
DROP VIEW shop_perimeter_pk50 CASCADE;
DROP VIEW shop_perimeter_pk100 CASCADE;
DROP VIEW shop_perimeter_pk200 CASCADE;
DROP VIEW shop_perimeter_pk500 CASCADE;
DROP VIEW shop_perimeter_swissimage CASCADE;
rollback;
```

reverts: https://github.com/geoadmin/mf-chsdi3/pull/2083

### CODE REVIEW

**Review by boecklic — APPROVED** [review]
:+1: can this be deployed right now or do we need to wait for the next data deploy?

**Comment by ltclm** [comment]
> 👍 can this be deployed right now or do we need to wait for the next data deploy?

@boecklic theoretically yes, but I suggest doing it with the next data deploy. it is not an urgent clean-up. The service has not been used for almost a year anymore.

**Review by procrastinatio — APPROVED** [review]
Looks OK, but you forget to remove the doc :smirk:

**Comment by procrastinatio** [comment]
To test the procedure, we may deploy. But no hurry anyway

**Pull request merged**
