### PR TITLE
Add relnotes 20210908

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by rebert — COMMENTED** [review]
ltgm

**Comment by mariokeusen** [comment]
Looks good to me apart from the ch.bafu.gewaesserschutz-badewasserqualitaet - update, which is missing on the Releasenote. @faselm could you please add that?

**Comment by faselm** [comment]
@mariokeusen Salut Mario, the layer is already in the doc in fact (after ch.bfe.energieforschung)...

**Comment by mariokeusen** [comment]
> @mariokeusen Salut Mario, the layer is already in the doc in fact (after ch.bfe.energieforschung)...

Ah, didn't realize it's not the same order than in the remember doc ;-)

**Pull request merged**
