### PR TITLE
switched from jpeg to jpg for energieforshung pics

### PR DESCRIPTION
**Pull request by AFoletti**
BFE is switching their pictures from jpeg to jpg for the energieforschung layer.
Migration is in progress, and this PR must NOT be merged until GO is received from BFE

### CODE REVIEW

**Comment by AFoletti** [comment]
Confirmed by BFE: this is needed for tomorrow's deploy. Could a dev please merge?

**Comment by gjn** [comment]
How to test?

Do they have both formats available?

**Comment by gjn** [comment]
When I try http://www.bfe-gis.admin.ch/bilder/ch.bfe.energieforschung/b500771-1.jpg, it's not there, but http://www.bfe-gis.admin.ch/bilder/ch.bfe.energieforschung/b500771-1.jpeg is there...

Are they ready?

**Comment by AFoletti** [comment]
they will complete the switch this afternoon

**Pull request merged**
