### PR TITLE
Assure that files service works with IE9

### PR DESCRIPTION
**Pull request by gjn**
IE9 does not send any content-type header. There's no way to change that. This means that storing kml files coming from IE9 simply doesnt work.

This PR changes the files service so it will accept requests coming from IE9 without checking the content-type header.

### CODE REVIEW

**Comment by gjn** [comment]
Nosetests fail. I'm on it.

**Comment by gjn** [comment]
Should be good now.

**Comment by loicgasser** [comment]
you rule

**Comment by gjn** [comment]
:)
IE9 rules. Another 2.5 hours taken from my working time.

**Comment by procrastinatio** [comment]
OK, I have a look. If good, merging and redeplyoing...

**Pull request merged**
