### PR TITLE
BGDIDIC-965: update legends

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by rebert — CHANGES_REQUESTED** [review]
Thanks. Here some feedback about legends
- the max width of legend images is 480px
- when rm the _big.pdf you have to rm it from the config as well in chsdi/templates/legend.mako

**Comment by faselm** [comment]
>     * when rm the _big.pdf you have to rm it from the config as well in chsdi/templates/legend.mako

Hi, I don't understand this sentence. It's just an update of the existing legends

**Comment by rebert** [comment]
Hej @faselm 

- The width of the images lgtm now.

- About the pdf: I mean that when you remove the 
`chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_de_big.pdf` you have to rm it from the template as well: https://github.com/geoadmin/mf-chsdi3/blob/develop-2023-03-15/chsdi/templates/legend.mako#L16 (if not clear, don't hesitate to give me a call)

BR
Tobias

**Comment by faselm** [comment]
Hi @rebert, OK but it's an update, I don't remove chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_de_big.pdf or any other legends...

**Review by rebert — APPROVED** [review]
@faselm sorry - my bad. it lgtm

**Comment by faselm** [comment]
@rebert OK, thanks

**Pull request merged**
