### PR TITLE
use dedicated database for solarkataster layer

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by ltclm** [comment]
to be deployed together with https://github.com/geoadmin/wms-bgdi/pull/106

**Comment by loicgasser** [comment]
Silent deploy for Monday.

1. Deploy new DB to int, prod
2. Deploy CHSDI to int, prod
3. Deploy WMS to int, prod
4. Remove old tables from uvek
5. Redeploy uvek to int, prod (optional)

@gjn Do we have automatic updates on this layer.

**Comment by AFoletti** [comment]
no, there is no auto update on this one :)

**Comment by gjn** [comment]
But certainly FME scripts to adapt, no?
Am 28.10.2016 9:12 nachm. schrieb Ambrogio Foletti <notifications@github.com>:no, there is no auto update on this one :)

**Comment by ltclm** [comment]
yes, we will update the import scripts during the next update.
The tables in the old database will be removed after next weeks deploy.

**Pull request merged**
