### PR TITLE
Ltfoa teileinzugsgebiete

### PR DESCRIPTION
**Pull request by AFoletti**

### CODE REVIEW

**Comment by AFoletti** [comment]
ToDo:
correct such errors:
https://mf-chsdi3.dev.bgdi.ch/ltfoa/rest/services/ech/MapServer/ch.bafu.wasser-teileinzugsgebiete_2/13698/extendedHtmlPopup?lang=it

**Comment by AFoletti** [comment]
bug from previous comment is fixed

**Comment by AFoletti** [comment]
this PR is ready to be merged once reviewed and accepted

**Comment by alcapat** [comment]
LGTM
Remark :
A traduction is not right (a request to the datenherr will be sent)
One attribute is not set right (set in varchar on db but must be an integer).

**Pull request merged**
