### PR TITLE
ready to merge for next deploy: update bfe web-dav url

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by gjn** [comment]
@daguer for tomorrow?

**Comment by cedricmoullet** [comment]
@daguer Is https an option ? Or could we use the proxy ?

**Comment by daguer** [comment]
@gjn  Yes, it's for today...
@cedricmoullet We can use the proxy, I adapt my PR

**Comment by gjn** [comment]
Not a fan of proxy. If it works that way, we should let it as it is.

**Comment by cedricmoullet** [comment]
I would reconsider the useage of the proxy. Of course, the problem should be solved at the source. But in this case, our application is considered unsecure...

**Pull request merged**
