### PR TITLE
Add new layer ch.bfe.wpsm-qualifizierte_firmen

### PR DESCRIPTION
**Pull request by Sgachet**
[Test link](https://mf-chsdi3.dev.bgdi.ch/gas_wpsm/shorten/7a8a4d64f0)

### CODE REVIEW

**Comment by Sgachet** [comment]
For the moment it's only "test data" but you can already review and then we can merge this PR

**Comment by ltclm** [comment]
is this for next weeks deploy?

**Comment by Sgachet** [comment]
Nope, only [this](https://github.com/geoadmin/mf-chsdi3/pull/2977) is for next weeks

**Comment by ltclm** [comment]
@Sgachet is this ready for review?

**Comment by Sgachet** [comment]
@ltclm I think yes, but for pay attention that for the moment there is just test data

**Pull request merged**
