### PR TITLE
[WIP] rapidmapping vector layer

### PR DESCRIPTION
**Pull request by ltclm**
visualize the rapidmapping events in map.geo.admin.ch
spec: https://jira.swisstopo.ch/browse/BGDIINF_SB-862?jql=text%20~%20%22rapidmapping%20vector%22

### CODE REVIEW

**Comment by AFoletti** [comment]
@ltclm I made some tooltip changes. See [here](https://mf-chsdi3.dev.bgdi.ch/ltfoa/shorten/855239de28) for a testlink.
What do you think?

**Comment by procrastinatio** [comment]
Rebased...

**Comment by ltclm** [comment]
@AFoletti do you want to publish this next week?

**Comment by AFoletti** [comment]
@ltclm no... we are absolutely not ready

**Comment by ltclm** [comment]
no one seems to want this here anymore.

**Pull request closed without merging**
