### PR TITLE
Update ch.bfe.energiestaedte-energieregionen

### PR DESCRIPTION
**Pull request by b4l**
test link: https://mf-chsdi3.dev.bgdi.ch/ltbal_energieregionen/shorten/8a5e8b2fbb

### CODE REVIEW

**Comment by b4l** [comment]
Reviewed by customer & requested to put to production by @mariokeusen

**Comment by b4l** [comment]
@ltclm what about the CI errors?

**Comment by ltclm** [comment]
@b4l the access to the ci / aws gui is not yet ready but planned to be done soon.
Until then we cannot use the CI output. I propose to run the tests locally:
```
make test
```

This should give you an idea about the situation.

**Comment by ltclm** [comment]
@mariokeusen how urgent is this? Do we have to publish this before the next deploy?

**Comment by ltclm** [comment]
@rebert in the meantime i have checked the codebuild tests in aws console, tests are passing.

**Pull request merged**
