### PR TITLE
Legends for ch.bag.zeckenstichmodell

### PR DESCRIPTION
**Pull request by Sgachet**
[Test link](https://mf-chsdi3.int.bgdi.ch/gas_zeckenstichmodell/shorten/7d1c77700b)

New raster layer ch.bag.zeckenstichmodell. No tooltip, no model

### CODE REVIEW

**Comment by danduk82** [comment]
ping @Sgachet what is the status?

**Comment by AFoletti** [comment]
We just received green light for continuing with the layer. Planned deploy on 27.02

**Comment by AFoletti** [comment]
This layer is OK for deploy next week.
The PR looks good to be merged to me

**Comment by ltclm** [comment]
lgtm, thank you!

**Pull request merged**
