### PR TITLE
Honor scale dependent htmlpopups and split validation files

### PR DESCRIPTION
**Pull request by loicgasser**
@alcapat Please test
@gjn Please review

Small refactoring as well, more to come later.

[Test Link](http://mf-chsdi3.dev.bgdi.ch/gal_honor_scale/dev)

### CODE REVIEW

**Comment by loicgasser** [comment]
Jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by alcapat** [comment]
Test in geoadmin (ltalp) connect to api gal_honor_scale, work's fine.
[https://mf-geoadmin3.dev.bgdi.ch/ltalp/src/?layers=ch.bafu.schutzgebiete-aulav_uebrige,ch.bafu.schutzgebiete-aulav_jagdbanngebiete&topic=aviation&lang=fr&catalogNodes=1379,1381,1514&bgLayer=ch.swisstopo.pixelkarte-grau&layers_opacity=0.75,0.75&X=138594.66&Y=572849.93&zoom=7]

Thanks loïc

**Comment by gjn** [comment]
Is https://github.com/geoadmin/mf-chsdi3/pull/2016/commits/c038767e4b6d9e4a9a1b0be348ddfd0ebb132b60 the fix?

**Comment by loicgasser** [comment]
yes you'll need e8140481e896a5b45a83781aac2ad276d99d99a5 as well

**Comment by loicgasser** [comment]
@alcapat thanks, could we use unique ids accross the 2 tables as they describe different objects so that API users won't have this problem?

**Comment by ltclm** [comment]
yes that's possible, define a global counter in the fme workbench, you can ask @daguer for an example.

**Comment by gjn** [comment]
@loicgasser I'm afraid, this needs a rebase.

Also, would like to have a full testlink with integration in mf-geoadmin3. It imapacts tooltip/extended tooltip interaction.

**Comment by loicgasser** [comment]
Fixes https://github.com/geoadmin/mf-chsdi3/issues/1276 I rebase now no probs

**Comment by loicgasser** [comment]
rebased
[Test Link CHSDI](http://mf-chsdi3.dev.bgdi.ch/gal_honor_scale/dev)
[Test Link Geoadmin](http://mf-geoadmin3.dev.bgdi.ch/gal_honor_scale/)

**Comment by gjn** [comment]
Thanks alot for the effort!

Will review in detail when finishing reviewing the grid PR.

**Comment by gjn** [comment]
@rfrancel @mariavkourouni @alcapat We need your testing efforts. Please use [this link] for your tests. Focus on the following:

- Tooltip interaction (does the correct tooltip show up - depending on zoom levels)
- Extendet tooltips (are they correct)
- Query tool (for luftfahrthindernisse, with custom filters)
- Zeitreihen print (corret numer of years printed?)

No need to test in multiple browsers. 1 is enough.

Please test at minimum these layers:

ch.kantone.cadastralwebmap-farbe
ch.bafu.schutzgebiete-aulav_jagdbanngebiete
ch.bafu.schutzgebiete-aulav_moorlandschaften
ch.bafu.schutzgebiete-aulav_uebrige
ch.bfs.gebaeude_wohnungs_register
ch.swisstopo.swissnames3d
ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung
ch.bfe.sachplan-uebertragungsleitungen_kraft
ch.bav.haltestellen-oev
ch.swisstopo.zeitreihen

Thanks in advance for your efforts.

**Comment by mariavkourouni** [comment]
I tested the above and all seem to work as expected.

**Comment by gjn** [comment]
Thanks everybody for the tests. I'll merge.

**Pull request merged**
