### PR TITLE
Update ch.bafu.wasserbau-querprofilmarken

### PR DESCRIPTION
**Pull request by faselm**
Test link: https://mf-chsdi3.dev.bgdi.ch/ltfas_wasserbau/shorten/8e0de419d1

### CODE REVIEW

**Review by b4l — COMMENTED** [review]
Many tooltip attribute names and legend classes start with lower case, does the customer wants it like this?

**Comment by faselm** [comment]
@b4l Yes, I think so. It's how they wrote it in the table they sent with all the names and translations...

**Review by ltclm — APPROVED** [review]
lgtm thank you!
I have just restarted the test but the issue seems to be not related to this pr.

**Comment by ltclm** [comment]
@faselm can you please rebase on the latest data branch?

**Comment by faselm** [comment]
@ltclm Branch rebased, the tests look good

**Pull request merged**
