### PR TITLE
fix 4 canton Schwyz and canton BL

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Comment by rebert** [comment]
@p1d1d1  [4 testing](https://mf-chsdi3.dev.bgdi.ch/fix_oereb_service_for_canton_5/shorten/817a17e96a)

**Comment by p1d1d1** [comment]
> 
> 
@rebert 

> @p1d1d1 [4 testing](https://mf-chsdi3.dev.bgdi.ch/fix_oereb_service_for_canton_5/shorten/817a17e96a)

I did test all cantons this time. It seems to be all ok. I'll ask data owner to test also

**Comment by p1d1d1** [comment]
@rebert got OK from data owner

**Comment by p1d1d1** [comment]
@rebert  this has been fixed but please have a look at: https://github.com/geoadmin/mf-chsdi3/issues/3175

**Pull request merged**
