### PR TITLE
BGDIDIC-1953: Update ch.bafu.wasserbau-vermessungsstrecken

### PR DESCRIPTION
**Pull request by b4l**
Test link: https://mf-chsdi3.dev.bgdi.ch/feature_BGDIDIC-1953/shorten/8e08185818

Mapfile: https://github.com/geoadmin/wms-mapfile_include/pull/598

Script: https://github.com/geoadmin/bgdi-scripts/pull/792

### CODE REVIEW

**Comment by faselm** [comment]
@b4l Map, tooltip, legends look good!

**Review by ltclm — CHANGES_REQUESTED** [review]
as @mariokeusen already noticed, the urls are wrong.
they are read from the attribute: uebersicht_messkampagne_link in the model.
These are not valid urls:
```
https:/data.geo.admin.ch/ch.bafu.wasser-vermessungsstrecken/objectsheets/Querprofilaufnahmen_Rhein_Basel_Bodensee_Hochrhein.pdf

instead of

https://data.geo.admin.ch/ch.bafu.wasser-vermessungsstrecken/objectsheets/Querprofilaufnahmen_Rhein_Basel_Bodensee_Hochrhein.pdf
```

Please fix these urls in the fme integration script or in the datasource. The Links should be fixed afterwards.

What will happen to the old table: `` wasser.vermessungsstrecken``?

**Comment by ltclm** [comment]
@b4l  to fix the tests, please rebase your branch to the latest data branch.

**Comment by b4l** [comment]
The invalid urls are now fixed in the script commit: https://github.com/geoadmin/bgdi-scripts/pull/792/commits/706d02f3a51edf8f7fc3b57b5d9bfc69b222eb16
The old table and the sphinx index can get removed after the deploy, i will add this to the remember doc.
I rebased and redeployed the branch, once the deploy date is fixed i will update this and the related pull requests.

**Review by ltclm — APPROVED** [review]
thank you!
lgtm now.

**Pull request merged**
