### PR TITLE
Update ol to v3.4.0

### PR DESCRIPTION
**Pull request by oterral**

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@oterral is it for today's deploy ?

**Comment by oterral** [comment]
yes @cedricmoullet

**Comment by oterral** [comment]
I've tested right now

**Comment by ponceta** [comment]
@oterral shouldn't https://github.com/geoadmin/ol3/pull/125 be merged before?

**Comment by oterral** [comment]
yes

**Pull request merged**
