### PR TITLE
added date format d.m.Y

### PR DESCRIPTION
**Pull request by cype**

### CODE REVIEW

**Comment by AFoletti** [comment]
Nothing against it. More so if I'm right about the source of this PR  ;)
But since the source is external to the team I'll let a developer merge it

**Comment by cype** [comment]
:+1: Thanks Ambrogio & Cedric. More PRs to come from my side!

**Comment by cedricmoullet** [comment]
@AFoletti please test the PR when you review it. This one generated issues so that I had to revert it.

**Comment by cype** [comment]
Ups sorry, that's my fault. Since I don't have a development environment, I'm not able to test my code. Therefore you should be careful with my PR.

**Comment by AFoletti** [comment]
I just checked the data and the problem is that the "end" attribute may contain null values.
@cype : I'll use your code and implement a not-null check, then post a new PR

**Comment by cype** [comment]
Thanks Ambrogio!

**Pull request merged**
