### PR TITLE
Include pkey in getAttributes when needed

### PR DESCRIPTION
**Pull request by loicgasser**
Would be nice to have it for tomorrow.

Some layers define pkeys as queryable attributes, this was not taken into account so far.

### CODE REVIEW

**Comment by procrastinatio** [comment]
OK, but maybe the name `excludePkey` is too restrictive.

**Comment by loicgasser** [comment]
What do you suggest then?

**Comment by loicgasser** [comment]
@gjn adapted to comments

**Comment by gjn** [comment]
I still don't understand why you introduce a parameter that is always set to the same value (`False`) when the function is called...

**Comment by loicgasser** [comment]
Per default we exclude the primary key from the attributes unless specified diffrently.

**Comment by loicgasser** [comment]
You can read http://www.diveintopython.net/power_of_introspection/optional_arguments.html

**Comment by gjn** [comment]
My fault. I didn't see https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/__init__.py#L120

**Comment by loicgasser** [comment]
@procrastinatio @gjn Good to you guys? Can I merge?

**Comment by gjn** [comment]
Good for me.

**Pull request merged**
