### PR TITLE
Add ch.meteoschweiz.klimanormwerte-niederschlag_*

### PR DESCRIPTION
**Pull request by b4l**
Test link: https://mf-chsdi3.dev.bgdi.ch/ltbal_niederschlag/shorten/8c53574b0a

### CODE REVIEW

**Comment by faselm** [comment]
@b4l Sorry but I don't see the data... Legends are OK

**Comment by marionb** [comment]
Same for me. I am getting some 503 for the image requests.

**Comment by b4l** [comment]
@marionb & @faselm it should work now.

**Review by marionb — APPROVED** [review]
LGTM Thanks!

**Review by faselm — APPROVED** [review]

**Pull request merged**
