### PR TITLE
Remove @requires_authorization for color service

### PR DESCRIPTION
**Pull request by oterral**
Should fix the display of icons in Google earth.

### CODE REVIEW

**Comment by gjn** [comment]
LGTM. merge when jenkins happy or unrelated.

**Comment by loicgasser** [comment]
chsdi/views/color.py:6:1: F401 'chsdi.lib.decorators.requires_authorization' imported but unused

**Comment by loicgasser** [comment]
We could alternatively add google earth client to the list of `allowed` origins, but I am also fine with it.

**Comment by loicgasser** [comment]
And we may have a test as well please check it out

**Comment by oterral** [comment]
yes sure

**Pull request merged**
