### PR TITLE
Add a script to describe all tables deps

### PR DESCRIPTION
**Pull request by loicgasser**
@ltclm this is more or less the same approach taken in https://github.com/geoadmin/bgdi-scripts/pull/54/files

Please let me know if it's enough and works as expected.

### CODE REVIEW

**Comment by ltclm** [comment]
thanks for this @loicgasser 
a general question, how can i use this python script or other scripts in the console?
```bash
python models_scan.py
Traceback (most recent call last):
  File "models_scan.py", line 16, in <module>
    from pyramid.paster import get_app
ImportError: No module named pyramid.paster

```

**Comment by loicgasser** [comment]
`.venv/bin/python` :)

**Comment by ltclm** [comment]
thanks, the script is working fine.
a comma separated list of the referenced attributes would be good to know. do you think that's doable?

**Comment by loicgasser** [comment]
I am not sure what you mean by `the referenced attributes`

**Comment by ltclm** [comment]
the attributes which are configured in the model

**Comment by loicgasser** [comment]
Oh yes that's easy

**Comment by loicgasser** [comment]
done in https://github.com/geoadmin/mf-chsdi3/pull/2156/commits/a03a5afe39c6e2246fae482b87cc284a9d5cb82b

It's a flat list of column names.

**Comment by ltclm** [comment]
great, thank you @loicgasser 
from my side ready to merge
@AFoletti is it ok for you too?

**Comment by gjn** [comment]
Very nice. Thanks alot!

**Comment by AFoletti** [comment]
:heart: this script!

**Pull request merged**
