### PR TITLE
Update sparql queries

### PR DESCRIPTION
**Pull request by p1d1d1**

### CODE REVIEW

**Comment by p1d1d1** [comment]
@danduk82 could you take this for the next deploy?

**Comment by p1d1d1** [comment]
@danduk82 ok for deploy 27/02?

**Comment by danduk82** [comment]
added to the milestone

**Comment by p1d1d1** [comment]
@danduk82 @rebert could you please take care that this will be in the next deploy?
thanks

**Comment by rebert** [comment]
@p1d1d1 of course - we added the milestone 2019-02-27

**Comment by p1d1d1** [comment]
appreciate, thanks

**Pull request merged**
