### PR TITLE
[WIP] CHSDI are.agglomerationsverkehr

### PR DESCRIPTION
**Pull request by Simon1193**
[testlink on dev](https://mf-chsdi3.dev.bgdi.ch/ltbei/shorten/882327a61e)

### CODE REVIEW

**Comment by rebert** [comment]
@Simon1193 CHSDI seems to work fine! but the wms has not been integrated right in the testlink

**Comment by Simon1193** [comment]
> @Simon1193 CHSDI seems to work fine! but the wms has not been integrated right in the testlink

Yes exactly. I still don't know why. I though it was because of the projection but it seems not. I will further investigate

**Comment by Simon1193** [comment]
> @Simon1193 CHSDI seems to work fine! but the wms has not been integrated right in the testlink
@rebert I forgot to add the snippet on wms.map. Now it's ready for review!

**Comment by ltclm** [comment]
theres a new clean pr rebased on the latest master and data branch.
https://github.com/geoadmin/mf-chsdi3/pull/3436

**Pull request closed without merging**
