### PR TITLE
Model, mako and translations for geologie-rohstoffe*

### PR DESCRIPTION
**Pull request by nadine-piveteau**
Concerned Layers: 

- ch.swisstopo.geologie-rohstoffe-salz_abbau_verarbeitung
- ch.swisstopo.geologie-rohstoffe-gips_abbau_verarbeitung
- ch.swisstopo.geologie-rohstoffe-zement_abbau_verarbeitung

Legends are still missing

[Testlink](https://mf-chsdi3.int.bgdi.ch/ltpin_rohstoffe/shorten/7ab816c7dd)
Edit ltfoa: adapted testlink

### CODE REVIEW

**Comment by AFoletti** [comment]
@rebert could you please review the last fixes? This has to be merged for next deploy.
Thanks!

**Comment by AFoletti** [comment]
I'll let @nadine-piveteau refactor it if needed 😉

**Comment by rebert** [comment]
@procrastinatio

**Comment by procrastinatio** [comment]
I try to merge after passing tests

**Pull request merged**
