### PR TITLE
Fill the content type header when not present in files service

### PR DESCRIPTION
**Pull request by oterral**
Fix https://github.com/geoadmin/mf-geoadmin3/issues/2479

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@procrastinatio could you please review ?

**Comment by procrastinatio** [comment]
Depending of you client (IE, curl or nostest), if you don't set `Content-Type`, `request-encoding_type` may ends with `None`, `''`or `application/x-www-form-urlencoded`, which is very cool in deed.

**Comment by procrastinatio** [comment]
jenkins test

**Comment by procrastinatio** [comment]
jenkins test

**Comment by oterral** [comment]
@procrastinatio or @gjn, could we merge this one for tomorrow?

**Comment by gjn** [comment]
LGTM. @procrastinatio ?

**Comment by procrastinatio** [comment]
Yes, I was waiting for jenkins to pass.

**Pull request merged**
