### PR TITLE
Sort by label if order key does not exist

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3473

### CODE REVIEW

**Comment by procrastinatio** [comment]
I don't get it: https://mf-geoadmin3.dev.bgdi.ch/?api_url=http:%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgal_labelsort&lang=fr&topic=ech

**Comment by loicgasser** [comment]
https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgal_labelsort&lang=fr&topic=ech
Try this one

**Comment by procrastinatio** [comment]
So, if I do understand, layer's name have to be alphabetically sorted, but only if no key is available ? So something like:  that is not correct ? _Voyage > Cartes > Atlas_

**Comment by loicgasser** [comment]
Yes for some categories we have an order key and for some other we don't. When the order key is not defined, we want to sort it alphabetically. But that s only valid for nodes of the same order. Did you catch anything suspicious ?

**Comment by procrastinatio** [comment]
Looks good, except maybe that **Ä** or **ä** are shown after **z**.

See by yourself: https://mf-chsdi3.dev.bgdi.ch/~ltmom/json_sorting.html, some categories makes absolutely no sense, but as it is the same order across langage, I suppose it is the right order.

**Comment by loicgasser** [comment]
Oh thank you for noticing the ä sorting.

**Comment by loicgasser** [comment]
ok fixed thanks for the review

**Pull request merged**
