### PR TITLE
[WIP] Trying to fix ivs-verlaeufe

### PR DESCRIPTION
**Pull request by procrastinatio**
If someone has a better idea to fix https://github.com/geoadmin/mf-chsdi3/issues/1669

[Demo](http://mf-chsdi3.dev.bgdi.ch/mom_fix_1669/mapproxy/demo) (still deplyoing at the time writting)

or [even better](http://mf-chsdi3.dev.bgdi.ch/mom_fix_1669/examples/ol3_lv95_all.html?layer=ch.astra.ivs-nat-verlaeufe&timestamp=20100416&format=png&base_url=http://mf-chsdi3.dev.bgdi.ch/ltmom)

### CODE REVIEW

**Comment by procrastinatio** [comment]
At least all tests pass: `./buildout/bin/nosetests chsdi/tests/e2e/test_wmtsgettile.py`

I have no better idea how to solve this one. So if anybody of @cedricmoullet @mariavkourouni @ltclm @alcapat @AFoletti @rfrancel @daguer has a smarter idea, I would be glad.

**Comment by procrastinatio** [comment]
Well in fact, the tiles of this layer are a patchwork of color and greyscale png:

```
$ file 17_5_10.png
17_5_10.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
$ file 17_5_9.png
17_5_9.png: PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
```

So when mapproxy is trying to reassemble this patchwork into a single tile and applying a quantize filter, it breaks.

So, the fix is to have source tiles in the exactly same png format, not a patchwork.

**Comment by ltclm** [comment]
obviously optipng during the tilegeneneration is messing up the image type:
**tileworker output with ``optipng -q -zc9 -zm9 -zs3 -f0 %filename``**
```bash
21781/17/5$ file *.png
10.png: PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
11.png: PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
12.png: PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
13.png: PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
14.png: PNG image data, 256 x 256, 8-bit colormap, non-interlaced
15.png: PNG image data, 256 x 256, 1-bit colormap, non-interlaced
16.png: PNG image data, 256 x 256, 8-bit colormap, non-interlaced
4.png:  PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
5.png:  PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
6.png:  PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
7.png:  PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
8.png:  PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
9.png:  PNG image data, 256 x 256, 8-bit gray+alpha, non-interlaced
```

**tileworker output without optipng**
```bash
21781/17/5$ file *.png
10.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
11.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
12.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
13.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
14.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
15.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
16.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
4.png:  PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
5.png:  PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
6.png:  PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
7.png:  PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
8.png:  PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
9.png:  PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
```

**Comment by ltclm** [comment]
We would have to recreate all tiles for the affected layers and change or disable the optipng configuration. This would result in bigger tiles and a loss of performance.
What are our other options?
If a tilesource with heterogenous image modes (colormode, depth) is not a foreseen use case in our mapproxy version we could also try to 
* upgrade to mapproxy 1.8 or 1.8.1
* hack the image processor in mapproxy

Sorry i dont have any other idea, but recreating the affected layers is probably not the best solution.

**Comment by gjn** [comment]
@ltclm Does the update to 1.8 mention anything regarding this issue? Or is it shot in the dark?

**Comment by gjn** [comment]
btw, there might be other layers where we have this issue. Our tests don't test every tile in mapproxy, but one tile for every layer defined.

**Comment by procrastinatio** [comment]
Updating to Mapproxy 1.8 will not solve anything. 

See https://github.com/geoadmin/mf-chsdi3/pull/1685

**Comment by procrastinatio** [comment]
@gjn My PR has been merged into Mapproxy master. Do we switch to Mapproxy master ?
When will we make the switch to `service-mapproxy` ? For now I am correcting both project.

**Comment by procrastinatio** [comment]
Se PR https://github.com/geoadmin/mf-chsdi3/pull/1690 and close this one

**Pull request closed without merging**
