### PR TITLE
LUBIS release

### PR DESCRIPTION
**Pull request by procrastinatio**
Testing for missing attributes. Years list is still empty

See https://github.com/geoadmin/mf-chsdi3/issues/2698

### CODE REVIEW

**Comment by ltclm** [comment]
years list is probably empty because of the lv95 migration.
@loicgasser has the releases service been migrated to lv95 to?
the zeitreihen data for releases is still lv03, thats why it is still working. the lubis data is now in lv95.

**Comment by loicgasser** [comment]
no releases is a zeitreihen service only.
Time series in print was also only designed for zeitreihen.
People forget so much...

layers config right here tells what years there are. On top of it lubis are points, and release service is intersecting with a point and not a bbox.

@procrastinatio I propose that you pass in the timestamps to the print and that you raise a 400 if the release service is used with something else than zeitreihen.


```
ch.swisstopo.lubis-bildstreifen: {
shop: [
"mapsheet"
],
wmsUrl: "https://wms.geo.admin.ch",
background: false,
searchable: true,
serverLayerName: "ch.swisstopo.lubis-bildstreifen",
highlightable: true,
timeEnabled: true,
attributionUrl: "https://www.swisstopo.admin.ch/fr/home.html",
tooltip: true,
label: "Bandes d'images aériennes swisstopo",
singleTile: false,
timestamps: [
"2017",
"2016",
"2015",
"2014",
"2013",
"2012",
"2011",
"2010",
"2009",
"2008",
"2007",
"2006",
"2005"
],
type: "wms",
topics: "api,ech,luftbilder,swisstopo,wms-bgdi",
attribution: "swisstopo",
format: "png",
chargeable: false,
wmsLayers: "ch.swisstopo.lubis-bildstreifen",
gutter: 20,
timeBehaviour: "all",
hasLegend: true,
queryableAttributes: [
"id"
]
}
```

**Comment by procrastinatio** [comment]
@loicgasser @ltclm 
* `releases` service works fine in both lv95 and lv03
* See https://github.com/geoadmin/mf-geoadmin3/issues/2099. If we want to print timeserie for LUBIS layer, we need to know wich years to print in a given extent. It is a **new** feature. Nothing broken here.

**Comment by procrastinatio** [comment]
I guess it is a complexe issue, because the `flugjahr` is not what you see on the map at `published year`, it was usually 3 years later.

**Comment by loicgasser** [comment]
I fixed the build and added the test for zeitreihen.

**Pull request merged**
