### PR TITLE
Improve full text search perfs

### PR DESCRIPTION
**Pull request by loicgasser**
Using `like` in conjuction with `lower` is faster than `ilike`. @ltcm can confirm I think.

### CODE REVIEW

**Comment by gjn** [comment]
Doens't this require that all texts in the db to be lower case?

**Comment by loicgasser** [comment]
Yes.

Topics are always lower case.

`full_text_search` is used in https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/layers.py#L49
The fullTextSearch, layerBodId and geoCatId are lower case.

`full_text_search` is also used in the find service.
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/features.py#L471
This might be an issue. I may only change it for the topic search to be on the safe side.

**Comment by gjn** [comment]
Yes. It would be nice to have sample tests for all use cases you mentioned.

I assume the `fullTextSearch` column of the layers is a special index with lower case only. Is this correct?

**Comment by loicgasser** [comment]
yes

**Comment by loicgasser** [comment]
let's just do that for the topics.

**Comment by gjn** [comment]
Any metrics on the performance improvements?

**Comment by loicgasser** [comment]
just a stackoverflow http://stackoverflow.com/questions/20336665/lower-like-vs-ilike
It's a minor change as it just affects the topic search

**Comment by gjn** [comment]
ok. Please merge once build is ok.

**Pull request merged**
