### PR TITLE
Rename shop layers

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by daguer** [comment]
@loicgasser : the last 3 layers to rename: I have made 3 new layers

**Comment by loicgasser** [comment]
Great as those are pointing to the same layer you should define `extend_existing=True`.
Could you prepare a SQL migration script we can apply after the deploy?
Basically a set of DELETE commands in the correct order.

**Comment by loicgasser** [comment]
I meant the same table.

**Comment by loicgasser** [comment]
To test your migration script make sure you use your own DB.

**Comment by loicgasser** [comment]
Now if you could prepare the delete PR post-deploy please?

**Pull request merged**
