### PR TITLE
fix search test

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Review by ltclm — APPROVED** [review]
thank you @rebert 
did the local tests pass?

**Comment by rebert** [comment]
@ltclm the local tests passed with this change

**Comment by ltclm** [comment]
ok, will merge as soon as codebuild tests have passed.

**Review by marionb — APPROVED** [review]
Thanks.

**Comment by ltclm** [comment]
@faselm @marionb @b4l 
please rebase your prs for the next deploy, the integration tests had to be adapted.

**Pull request merged**
