### PR TITLE
Update ol3

### PR DESCRIPTION
**Pull request by loicgasser**
https://github.com/geoadmin/ol3/pull/118 must be merged first.

### CODE REVIEW

**Comment by oterral** [comment]
PR updated with last version.

[Test link](http://mf-chsdi3.dev.bgdi.ch/gal_update_ol3/)

**Comment by loicgasser** [comment]
Cool thanks

**Comment by oterral** [comment]
No bug found @ponceta can you make some tests ?

**Comment by ponceta** [comment]
Seems great works on all browsers and mobile

[Test for geoadmin](http://mf-geoadmin3.dev.bgdi.ch/ltpoa)

**Pull request merged**
