### PR TITLE
Add models, mako and legends for bfe meteo vereisung

### PR DESCRIPTION
**Pull request by pfanguin**
Test link : https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Ffap_bfe_vereisung&layers=ch.bfe.meteorologische-vereisung

layers : ch.bfe.meteorologische-vereisung

### CODE REVIEW

**Comment by loicgasser** [comment]
LGTM

**Comment by loicgasser** [comment]
https://mf-chsdi3.dev.bgdi.ch/fap_bfe_vereisung/rest/services ?? doesn't work

**Comment by loicgasser** [comment]
lol works again

**Comment by loicgasser** [comment]
some weird behaviour, identify doesn't work either.

**Comment by AFoletti** [comment]
LGTM. Hope the BFE accepts the aggregated raster cells

**Comment by loicgasser** [comment]
Hope so to, but deploy is for tomorrow, so...

**Pull request merged**
