### PR TITLE
Update legend for bafu layer

### PR DESCRIPTION
**Pull request by alcapat**
ch.bafu.wrz-jagdbanngebiete_select and ch.bafu.wrz-wildruhezonen_portal
change red line to green for permitted paths

### CODE REVIEW

**Comment by alcapat** [comment]
This PR is necessaryonly if we have received the new update and if new tiles (with green line) are generated

**Comment by gjn** [comment]
Let us know when it's ready to be tested.

**Comment by alcapat** [comment]
Update Mapproxy layer list according to the command describe on doc Remeber_when_deploying

**Comment by procrastinatio** [comment]
`mapproxy.yaml`i not needed anymore.

**Pull request merged**
