### PR TITLE
Update ch.swisstopo.treasurehunt

### PR DESCRIPTION
**Pull request by b4l**
- [x] **Revert commit `dc38fbc7653c4207d65df6ef50e1e6dd483c4d87` before merging!**

### CODE REVIEW

**Comment by b4l** [comment]
test link: https://mf-chsdi3.dev.bgdi.ch/shorten/8a81e2ee46

**Comment by b4l** [comment]
I reverted the change of the production.ini and configured the layer in bod_master. @ltclm could you have a look if everything is ok for the next deploy? Thanks!

**Review by ltclm — APPROVED** [review]
thank you @b4l !

**Comment by ltclm** [comment]
image
i guess it is accepted that the symbol is not exactly pointing to the coordinate in the json?

**Comment by mariokeusen** [comment]
@ltclm : yes, this has been accepted after weeks of testing and by signature of the acceptance doc.

**Pull request merged**
