### PR TITLE
fix str/unicode issue in lubis mako

### PR DESCRIPTION
**Pull request by ltclm**
fixes https://github.com/geoadmin/mf-chsdi3/issues/1559

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@procrastinatio could you please review ?

**Comment by procrastinatio** [comment]
I think is is better to use a Mako the filter `trim` (note the `|`pipe)
`${c['attributes']['ort']|trim }`

**Comment by ltclm** [comment]
I have replaced ``.strip()`` with `` | trim``

**Comment by procrastinatio** [comment]
This branch is OK, compare with [main](https://mf-chsdi3.dev.bgdi.ch/rest/services/ech/MapServer/ch.swisstopo.lubis-luftbilder_schwarzweiss/19512530016462/extendedHtmlPopup?lang=fr)

**Comment by ltclm** [comment]
@procrastinatio did you merge this branch?
The current https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/templates/htmlpopup/lubis.mako does not have theses changes.

**Pull request merged**
