### PR TITLE
Add models and mako for layers laermbelastung-eisenbahn

### PR DESCRIPTION
**Pull request by Sgachet**

### CODE REVIEW

**Comment by Sgachet** [comment]
[Test link](https://mf-chsdi3.dev.bgdi.ch/gas_laermbelastung-eisenbahn/shorten/7515a71e9a )

**Comment by loicgasser** [comment]
rebase as well and squash

**Comment by Sgachet** [comment]
@loicgasser it's ready to merge

**Comment by loicgasser** [comment]
error is not related to this build I'll merge
AssertionError: ch.bafu.bundesinventare-vogelreservate_de.png image is too big, 515px instead of 480px

**Pull request merged**
