### PR TITLE
Update legends ch.bfe.thermische-netze

### PR DESCRIPTION
**Pull request by faselm**
New pr as the client reversed the changes.
Test link: https://mf-chsdi3.dev.bgdi.ch/ltfas_bfe_thermische_netze/shorten/92cbbebf64

### CODE REVIEW

**Review by ltclm — APPROVED** [review]
can we completely remove the attribute contact from the table,  chsdi model and identify response too?

**Comment by faselm** [comment]
> can we completely remove the attribute contact from the table, chsdi model and identify response too?

@ltclm I don't know but there is still data delivered for it in the raw data. I can ask Véronique..

**Comment by ltclm** [comment]
> > can we completely remove the attribute contact from the table, chsdi model and identify response too?
> 
> @ltclm I don't know but there is still data delivered for it in the raw data. I can ask Véronique..

yes please, in this state we will still have the attribute in identtify response but not in htmlpopup response which is not ideal.

**Comment by faselm** [comment]
@ltclm It will be still used in the extended tooltip...

**Comment by AFoletti** [comment]
> @ltclm It will be still used in the extended tooltip...

Dear integrators
Just a heads-up from the BFE side of the barricade 😉 

If the data contains an attribute and it is referenced in the DIF table, then it is meant to be available via the BGDI services even if it does not come up in the normal or extended tooltip.
We sometimes build apps/visualizations on the BDGI services that use attributes not visible in any tooltip.
Thanks!

**Pull request merged**
