### PR TITLE
Update to Jessie, node 5.9.1 and npm 3.7.3

### PR DESCRIPTION
**Pull request by loicgasser**
https://github.com/geoadmin/mf-geoadmin3/issues/3393

Tested:
- [x] Build is successful
- [x] Tests are passing
- [x] e2e tests are passing
- [x] Update js api
- [x] Deploydev command works
- [x] Deploybranch command works
- [x] Deplysnapshot command works
- [x] Test vhosts and apache configuration (app in general)
- [x] Deploy to integration instances
- [x] Migrate Jenkins instance

Build fail is related to https://github.com/geoadmin/db/commit/6036245eccacba4f1b781d7a325d2a409555fe3e

### CODE REVIEW

**Comment by loicgasser** [comment]
All tests ok but the ones involving geoadmin file storage service

**Comment by oterral** [comment]
I've rss problem here when build:
```
Creating the rss feed from releasenotes
.venv/bin/python scripts/rssFeedGen.py
Traceback (most recent call last):
  File "scripts/rssFeedGen.py", line 97, in <module>
    rss = rss.to_xml('utf-8')
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 39, in to_xml
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 34, in write_xml
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 380, in publish
  File "scripts/rssFeedGen.py", line 25, in publish
    PyRSS2Gen.RSSItem.publish(self, handler)
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 429, in publish
  File "scripts/rssFeedGen.py", line 28, in publish_extensions
    handler._out.write('<%s><![CDATA[%s]]></%s>' % ('description', self.do_not_autooutput_description, 'description'))
AttributeError: XMLGenerator instance has no attribute '_out'
Makefile:162: recipe for target 'rss' failed
make[1]: *** [rss] Error 1
make[1]: Leaving directory '/home/ltteo/mf-chsdi3'
Makefile:108: recipe for target 'user' failed
make: *** [user] Error 2

```

Any idea ?

**Comment by loicgasser** [comment]
Hum, I thought I fixed that in https://github.com/geoadmin/mf-chsdi3/pull/2165/commits/1ed63894f73b292bdbc6d3e114b155d0f14e6e07.

**Comment by oterral** [comment]
Arf wrong branch , sorry for the noise.

**Comment by gjn** [comment]
mf-geoadmin3
mf-chsdi3
service-print
service-alti
storymaps

not needed:
web-dashboard

**Comment by loicgasser** [comment]
Note that without https://github.com/geoadmin/ol3/pull/142

updateapi target will always fail as node deps are old and outdated.

**Comment by loicgasser** [comment]
[Test Link](https://mf-chsdi3.infra.bgdi.ch)

**Comment by loicgasser** [comment]
Boouum https://service-print.infra.bgdi.ch/print/info.json?url=https%3A%2F%2Fservice-print.infra.bgdi.ch%2Fprint

**Comment by loicgasser** [comment]
Seems like there is difference in accesss rights for py libs

Wheezy
```-rw-rwSr-- 1 ltgal geodata 1 Oct 19 14:26 /var/www/vhosts/service-print/private/print/.venv/lib/python2.7/site-packages/pycodestyle-2.0.0-py2.7.egg/EGG-INFO/namespace_packages.txt```

Jessie
```-rw-rwS--- 1 ltgal geodata 1 Oct 26 14:45 /var/www/vhosts/service-print/private/print/.venv/lib/python2.7/site-packages/pycodestyle-2.0.0-py2.7.egg/EGG-INFO/namespace_packages.txt```

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Pull request merged**
