### PR TITLE
Data emapis

### PR DESCRIPTION
**Pull request by AFoletti**
PR for the emapis layers. Still waiting for definitive approval

### CODE REVIEW

**Comment by AFoletti** [comment]
@alcapat could you please review those layers until next monday? Thanks!

**Comment by AFoletti** [comment]
Thanks Patrick for the review.
Problems fixed. Still need the new legends, but I would like to merge that anyways.
Please note that even if the code will be merged, no layer will go to prod for the next X weeks (where XX > 4)

**Comment by AFoletti** [comment]
corrected legends pushe. All OK now

**Comment by loicgasser** [comment]
Remove WIP from text if ok otherwise it s confusing. ;)

**Comment by AFoletti** [comment]
merge, anyone?

**Pull request merged**
