### PR TITLE
Data hydrologie messstationen gefahren

### PR DESCRIPTION
**Pull request by alcapat**

### CODE REVIEW

**Comment by AFoletti** [comment]
I'll wait to put this one as "next deploy" ;). Abnahmeprotokoll is still pending

**Comment by loicgasser** [comment]
For my knowledge what's the difference between ch.bafu.hydroweb-messstationen_gefahren and ch.bafu.hydrologie-messstationen_gefahren ?? Same layer?

**Comment by AFoletti** [comment]
that's a question for @mariokeusen. Apparently BAFU requested the layer (see the [redmine ticket] (https://redmine.prod.bgdi.ch/issues/5921) ) but the info is exactly the same as in the hydroweb layer.

**Comment by loicgasser** [comment]
Then we don't really need to create a nee symbology in CHSDI, just use the same and register the model with a new id as well, it will work as an alias. @alcapat is that why you closed this PR?

**Pull request closed without merging**
