### PR TITLE
Update sdiservices.rst

### PR DESCRIPTION
**Pull request by mariokeusen**
Some of the service examples have been fixed, because they didn't work anymore (esp. identify examples with old bfs layer data)

### CODE REVIEW

**Review by davidoesch — COMMENTED** [review]
LGTM

**Comment by rebert** [comment]
The content LGTM. Why are you not making a PR to the branch? develop-2022-03-16 following the new workflow. This would simplify our live.

**Comment by davidoesch** [comment]
@rebert hast du mir noch den link zum neuen workflow?

**Comment by rebert** [comment]
Deploy Guidline:
https://github.com/geoadmin/doc-guidelines/blob/master/DEPLOY.md

Milestone workflow (data/deploy dependend): 
https://github.com/geoadmin/doc-guidelines/blob/master/GITHUB_WORKFLOW.md#setting-up-milestone-workflow

Wiki:
https://ltwiki.adr.admin.ch:8443/display/BGDI/03_VIEWER

**Comment by rebert** [comment]
opened pr to branch develop-03-16 https://github.com/geoadmin/mf-chsdi3/pull/3808

**Pull request closed without merging**
