### PR TITLE
[WIP] ch.bafu.gefahren-basiskarte

### PR DESCRIPTION
**Pull request by ltclm**
[testlink](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fdev_ltclm_bafu_basiskarte&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bafu.gefahren-basiskarte&layers_opacity=0.75)

### CODE REVIEW

**Comment by loicgasser** [comment]
Seems like you have a little git issue looking at your commit history

**Comment by ltclm** [comment]
thanks @loicgasser 
i have fixed the commits.

**Comment by loicgasser** [comment]
Nice we really should tile it. it's slow

**Comment by ltclm** [comment]
as soon as zadara is replaced by efs, the performance will be much better. wms-dev is using an old version of the raster files. meanwhile i have created overview images for a better performance.
We cannot tile this layer because it's extent is bigger than our default pyramid extent.

**Comment by loicgasser** [comment]
I guess we don't have a choice then. That's a shame on average it takes 4 secs to load.

**Comment by loicgasser** [comment]
Is it still WIP?

**Comment by ltclm** [comment]
yes, we wait for zadara2efs migration to be finished, check the performance and decide afterwards.

**Comment by ltclm** [comment]
@loicgasser  the zadara migration has been finished.

**Comment by loicgasser** [comment]
Do we go with this version?

**Comment by ltclm** [comment]
yes

**Comment by loicgasser** [comment]
Ok 👌 remove wip in title so we know when to review

**Pull request merged**
