### PR TITLE
[WIP] new layer ch.bfe.biogasanlagen

### PR DESCRIPTION
**Pull request by pakb**

### CODE REVIEW

**Comment by procrastinatio** [comment]
Rebase on master, I did deactivate `test_too_large_feature_only_attributes` (we don't have large features anymore, apparently)

**Comment by rebert** [comment]
@pakb on the first glance it looks good to me. Only remark so far, could you please provide a testlink?

**Comment by pakb** [comment]
Here : https://mf-chsdi3.int.bgdi.ch/ltbtp_bfe_biogasanlagen/shorten/7ff7f82b04

**Comment by rebert** [comment]
@pakb has nothing to do with the code. But This image does not exist:
https://mf-chsdi3.int.bgdi.ch/ltbtp_bfe_biogasanlagen/1902141056/rest/services/ech/MapServer/ch.bfe.biogasanlagen/1155/htmlPopup?coord=2621000.0000000005,1092750.0000000002&imageDisplay=1920,661,96&lang=de&mapExtent=2114960.5,1020858.69,3074960.5,1351358.69&sr=2056

**Comment by rebert** [comment]
@pakb we are going to merge after technical deploy

**Comment by pakb** [comment]
yes, there was one plant that had no data whatsoever (for yearly production), you might have stubble upon "the one" 😄. I could put some checkers before building the image URL as I also know if there is some data for a plant.
The graphic is given by the BFE themselves so I haven't checked for data validity (and them neither 😉).

**Pull request merged**
