### PR TITLE
added xyz description

### PR DESCRIPTION
**Pull request by davidoesch**
@procrastinatio can you review and add an example in codepen?
@p1d1d1 feedback welcome

### CODE REVIEW

**Comment by ltshb** [comment]
@davidoesch and @procrastinatio can this be merged and deployed with the next deploy on 2022-03-16 ?

**Comment by davidoesch** [comment]
A go from my side

**Review by ltshb — CHANGES_REQUESTED** [review]
This can not be merge like this. This is not production ready and still contain TODO.
@davidoesch what is XYZ ? Looks to be a quick copy paste of the WMTS chapter, I don't understand the goal of adding this chapter when it is already documented in WMTS. Note to not block current deploy of 2022-03-16 I'll remove this PR from milestone.

**Comment by rebert** [comment]
going to make a PR on branch develop-2022-05-18

**Comment by davidoesch** [comment]
so pretty please, with sugar on the top, can IGEB  please contribute to the issue as mentioned above?

**Comment by ltshb** [comment]
@davidoesch please refer to the new PR #3837 not this one which is closed. IMHO it does not only need an example, but clearly a definition of what you want ! A copy paste of service WMTS chapter with just some small changes for describing something that the same is not a good documation at all. As I already say we have a process with jira and if you at first defined directly in a Jira ticket  and/or talked in our planning what you really want this would have been already done without sugar. So stop commenting this here and bring this in our regular planning meeting, otherwise we can stop scrum and planning.

**Pull request closed without merging**
