### PR TITLE
updated astra unfaelle legends

### PR DESCRIPTION
**Pull request by AFoletti**
reworked astra unfaelle legends

### CODE REVIEW

**Comment by loicgasser** [comment]
LGMT

**Comment by gjn** [comment]
LGTM. @davidoesch @cedricmoullet

**Comment by cedricmoullet** [comment]
Not sure that U(g), U(sv)... brings something to user. Otherwise ok for me.

**Comment by davidoesch** [comment]
Ok. The U are introduced by dataowner

**Pull request merged**
