### PR TITLE
[WIP] Dummy

### PR DESCRIPTION
**Pull request by gjn**
ignore, used for testing only

### CODE REVIEW

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by loicgasser** [comment]
it worked

**Comment by gjn** [comment]
yep, just wrote an email about it.

**Comment by gjn** [comment]
build failed: https://jenkins.dev.bgdi.ch/job/PR_chsdi3/1/console

**Comment by loicgasser** [comment]
unrelated though
```
======================================================================
ERROR: chsdi.tests.integration.test_layers.test_all_htmlpopups(u'ch.swisstopo.swissbuildings3d_2.metadata', 'BUILD3D2', False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/PR_chsdi3/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/workspace/PR_chsdi3/chsdi/tests/integration/test_layers.py", line 99, in checkHtmlPopup
    resp = self.testapp.get(link)
  File "/var/lib/jenkins/workspace/PR_chsdi3/.venv/lib/python2.7/site-packages/webtest/app.py", line 327, in get
    expect_errors=expect_errors)
  File "/var/lib/jenkins/workspace/PR_chsdi3/.venv/lib/python2.7/site-packages/webtest/app.py", line 636, in do_request
    self._check_status(status, res)
  File "/var/lib/jenkins/workspace/PR_chsdi3/.venv/lib/python2.7/site-packages/webtest/app.py", line 668, in _check_status
    res)
AppError: Bad response: 509 Bandwidth Limit Exceeded (not 200 OK or 3xx redirect for http://localhost/rest/services/all/MapServer/ch.swisstopo.swissbuildings3d_2.metadata/BUILD3D2/htmlPopup?callback=cb_&lang=de)
509 Bandwidth Limit Exceeded
```

**Comment by loicgasser** [comment]
don't you receive my messages on gmail? or whatsapp?

**Pull request closed without merging**
