### PR TITLE
Increase coverage chsdi.views.height

### PR DESCRIPTION
**Pull request by mariavkourouni**

### CODE REVIEW

**Comment by mariavkourouni** [comment]
jenkins test

**Comment by mariavkourouni** [comment]
jenkins test

**Comment by pfanguin** [comment]
jenkins test

**Comment by loicgasser** [comment]
That's a goos test, but I am not sure the height service should return simply a 200 code and None if the requested point is out of Switzerland.
We should change that.

**Comment by loicgasser** [comment]
@mariavkourouni can you make a proposal?

**Comment by mariavkourouni** [comment]
Do you mean that in this case the height service should return a bad request?

**Comment by loicgasser** [comment]
Yes either bad request, either a JSON like this:
```JSON
{
  "success": false,
  "error": {
    "code": 400,
    "message": "Requested coordinate out of bounds"
  }
}
```
@gjn @procrastinatio what do yo prefer?

**Comment by gjn** [comment]
I think we should return a 400 and put `Requested coordinate out of bounds` as reason. We should not return a 200.

**Comment by loicgasser** [comment]
Agree, @mariavkourouni could you change that in the service and adapt the test accordingly?

**Comment by mariavkourouni** [comment]
adapted!

**Comment by loicgasser** [comment]
Thanks a lot

**Pull request merged**
