### PR TITLE
[WIP] switch to point on a geoadmin/ol3 in lv95

### PR DESCRIPTION
**Pull request by rebert**
Switch for a geoadmin/ol3 env in lv95
default: [try](http://mf-chsdi3.int.bgdi.ch/ltrea_lv95/loader.js)
sr=2056: [try](http://mf-chsdi3.int.bgdi.ch/ltrea_lv95/loader.js?sr=2056)
sr=21781: [try](http://mf-chsdi3.int.bgdi.ch/ltrea_lv95/loader.js?sr=21891)
sr=fuckitup: [try](http://mf-chsdi3.int.bgdi.ch/ltrea_lv95/loader.js?sr=4326)

### CODE REVIEW

**Comment by loicgasser** [comment]
Sure, but what is the ol3 api related PR?
LGTM

**Comment by rebert** [comment]
@loicgasser this PR is missing, we were waiting until @oterral is back!

**Comment by loicgasser** [comment]
Hi, @rebert what's the status here? Did we replace this PR with another one?

**Comment by rebert** [comment]
@loicgasser the new version geoadmin/ol3 is per default lv95

**Pull request closed without merging**
