### PR TITLE
BGDIDIC-1989: Add ch.vbs.panzerverschiebungsrouten

### PR DESCRIPTION
**Pull request by b4l**
Test link: https://mf-chsdi3.dev.bgdi.ch/feature_BGDIDIC-1989/shorten/8e6fdc8a07

Script: https://github.com/geoadmin/bgdi-scripts/pull/806

WMS: https://github.com/geoadmin/wms-mapfile_include/pull/605

### CODE REVIEW

**Review by faselm — COMMENTED** [review]
Symbology, legends, tooltips look good!

**Review by marionb — APPROVED** [review]
LGTM, Thanks!

**Review by ltclm — APPROVED** [review]
lgtm but i would like to know why there is only a tooltip on the point features, its a bit confusing for an enduser in my opinion.

**Comment by faselm** [comment]
> lgtm but i would like to know why there is only a tooltip on the point features, its a bit confusing for an enduser in my opinion.

I actually also desperately tried to get info from the line :) I agree, it's a bit confusing...

**Comment by b4l** [comment]
@ltclm this is specified so in the DIF, also there is no such information for the lines. Maybe @mariokeusen has some more insights from the tank drivers and owners.

**Pull request merged**
