### PR TITLE
Change qrcode and shortlink url on every pages when multi-pages printing

### PR DESCRIPTION
**Pull request by procrastinatio**
Fixing https://github.com/geoadmin/mf-geoadmin3/issues/2020

The QRcode URl also needs to be corrected on the mf-geoadmin3 side: see also https://github.com/geoadmin/mf-geoadmin3/issues/2067

Test against this: http://mf-chsdi3.dev.bgdi.ch/mom_multiprint_qrcode/

### CODE REVIEW

**Comment by procrastinatio** [comment]
Need to rework it.

**Comment by procrastinatio** [comment]
Test against this: http://mf-chsdi3.dev.bgdi.ch/mom_multiprint_qrcode/

**Comment by loicgasser** [comment]
Ok I ll check again. Thanks!

**Comment by loicgasser** [comment]
```
ltgal@ip-10-220-4-46 (vpc/mf0 - test):~/mf-chsdi3/chsdi/tests/print$ curl http://s.geo.admin.ch/62a88d5c5e
<html>
 <head>
  <title>301 Moved Permanently</title>
 </head>
 <body>
  <h1>301 Moved Permanently</h1>
  The resource has been moved to https://mf-geoadmin3.dev.bgdi.ch/ltgal/src/?lang=en&amp;catalogNodes=1392&amp;bgLayer=ch.swisstopo.pixelkarte-farbe&amp;layers=ch.swisstopo.zeitreihen&amp;time=1864&amp;zoom=1&amp;topic=swisstopo&amp;layers_timestamp=18641231&amp;Y=660000.00&amp;X=190000.00; you should be redirected automatically.


 </body>
```

I still get `&amp`

**Comment by loicgasser** [comment]
time substitution works, it really the decoding/encoding that fails. Did you take into account:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/qrcode_generator.py#L17

**Comment by gjn** [comment]
@procrastinatio What's the state of this PR? Seems like @loicgasser still found some problems.

**Comment by gjn** [comment]
jenkins test

**Comment by procrastinatio** [comment]
OK, reworked, rebased.

**Comment by gjn** [comment]
This works like a charm. Thanks alot for this.

**Pull request merged**
