### PR TITLE
Delete legends ch.swisstopo.vec200-landcover-wald

### PR DESCRIPTION
**Pull request by faselm**
Layer decommissioning

### CODE REVIEW

**Review by b4l — COMMENTED** [review]
What about model, mako, etc.?

**Comment by ltclm** [comment]
please follow the process here:
https://ltwiki.adr.admin.ch:8443/display/BGDI/BGDI+Layer+decomissioning
example:
https://jira.swisstopo.ch/browse/BGDIDIC-1960

**Review by ltclm — CHANGES_REQUESTED** [review]
please remove all components

**Comment by faselm** [comment]
I didn't find any mako and model for this layer...

**Review by ltclm — APPROVED** [review]
apparently that was an easy layer :-)

**Pull request merged**
