### PR TITLE
Update  ch.bazl.einschraenkungen-drohnen

### PR DESCRIPTION
**Pull request by Sgachet**

### CODE REVIEW

**Comment by Sgachet** [comment]
[Test link](https://mf-chsdi3.dev.bgdi.ch/gas_drohnen_update/shorten/777b4323c6)

**Comment by loicgasser** [comment]
milestone?

**Comment by Sgachet** [comment]
Still WIP, wait for DatenHerr Feedback

**Comment by Sgachet** [comment]
Update ready to go on prod on 24.01

**Pull request merged**
