### PR TITLE
Adapting test folder structure

### PR DESCRIPTION
**Pull request by gjn**
This PR adapts our folder structure for tests. Until now, we had a mixture of folders in the tests directory. One set was referring to types of tests and another set of what was tested.

This PR uses at the top level the types of tests:

`functional`: containing pure unit tests
`integration`: containing integration tests (tests that access db/sphinx backends)
`e2e`: tests that test the full stack, including varnish, apache, etc. Full end to end tests
`manual`: scripts and helpers to run tests manually

We can always add subfolders to separate what is tested further one.

The nose version is updated as well.

### CODE REVIEW

**Comment by loicgasser** [comment]
ike the new structure, much better. An typo in gitignore (chsdi3) I believe.

**Comment by gjn** [comment]
Thanks for the review. Typo corrected.

Will wait for @procrastinatio post-holiday feedback.

**Comment by gjn** [comment]
@procrastinatio Care to take a look?

**Comment by procrastinatio** [comment]
Looks much better.. All tests pass

**Pull request merged**
