### PR TITLE
split mapservice test files

### PR DESCRIPTION
**Pull request by rfrancel**
linked to issue: https://github.com/geoadmin/mf-chsdi3/issues/1977

@loicgasser  I splitted the files in two. identify tests are the most consuming (60 s out of 97s) in the features tests. Do you wantr me to make a separate identify test file?

### CODE REVIEW

**Comment by rfrancel** [comment]
jenkins test

**Comment by loicgasser** [comment]
thank you! Yes please that makes sense

**Comment by loicgasser** [comment]
Code LGTM so far

**Comment by rfrancel** [comment]
@loicgasser it's done

**Comment by gjn** [comment]
Nice. Thanks alot @rfrancel

**Pull request merged**
