### PR TITLE
Prefer x in dict over x in dict.keys()

### PR DESCRIPTION
**Pull request by cclauss**
Replicates much of https://github.com/geoadmin/mf-next/pull/63

### CODE REVIEW

**Comment by loicgasser** [comment]
LGTM

**Comment by gjn** [comment]
whitelist

**Comment by gjn** [comment]
add to whitelist

**Comment by gjn** [comment]
@loicgasser Seems like this PR broke some tests...and probably the service as well.

Could you have a look? Or revert it if now easy fix?

**Pull request merged**
