### PR TITLE
Decomission of 2 bafu layer

### PR DESCRIPTION
**Pull request by alcapat**
#2847 ch.bafu.wege-wildruhezonen-jagdbanngebiete
#2849 ch.bafu.wildruhezonen-jagdbanngebiete

### CODE REVIEW

**Comment by loicgasser** [comment]
Okay, for next deploy? BOD has already been adapted?

**Comment by ltclm** [comment]
the data is still used in  the following mapfile snippets
ch.bafu.wege-wildruhezonen-jagdbanngebiete.map
ch.bafu.wildruhezonen-jagdbanngebiete.map

and in the following wms-services
wms-bod
wms-bgdi

Can we remove them from wms-bgdi too?
If so, you can delete the tables.

**Comment by alcapat** [comment]
mapfile snippets (ch.bafu.wege-wildruhezonen-jagdbanngebiete.map and 
ch.bafu.wildruhezonen-jagdbanngebiete.map) are removed.
These 2 layers are removed from bod (dataset, ms_class, ms_item,re3.layers_js) so should not exist in wms-services.
I will remove the table.

**Comment by ltclm** [comment]
ok, thank you. please translate wms-bgdi and create a pr.

**Comment by alcapat** [comment]
layers are already removed from wms-bgdi.
This PR can be merged

**Comment by loicgasser** [comment]
@alcapat 
Here is the commit in mapfile_include
https://github.com/geoadmin/wms-mapfile_include/commit/4b7653e5a03172ba1ea98f18d9a5364d9ec197d5

Can you create and link the PR from wms-bod please? and then I'll merge.
Thanks!

**Pull request merged**
