### PR TITLE
Round is a resevered namespace

### PR DESCRIPTION
**Pull request by loicgasser**
I don't even know why we have that but it's BAD.

### CODE REVIEW

**Comment by loicgasser** [comment]
Build error related to https://github.com/geoadmin/mf-chsdi3/issues/1969

**Comment by gjn** [comment]
Interesting. If bad, we should remove the function from the helper library.

I've noticed a small difference between in-build round function and helper round.

round(-1.5) = -2.0
helper.round(-1.5) = -1.0

But it's only affecting negative numbers that are exactly -x.5.

**Comment by loicgasser** [comment]
I saw that but I don't see the use case where altitudes would be negative. I believe that this is quite bad indeed.

**Comment by gjn** [comment]
Agree.

Conflicts now with merged PR. Sorry about that.

Should we remove the round function from the helper library?

**Comment by loicgasser** [comment]
yes I rebase now

**Comment by loicgasser** [comment]
done

**Pull request merged**
