### PR TITLE
do not test htmlpopup for aggregated layer

### PR DESCRIPTION
**Pull request by ltclm**
only parent layers are tested, analogous to other tests

### CODE REVIEW

**Comment by ltclm** [comment]
will solve buildout problem like this one: https://github.com/geoadmin/mf-chsdi3/pull/1514

**Comment by ltclm** [comment]
@loicgasser thanks for support with this buildout issue

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
same error occurs did it work when running nosetests locally? Could you try to do all tests in TestMapServiceView?

**Comment by ltclm** [comment]
yes, there is a prod layer without model because the pr https://github.com/geoadmin/mf-chsdi3/pull/1514 is pending.
I have set the layers staging to int and deployed the bod.
Should work now.

Probably the nosetests staging should be definable by parameter instead of using always using 'prod'.

**Comment by ltclm** [comment]
jenkins test

**Pull request merged**
