### PR TITLE
Update ol to v3.6.0 - adapt api3 examples

### PR DESCRIPTION
**Pull request by kandre**
Update ol3.6.0

[Test link](http://mf-chsdi3.dev.bgdi.ch/kan_update_ol_3.6)

### CODE REVIEW

**Comment by oterral** [comment]
Test link please

**Comment by gjn** [comment]
We also need an official test link for our api users to adapt their applications before we merge and deploy this. We need to inform the list about this. See https://github.com/geoadmin/mf-chsdi3/issues/1423

@oterral Could you take care of this while I'm in holidays?

**Comment by oterral** [comment]
sure

**Comment by oterral** [comment]
Will be merged when preview mode will be removed

**Pull request merged**
