### PR TITLE
fixes astra schwerunf

### PR DESCRIPTION
**Pull request by AFoletti**
Uses integer for population instead or real.
A change in the DB was also needed and is being pushed to INT just now

### CODE REVIEW

**Comment by gjn** [comment]
LGTM. I'll merge once jenkins is happy and then I'll deploy to integration.

**Comment by daguer** [comment]
It was not a good idea to modify this code.
The separators of thousands do not appear any more...

**Comment by gjn** [comment]
@mariokeusen Can we live without the thousand separators?

**Comment by gjn** [comment]
@daguer When doing something as specific as this, I would be great to add a comment in code so we can understand better why it was done.

**Comment by mariokeusen** [comment]
When we are talking about the "population" field, then yes, we could live without the thousand separator, because they are simply not present in the data source. But I saw on INT that we have some thousand separators.

**Comment by gjn** [comment]
Yes, we fixed it :)

**Pull request merged**
