### PR TITLE
Remove legacy targets

### PR DESCRIPTION
**Pull request by loicgasser**
@gjn Any reason not to? If not please merge as I think it makes no sense anymore.

### CODE REVIEW

**Comment by gjn** [comment]
Depends on ogcproxy.

We originally put ogcproxy onto legacy instances to avoid troubles that
it might cause. The standard apache congestion that might happen if a
service uses up all apache connections. If I remember correctly, we had
this a couple of times with ogcproxy as well (hence, we moved it).

Are we all sure it's a good idea to move ogcproxy back to mf instances 
that
contain all our other services?

@procrastinatio @oterral ?

**Comment by loicgasser** [comment]
Ogc proxy won't disappear unless we remove the vhost.
I don't think it s used as much, we can analyze it though. We should finish this separation and not remain half way through.

**Comment by gjn** [comment]
There was a reason for separation of ogcproxy. If this reason is still there, we should not put it on the instance where other important services are run.

The reasons are old and might not apply today - so this I can't tell.

**Comment by gjn** [comment]
Btw: ogcproxy is still pointing to legacy instance. I propose to switch and hope we don't have any congestion anymore.

@procrastinatio Could you have a look at the ogcproxy code and try to avoid 'long' requests? Maybe head request first to determine possible size?

**Comment by procrastinatio** [comment]
@gjn How do you detect long request ? You have no way to know if a server is slow or not.

@loicgasser @gjn Yes, the goal was to switch, but I don't like to push **too many** changes at the same time in varnish. But maybe, it is an effect of old age...

**Comment by gjn** [comment]
We can wait with the varnish switch. ogcproxy runs on the legacies anyway.

ELK could be used to analyse response times.

We could improve the ogcproxy service in that we check for content-length (HEAD request) on the external resource and define some limit (20MB? 50MB?). Then only proxy content which is lower to that limit. This will likely help a ton in avoiding long response times for large resources.

**Pull request merged**
