### PR TITLE
[ON HOLD] Update iframe example

### PR DESCRIPTION
**Pull request by oterral**
Update for https://github.com/geoadmin/mf-geoadmin3/pull/3164

[Test](http://mf-chsdi3.dev.bgdi.ch/teo_postmtest/examples/geoadmin_iframe.html)

### CODE REVIEW

**Comment by loicgasser** [comment]
LGTM in geoadmin and CHSDI but this may potentially break http://www.hydrodaten.admin.ch/

@davidoesch Can you warn hydroweb people to support per default 
https://github.com/geoadmin/mf-chsdi3/pull/1928/files

and also the old behaviour until we deploy a new version of CHSDI please?

**Comment by davidoesch** [comment]
@loicgasser do not push this to production BEFORE we got an OK from BAFU that they tested it. @mariokeusen : can you provide BAFU this testlink so they can check this feature (it will later on as well make the tooltip not necessary anymore, and later enhance as well the communication between iframe and cms - one of the open points we had with tom)

**Comment by loicgasser** [comment]
@davidoesch yes of course that's why I contacted you. Here is a test link: they simply need to change the host. I think that the best for them is to support both temporarly. [Test Host](https://mf-geoadmin3.int.bgdi.ch/fix_3146/)

**Comment by gjn** [comment]
This is an interface that we need to keep stable in the future. So we should really put some effort into it to get it right.

**Comment by loicgasser** [comment]
Not relevant anymore as examples are on codepen now and we decided to use antoher approach

**Pull request closed without merging**
