### PR TITLE
new legends 4 aviatik

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Comment by rebert** [comment]
[try](https://mf-chsdi3.dev.bgdi.ch/ltrea_legends_aviatik/shorten/87f3bc9e59)

**Comment by ltclm** [comment]
we have limited the with of legend images to 480px
if you need bigger legends create two versions
one resampled to width 480px
and the original version.
naming convention:
ch.swisstopo.swisstlm3d-strassen_de_big.pdf
ch.swisstopo.swisstlm3d-strassen_de.png

@mariokeusen @AFoletti is the legend width limitation to 480px still a must?

**Comment by AFoletti** [comment]
@ltclm it is to my knowlegde.
Those look like good candidates for a "_big" legend to me

**Comment by rebert** [comment]
I'm going to start gimp

**Comment by ltclm** [comment]
the _big version has to be a pdf

**Comment by rebert** [comment]
for lang in de fr it en rm; do convert ch.bazl.segelflugkarte_${lang}.png -resize 480 ch.bazl.segelflugkarte_${lang}.png; done

**Comment by rebert** [comment]
@ltclm thanks for your feeback. Should be ok now

**Pull request merged**
