### PR TITLE
Regrouping layers shop

### PR DESCRIPTION
**Pull request by pfanguin**
[Test link](https://mf-geoadmin3.dev.bgdi.ch/ltfap/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Ffap_shop_new_sym&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.wanderkarte50_papier.metadata,ch.swisstopo.landeskarte50_papier.metadata,ch.swisstopo.landeskarte25_papier.metadata,ch.swisstopo.luftfahrtkarten-icao_papier.metadata,ch.swisstopo.landeskarte100_papier.metadata&X=203542.93&Y=752973.51&zoom=0)

[Issue : #2324](https://github.com/geoadmin/mf-chsdi3/issues/2324)

### CODE REVIEW

**Comment by pfanguin** [comment]
jenkins test

**Comment by pfanguin** [comment]
jenkins test

**Comment by loicgasser** [comment]
@pfanguin 

Can you use the same structure as in https://github.com/geoadmin/mf-chsdi3/issues/2323 ?

So that we can track the changes and post deploy tasks please?

Link all the PRs in one ticket and so on, otherwise we're gona loose it next week.

**Comment by pfanguin** [comment]
Test link updated

**Comment by loicgasser** [comment]
build error unrelated (catalog update)

**Pull request merged**
