### PR TITLE
switch gisgeol pdf source to s3, remove zadara/efs helpers and tests

### PR DESCRIPTION
**Pull request by ltclm**
this pr will move the datasource of gisgeol pdf downloads from efs to s3
the auto sync of the pdf's is already in working. the files and their size are written to a postgres table now [1].
the views are already prepared on dev, int and prod.

[Testlink](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fdev_ltclm_gisgeol_2_s3&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers_timestamp=&layers=ch.swisstopo.geologie-gisgeol-punkte&X=130675.37&Y=640473.78&zoom=7)

[1] https://github.com/geoadmin/bgdi-scripts/commit/162d35b847042dd228a2b86f2f95eb23de3ec7b0

### CODE REVIEW

**Comment by ltclm** [comment]
@mariokeusen this pr will switch the source of gisgeol pdf's to s3 in the tooltips.
auto sync scripts have been adapted already.

**Comment by gjn** [comment]
This is good for me. GisGeol the only data we used for this? In logs, I didn't find anythign else, but who knows for sure?

**Comment by ltclm** [comment]
yes, we only have these pdfs for the tooltips.

**Comment by gjn** [comment]
We can then unmount the downloads directory, as it's not needed anymore.

**Comment by ltclm** [comment]
the download directory is part of the geodata efs mount, i would keep this attached (for profile updates).

**Comment by gjn** [comment]
right. Just delete the directory in the EFS then.

**Comment by ltclm** [comment]
download folder in efs has been deleted and removed from sync scripts.

**Pull request merged**
