### PR TITLE
Add models, makos and translations for sem sachplan asyl

### PR DESCRIPTION
**Pull request by Sgachet**

### CODE REVIEW

**Comment by Sgachet** [comment]
[test link](https://mf-chsdi3.dev.bgdi.ch/gas_sem_sachplan/shorten/76f52fcced)

**Comment by loicgasser** [comment]
LGTM
I need you to remove the WIP if ok, give me the deploy date and rebase your branch.

`git rebase master`
`make translate`
`git add -A`
`git rebase --continue`
`git push origin +gas_sem_sachplan`

**Comment by Sgachet** [comment]
@loicgasser  Still in WIP for the moment. 
I'm waiting for the feedback of Mario and the DatenHerr
**Deploy on 6.12**.

I rebase the branch now

**Comment by loicgasser** [comment]
@Sgachet Are you sure about the symbology ? Green point is still visible when you zoom in.
screenshot from 2017-12-01 11-37-11

**Comment by Sgachet** [comment]
Yep it's correct, 
The point is the facility and the polygon the planning measure.

**Comment by loicgasser** [comment]
ok thks

**Pull request merged**
