### PR TITLE
[WIP] Mapproxy: deal with mixed type of PNG sources

### PR DESCRIPTION
**Pull request by procrastinatio**
This PR is a quick fix for https://github.com/geoadmin/mf-chsdi3/issues/1680 (mixed type of PNGs)

I don't see any configuration only solution, as Mapproxy knows only of type of PNG and does a lots of black magick to detect the `right type`:

Compare [Single tile](http://mf-chsdi3.dev.bgdi.ch/mom_no_quantize/mapproxy/wmts/1.0.0/ch.swisstopo.vec25-eisenbahnnetz_20090401/default/20090401/epsg_2056/17/5/6.png) and [All layer](http://mf-chsdi3.dev.bgdi.ch/mom_no_quantize/examples/ol3_lv95_all.html?layer=ch.swisstopo.vec25-eisenbahnnetz&timestamp=20090401&format=png&base_url=http://mf-chsdi3.dev.bgdi.ch/mom_no_quantize)

with the [defect one](http://mf-chsdi3.prod.bgdi.ch/mapproxy/wmts/1.0.0/ch.swisstopo.vec25-eisenbahnnetz_20090401/default/20090401/epsg_2056/17/5/6.png)

The cleaner solution howerver should be not to mix PNG in the source.
And the cleanest, not reproject tiles from source we have the original vector data in a WMS!

Note: This is using a custom Mapproxy version for now. Waiting PR https://github.com/mapproxy/mapproxy/pull/197  be merged into master.

### CODE REVIEW

**Comment by procrastinatio** [comment]
@ltclm @AFoletti Converting PNG to 8 bit is fine for tiles from vector layer, but less for transparent PNG like geological maps, etc.  How do I know which layer have to be `optimized`and which have not ?

**Comment by procrastinatio** [comment]
You may close this PR as this PR https://github.com/geoadmin/mf-chsdi3/pull/1690 is better.

But my [comment](https://github.com/geoadmin/mf-chsdi3/pull/1685#issuecomment-143969381) is still valid

**Comment by cedricmoullet** [comment]
@procrastinatio do we have layers with Transparent greyscale ('LA') ? What happens in this case ? Empty tile ?

**Comment by procrastinatio** [comment]
@cedricmoullet  Yes we have layers which are completely or partially transparent greyscale (See https://github.com/geoadmin/mf-chsdi3/pull/1672).
If a tile is greyscale, it is simply returned as is, with no further optimisation (see my PR in Mapproxy)

**Comment by cedricmoullet** [comment]
ok, thanks

**Comment by procrastinatio** [comment]
Bot `vpc-caching-proxy-prod` caches also flushed.

**Pull request closed without merging**
