### PR TITLE
fixed units

### PR DESCRIPTION
**Pull request by AFoletti**
hotfix for MM on monday

### CODE REVIEW

**Comment by gjn** [comment]
@loicgasser @AFoletti Please take care of the emergency deploy on monday. As master has been updated since last deploy, I propose to create a branch based on latest release tag and apply this patch and deploy the branch.

Also, mf-geoadmin3 would need to be re-deployed to invalidate the cache (assure a new version is created).

Ok?

**Comment by AFoletti** [comment]
BOD has not changed, so we can use the last snapshot

**Comment by loicgasser** [comment]
@chsdi tooltips are not cached in geoadmin.
No need to deploy geoadmin, if BOD has not changed.

Just chsdi and with the lubis fix, why not?
I am tempted to deploy now.

**Comment by loicgasser** [comment]
@gjn CHSDI on int. Snapshot is: **201704281531**
I'd rather have the lubis fix as well. not much as changed and it will also fix some translations for BAZL.
https://github.com/geoadmin/mf-chsdi3/issues/2538

**Comment by gjn** [comment]
No deploys on friday.

Deploy of geoadmin is needed because we need to change the application version. The application version is used to created cached requests to our api, e.g. https://api3.geo.admin.ch/1704261351/rest/services/ech/MapServer/ch.bfe.statistik-wasserkraftanlagen/202430/htmlPopup

The number after the domain is the application version. All versioned requests are cached 1 year.

**Comment by loicgasser** [comment]
> No deploys on friday.

No I won't

> Deploy of geoadmin is needed

Yes you're right, but Varnish doesn't cache much

> I insisted on being able to re-deploy a snapshot with a new version...

And you got it, DEEP_CLEAN=true ...

**Comment by gjn** [comment]
Thanks for deploying on Monday!

Varnish is not the only thing caching stuff. Other proxies (BIT proxy) and clients/browsers do as well.

We could discuss giving up this mechanism, so things like these don't need deploy of map.geo (I don't really like it myself). Maybe let api3 define it's own version and the map should use that. So before first api request where caching is wanted, the map asks for latest version to use (api3.geo.admin.ch/currentversion) and will use that for all requests. Would be best of both worlds, I guess.

**Comment by loicgasser** [comment]
Yes, that could be an option.
Do you want me to deploy geoadmin with the new cache headers for index.html ?

**Comment by AFoletti** [comment]
As info: MM is at 10:00 monday morning.

**Pull request merged**
