### PR TITLE
Revert "Update haltestellen-oev legends"

### PR DESCRIPTION
**Pull request by ltclm**
Reverts geoadmin/mf-chsdi3#1802

sorry, this is not for tomorrow's deploy.

### CODE REVIEW

**Comment by AFoletti** [comment]
there is no deploy today. I think this PR is useless

**Comment by gjn** [comment]
@ltclm ?

**Comment by ltclm** [comment]
If there is a deploy this week, then please revert.

**Comment by gjn** [comment]
@ltclm Is this still relevant?

**Comment by ltclm** [comment]
no, this one can be deleted.

**Pull request closed without merging**
