### PR TITLE
Ltfoa update bikesharing

### PR DESCRIPTION
**Pull request by AFoletti**

### CODE REVIEW

**Comment by AFoletti** [comment]
jenkins test

**Comment by AFoletti** [comment]
jenkins test looks unrelated to this layer (ch.pronatura.waldreservate fails)

**Comment by AFoletti** [comment]
jenkins test

**Comment by AFoletti** [comment]
@IGEB: please merge me; I'm neede for today's deploy!

**Comment by loicgasser** [comment]
@procrastinatio @rebert I merge this it's for today.

**Pull request merged**
