### PR TITLE
Updated Notruf 112, 117, 118

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Comment by ltclm** [comment]
@faselm is this for this weeks deploy?
If yes tag with milestone.

**Comment by faselm** [comment]
It's not for this week, it has been postponed to September for now...

**Comment by faselm** [comment]
Test link for this new layer: https://mf-chsdi3.dev.bgdi.ch/ltfas_notruf/shorten/8b0419a499

**Review by ltclm — APPROVED** [review]
rebased

**Pull request merged**
