### PR TITLE
Fix geometryType when returnGeometry is set to false

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-chsdi3/issues/2086

In this PR I also fixed the tests that broke due to data changes.

### CODE REVIEW

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
+1.

**Comment by loicgasser** [comment]
ping @oterral to ensure backward compatibility

**Comment by gjn** [comment]
Adaptions to front-end needed?

**Comment by loicgasser** [comment]
seems ok in shop https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/shop/ShopDirective.js#L82
Where I think it's the only location where we use returnGeometry=False

I could not find anything else, just wanted to be sure.

**Pull request merged**
