### PR TITLE
WMTS: add new Tilematrixset 17,19,24

### PR DESCRIPTION
**Pull request by ltclm**
this pr is adding new tilematrixset:  17 19 24

### CODE REVIEW

**Comment by procrastinatio** [comment]
OK, for the WMTS GetCapabilities part, it looks good. I am testing with various clients. We probably also need to reconsider the tilematrix for these layers in the reprojected WMTS tiles.

**Comment by procrastinatio** [comment]
@ltclm I a going to extent the test for WMTS GetCapabilities to document excatly what we want and to make sure we do not break anything:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/tests/integration/test_wmtscapabilities.py

**Comment by cedricmoullet** [comment]
@ltclm is it still a WIP ?

**Comment by procrastinatio** [comment]
OK, you may merge.

**Pull request merged**
