### PR TITLE
[WIP] Update symbology

### PR DESCRIPTION
**Pull request by alcapat**
Need to regenerate tiles before to merge this PR.

### CODE REVIEW

**Comment by gjn** [comment]
@alcapat Is this for tomorrow?

**Comment by alcapat** [comment]
@gjn : sorry, no it's not for today. We wait (for a long time) the AP before to generate new tiles and update the legend.

**Comment by gjn** [comment]
@alcapat Is this ready for deploy on 27.4?

**Comment by alcapat** [comment]
Forget this PR. Datenherr want to send a new delivery

**Pull request closed without merging**
