### PR TITLE
Add tooltip for ch.swisstopo.treasurehunt

### PR DESCRIPTION
**Pull request by Ariadnigaki**
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltgar_treasurehunt&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.treasurehunt&wms_url=%2F%2Fwms-bgdi.dev.bgdi.ch%2Fltgar&X=122815.90&Y=510429.83&zoom=12)

### CODE REVIEW

**Comment by AFoletti** [comment]
I get an error when trying the tooltip. Could you please check?

**Comment by Ariadnigaki** [comment]
Yes i am working on that. I will inform you as soon as i figure it out.

**Comment by Ariadnigaki** [comment]
@AFoletti could you please check again? I forgot to add the attribute type_coord to the model, so the tooltip was not working. I changed also the legends and instead of hint, it is written link now.

**Comment by AFoletti** [comment]
thanks for the fixes.
It's minor, but could you please make the legends background transparent as per standards?

**Comment by loicgasser** [comment]
please make the legend transparent as well.

**Comment by AFoletti** [comment]
ok, thanks for the images.
I have a last issue: please implement a zoomlevel limit for the tooltip. At the moment, you can get the tooltips even when the symbols are not displayed

**Comment by loicgasser** [comment]
Thanks for the update @Ariadnigaki

**Pull request merged**
