### PR TITLE
Data ltfoa suel

### PR DESCRIPTION
**Pull request by AFoletti**
ready for review.
Layers has to be on prod on 03.06

### CODE REVIEW

**Comment by AFoletti** [comment]
Has do be deployed on 03.06.2015

Wait for merge. New legends pending

**Comment by loicgasser** [comment]
Nice comment I like it! ;)

**Comment by AFoletti** [comment]
Definitive legends are pushed.
This branch is ready to be merged

**Comment by procrastinatio** [comment]
Legend [Kraft](http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bfe.sachplan-uebertragungsleitungen_kraft/legend) OK

Legend [Anhoerung](http://mf-chsdi3.dev.bgdi.ch/ltmom/rest/services/ech/MapServer/ch.bfe.sachplan-uebertragungsleitungen_anhoerung/legend) not OK ?

I did not test the tooltips though.

**Comment by AFoletti** [comment]
the "Anhoerung" layer is not present in ech catalog, thus the nonfunctioning legend

**Pull request merged**
