### PR TITLE
Update swisstlm3d legends and big pdf

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by gjn** [comment]
Transparent backgrounds?

**Comment by daguer** [comment]
I made as it is now because there is a link to big pdf...
transparent is needed in this case?!?

**Comment by daguer** [comment]
I'm not sure at all it's necessary, but the legends are now transparents...

**Comment by gjn** [comment]
I think the width are too big. Don't we have limit of 420px?

I'll merge for deploy today, but this might need adaption.

**Pull request merged**
