### PR TITLE
Fix getcap pointing to TOD

### PR DESCRIPTION
**Pull request by loicgasser**
does this makes any sense to anybody? Why do we have that?
Fix for https://github.com/geoadmin/service-proxywms/issues/150

### CODE REVIEW

**Comment by procrastinatio** [comment]
@loicgasser mapproxy was used to provide a WMTS from a WMS.

**Comment by loicgasser** [comment]
yes I guess this makes sense from a MapProxy point of view.

**Comment by loicgasser** [comment]
But this means that it probably didn't work in the JS API as well.

**Comment by gjn** [comment]
+1

**Pull request merged**
