### PR TITLE
[WIP] Update layer ch.swisstopo.treasurehunt

### PR DESCRIPTION
**Pull request by Ariadnigaki**
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltgar&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.treasurehunt,ch.swisstopo.zeitreihen&X=157752.80&Y=512418.52&zoom=13&layers_timestamp=,18641231&layers_visibility=true,false&wms_url=%2F%2Fwms-bod.dev.bgdi.ch%2Fltgar_treasurehunt_new%2Fxx%2F)

### CODE REVIEW

**Comment by AFoletti** [comment]
LGTM!
Could you please prepare an INT link and integrate it into the JIRA ticket? Once done, I'll send it to the customer

**Comment by Ariadnigaki** [comment]
Yes, sure!

**Comment by loicgasser** [comment]
@AFoletti I think you need to take care of that yourself or give it to someone else.

**Comment by oterral** [comment]
ping @AFoletti do we close or do you take care of it? What should be done?

**Comment by AFoletti** [comment]
Sorry, this is old and no more needed

**Pull request closed without merging**
