### PR TITLE
Add layer ch.swisstopo.geologie-dosisleistung-terrestrisch

### PR DESCRIPTION
**Pull request by alcapat**
Update stopo model, add new mako, add legend for ch.swisstopo.geologie-dosisleistung-terrestrisch and update translations

### CODE REVIEW

**Comment by gjn** [comment]
Can a dataintegrator review/test this?

**Comment by daguer** [comment]
Review was made in my environment, everything is OK!

**Comment by cedricmoullet** [comment]
Could you please rebase ?

**Comment by alcapat** [comment]
rebase done

**Pull request merged**
