### PR TITLE
change lfh datasource to view with new attribute activesince

### PR DESCRIPTION
**Pull request by ltclm**
adds a new attribute for attribute search ``bgdi_activesince``
its in a new view, and it has always the newer date of the the table attributes ``constructionConfirmed``and ``startofConstruction``

see https://jira.swisstopo.ch/browse/BGDIDI_KB-872

[Testlink](https://mf-chsdi3.dev.bgdi.ch/dev_ltclm_lfh/shorten/7fce83f29b)

automated fme workbench, table and view on _master, _dev, _int, _prod have been updated already.
This can be published only by merging and deploying this code .

### CODE REVIEW

**Comment by ltclm** [comment]
mf-geoadmin3 needs some changes too

**Comment by ltclm** [comment]
testlink has been updated, fixed mf-geoadmin is used.

**Comment by ltclm** [comment]
waiting for feedback @mariokeusen

**Comment by mariokeusen** [comment]
Feedback given in jira. Looks all good except one little translation

**Pull request merged**
