### PR TITLE
decommission vec25 layer, replaced by tlm3d layer

### PR DESCRIPTION
**Pull request by alcapat**
Decommission of 4 layers vec25 [1] replaced by 4 new tlm3d layer [2]

Following the procedure describe here: https://ltwiki.adr.admin.ch:8443/display/BGDI/99_RM_LAYER

[1]
ch.swisstopo.vec25-gewaessernetz
ch.swisstopo.vec25-strassennetz
ch.swisstopo.vec25-eisenbahnnetz
ch.swisstopo.vec25-uebrigerverkehr

[2]
ch.swisstopo.swisstlm3d-uebrigerverkehr
ch.swisstopo.swisstlm3d-gewaessernetz
ch.swisstopo.swisstlm3d-eisenbahnnetz
ch.swisstopo.swisstlm3d-strassen

### CODE REVIEW

**Comment by alcapat** [comment]
Can be done for the deploy of 11.102.2017

**Comment by loicgasser** [comment]
next week? yes.

You can already decomssion the layer from geocat_data, dataset. The rest should automatic.
Please decomission, mapfile_include. WMS

**Comment by loicgasser** [comment]
please remove legends and entries from BOD if not already done. ping @alcapat

**Comment by alcapat** [comment]
Jenkins test

**Comment by alcapat** [comment]
Entries removed on table dataset.
Legends remove too.
@loicgasser if possible, please merge this PR for the next deploy of 25.10.2017

**Pull request merged**
