### PR TITLE
Switch to new unified db cluster

### PR DESCRIPTION
**Pull request by gjn**
This will adapt to new db cluster. Most configs don't work yet because
    - pg.bgdi.ch does not exist yet
    - staging specific db's in cluster  do not exist yet (Marcel will create them)
Once this works, we can use ths PR/branch to test the new setup

With my configuration (using on slave ip address and exising db names), [it seems to be working fine](http://mf-geoadmin3.dev.bgdi.ch/ltjeg/).

Merge only after everything is ready!

TODO/Verify:
- [ ]  Demo instance setup -> @AFoletti 
- [ ] Where to run our automated nosetests/tests (we should not hit standard slaves for this...)

### CODE REVIEW

**Comment by ltclm** [comment]
the staging specific databases in the cluster have been created / copied from master,dev,int,prod.
for each database you will find the following databases:
```sql
...
stopo_master    -- do not use this one in any application, will be updated with fme, ogr, etc.
stopo_dev       -- staging dev
stopo_int       -- staging int
stopo_prod      -- staging prod
...
```
since the elb is not yet ready, you have to use one of the slaves ip addresses instead.

**Comment by gjn** [comment]
Cool. Let me know when the official adress is working.

**Comment by ltclm** [comment]
the official adress is now working but the file /var/www/.pgpass has not yet been updated.

**Comment by gjn** [comment]
When will this be done?

**Comment by ltclm** [comment]
as soon as the new db infra is available we will deploy the cw applications.
We will switch the automatic data updates and fme scripts on  13.04.2015.
From that date the old db infra will be still available but not updated anymore.
WMS and MF Projects should be deployed after that date.

**Comment by ltclm** [comment]
The entries in the pgpass file have been added.
You can access the slaves via elb, fqdn or ip.

**Comment by gjn** [comment]
We'll see. jenkins test.

**Comment by gjn** [comment]
Works well. Now we only need the test slave instance behind an url (pg.test.bgdi.ch?) for dev/int and to run nosetests on.

**Comment by procrastinatio** [comment]
Removing the _staging_ level is another PR ?

**Comment by gjn** [comment]
Staging level in the bod? or stating level of db's? (bod_dev, bod_int, bod_prod)

**Comment by ltclm** [comment]
could you provide a test link with pg.bgdi.ch?

**Comment by gjn** [comment]
Yes, I will today.

Does the test slave instance exist? Is there an DNS for it?

**Comment by ltclm** [comment]
Yes the backup slave is ready, We will setup pg-backup.bgdi.ch for this instance, 
please use it's ip address 10.220.4.239 for now. 
The corresponding entry in the pgpass exists.

**Comment by AFoletti** [comment]
@gjn : do you still need a demo instance for this task?

**Comment by gjn** [comment]
Never needed a demo instance. But we need to adapt/review the settings for the demo instances.

**Comment by gjn** [comment]
Testlink: mf-chsdi3.dev.bgdi.ch/gjn_new_dbsetup

Uses pg.bgdi.ch and *_dev db's.

**Comment by gjn** [comment]
We'll do the switch for dev/int to the backup slave instance right after the deploy.

**Comment by loicgasser** [comment]
You could simplify that a lot I think. What about only declaring a variable db_staging:

in buildout_dev:

db_staging = dev

in buildout_int:

db_staging = int

in buildout_prod:

db_staging = prod

and in developement.ini.in:

`sqlalchemy.are.url = postgresql://${vars:dbhost}:${vars:dbport}/are_${vars:db_staging}` ?

What do you think?

It needs rebase as well.

**Comment by gjn** [comment]
You are right, it would be much less 'code'.

I did it this way in anticipation that we might, in the future, change a little our db aproach. Instead of having staging db's, we could/would have dev/branch db's. To develop a new feature, we would have bod_new_feature, to have a fixed release, we would have bod_r20150422, or to have a demo db we would have are_demo_something...which would not be possible with the above. But I might have been too early, as this needs discussions in plenum.

I'll adapt to your proposal.

**Comment by gjn** [comment]
Should work now as switch is complete. jenkins test.

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
once more. I think failure was just a glitch. jenkins test.

**Pull request merged**
