### PR TITLE
[WIP] Get the total number of features of an identify request

### PR DESCRIPTION
**Pull request by oterral**
For https://github.com/geoadmin/mf-geoadmin3/pull/2143

Add a maxFeatures paramater to the identify request and add the number of features available for this request in the response.

Still limited to 10000 features.

### CODE REVIEW

**Comment by gjn** [comment]
How does this perform on big layers (e.g wohnungsregister?)

**Comment by oterral** [comment]
Not good :)  I have tested with luftbilder

**Comment by oterral** [comment]
a "Show the next 200 results" button should be better

**Comment by gjn** [comment]
Hmm. @mariokeusen do we need to know a) how many features we really have, or is it enough to b) know that there are more feaures?

If b) is enough, we could make a maxlimit query of 201, return 200 results and indicated if 201 were found. Then next query with offset, etc. This might perform considerably better.

**Comment by cedricmoullet** [comment]
I also think that Gilbert's proposal makes sense

On Tue, Feb 10, 2015 at 8:37 AM, Gilbert Jeiziner <notifications@github.com>
wrote:

> Hmm. @mariokeusen <https://github.com/mariokeusen> do we need to know a)
> how many features we really have, or is it enough to b) know that there are
> more feaures?
>
> If b) is enough, we could make a maxlimit query of 201, return 200 results
> and indicated if 201 were found. Then next query with offset, etc. This
> might perform considerably better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-chsdi3/pull/1263#issuecomment-73656475>.
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by oterral** [comment]
Out of date with #1266

**Pull request closed without merging**
