### PR TITLE
[WIP][MVT] cleaned up mvt branch

### LINKED ISSUE #3066: create a new clean branch based on mvt branch for support of /gl-styles
the old mvt branch is not up to date with master, webmercator is already merged.

please make a PR that uses the refactoring done in [mvt branch](https://github.com/geoadmin/mf-chsdi3/pull/3005), and test.

After this is done, use this branch in geoadmin3:mvt branch (PR)

### PR DESCRIPTION
**Pull request by boecklic**
this PR replaces PR #3005 and resolves #3066 
branch `mvt_clean` is based on recent master (70efc81e149c3c343cd42daa572d3e20a03ca434) with cherry-picking 4 glstyles related commits from #3005. If new upstream changes from master should be incorporated in this branch, it should be `rebased` on `master` instead of merging upstream `master` into `mvt_clean`.

### CODE REVIEW

**Comment by boecklic** [comment]
I tested: 

- [x] create drawing, share -> open in new browser
- [x] edit shared drawing, share again -> open in new browser
- [x] adapt style, export
- [x] adapt style, share -> open in new browser
- [x] adapt style, make drawing, share -> open in new browser (drawing and adapted style are considered)

Are there other features that should be tested that I have missed? Implementation/refactoring could be cleaner and more generic, but seems to work.

**Comment by procrastinatio** [comment]
Tested style saving and loading with: https://mf-geoadmin3.int.bgdi.ch/mvt/index.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmvt_clean
I've goat an `Acceess denied` when reloading the style

**Comment by danduk82** [comment]
@rebert, @procrastinatio, @Sgachet, @ltclm , please ensure that we test well tomorrow that KML is still working as expected.
- [ ] load a kml precendent to this modification, edit, and save
- [ ] measure tool
- [ ] point features
- [ ] polyline
- [ ] save and load

**Comment by procrastinatio** [comment]
N.b. If you use `api_url` please note that there is no way to configure the bucket you are using. On `int` it will use the `int`bucket, even if the file service writes in the `dev` bucket because you are using `api_url=//mf-chsdi3.dev.bgdi.ch`

**Pull request merged**
