### PR TITLE
Remove unused model and translation

### LINKED ISSUE #2278: Tiled WMS + drucken
**Tiled WMS**

https://map.geo.admin.ch/?X=199374.98&Y=599258.47&zoom=5&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.astra.unfaelle-personenschaeden_alle&layers_timestamp=

--> no print

**Non tiled WMS**

https://map.geo.admin.ch/?X=199374.98&Y=599258.47&zoom=5&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7CUnf%C3%A4lle%20mit%20Personenschaden%7C%7Chttps:%2F%2Fwms.geo.admin.ch%2F%7C%7Cch.astra.unfaelle-personenschaeden_alle%7C%7C1.3.0

--> print OK

### PR DESCRIPTION
**Pull request by kandre**
This PR fixes [#2278 in mf-geoadmin3](https://github.com/geoadmin/mf-geoadmin3/issues/2278)

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@kandre could you chek the tests ?

**Comment by kandre** [comment]
test_all_htmlpopups fails because the layer still exists in the DB on dev. Deploying the DB on dev will fix that.

**Comment by kandre** [comment]
jenkins

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
It migth it be the same as @procrastinatio said in #1371? 

I get this:

======================================================================
ERROR: test_all_htmlpopups (chsdi.tests.integration.test_mapservice.TestMapServiceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_mapservice.py", line 434, in test_all_htmlpopups
    model = models_from_name(layer)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

======================================================================
FAIL: test_all_legends_images (chsdi.tests.integration.test_mapservice.TestMapServiceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_mapservice.py", line 417, in test_all_legends_images
    self.failUnless((layer + '_' + lang) in legendImages, layer + lang)
AssertionError: ch.bfe.windenergieanlagende

**Comment by oterral** [comment]
jenkins test

**Comment by kandre** [comment]
The staging of ch.bfe.windenergieanlagende is on test, hope it will pass now

**Comment by procrastinatio** [comment]
jenkins test

**Comment by procrastinatio** [comment]
@kandre, yes genau. I mean, it is no fair... Every changes in DB breaking code should also be punished ;-)

**Comment by kandre** [comment]
I am sure I could have done it ;)

**Comment by loicgasser** [comment]
What about the tooltip and associated translations? templates/htmlpopup/emissionplan.mako

A little `git grep` would ensure that we remove all we need without breaking existing things. Otherwise LGTM.

**Comment by kandre** [comment]
[Test Link](http://mf-geoadmin3.dev.bgdi.ch/kan_chsdi_branch/?X=190000.00&Y=660000.00&zoom=1&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.laerm-emissionsplan_eisenbahn_tag), linked to this PR chsdi [branch](http://mf-chsdi3.dev.bgdi.ch/kan_remove_unused_model_and_translation) after uneeded translations removal.

**Comment by gjn** [comment]
I think you should also remove the associated legend images:
`chsdi/static/images/legends/ch.bav.laerm-emissionplan_eisenbahn_2015_XX.png`

**Comment by kandre** [comment]
Right, it is missing

**Comment by gjn** [comment]
Thanks alot for this.

**Pull request merged**
