### PR TITLE
[WIP] Update tooltip info according DIF

### PR DESCRIPTION
**Pull request by alcapat**
DIF available here: M:\Org\5-KOGIS\51-BGDI\5103-Geobasisdaten\5103-04-Originaldaten\5103-04-03-bund-bafu\20171005_ch.bafu.bundesinventare-hochmoore

Need display the type with a label (not a integer value like before).
The label is available in 3 languages (de, fr ,it)
Add new info "Description", also available in 3 languages.

Table bundinv.hm updated with new necessary attributs
Prepare sphinx search config

### CODE REVIEW

**Comment by loicgasser** [comment]
Is this still WIP? LGTM for me at this point.

**Comment by loicgasser** [comment]
And pleeeeasse. deploy date!

**Comment by AFoletti** [comment]
22.11

2017-11-17 15:41 GMT+01:00 Gasser Loïc <notifications@github.com>:

**Comment by AFoletti** [comment]
Is this part of the bundesinventare package? If so, it should go live on 06.12

**Comment by nadine-piveteau** [comment]
I considered your changes in #2717 . Thanks for that! In my opinion, this PR is not necessary anymore.

**Pull request closed without merging**
