### PR TITLE
ltmbr Update bfs-renewableheating

### PR DESCRIPTION
**Pull request by marionb**
Here the test link
https://mf-chsdi3.dev.bgdi.ch/ltmbr_update_bfs-renweableheating/shorten/903f3edd70

### CODE REVIEW

**Comment by faselm** [comment]
Do you have a test link?

**Comment by marionb** [comment]
@faselm Sorry I missed to add the link, here it is: https://mf-chsdi3.dev.bgdi.ch/ltmbr_update_bfs-renweableheating/shorten/903f3edd70

**Review by rebert — APPROVED** [review]
LGTM: but the the legend text seems to be quite big... but the customer decides...

**Review by ltclm — APPROVED** [review]
new attribute website does not appear in htmlpopup, but that might be intended.

**Comment by marionb** [comment]
@rebert yes that is what the customer sent as legend.

@ltclm that is intentional I added a comment for that in the code (it might clarify questions that come up in the future)

**Pull request merged**
