### PR TITLE
Using a single worker

### PR DESCRIPTION
**Pull request by procrastinatio**
Clearly not the best solution, but fixing the SRID mess is not easy.

[Demo](http://mf-chsdi3.dev.bgdi.ch/mom_wsgi/)

### CODE REVIEW

**Comment by loicgasser** [comment]
yes this is a problem. Try to update geoalchemy2. Geoalchemy is now able to read the `EWKB` data so you could read it from
https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/elements.py#L183

instead of using srid_out for the json response
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/__init__.py#L109

so `geom.srid`

**Comment by procrastinatio** [comment]
Thanks for the input @loicgasser 
But the main issue we have, requests are setting the `srid_out` on the models, to reproject the geometries, which is not a good idea as the models are global objects. Some servers may cope with that, but not apache with our current settings.

**Comment by loicgasser** [comment]
yes I know, you can't have several workers per process. But it seems that the geometries are re-projected correctly, the srid in the JSON output is incorrect. Reading it directly from the geometry could help mitigate the issue.

**Comment by loicgasser** [comment]
A solution to this problem could be to dynamically create as many instances of the same model with the different srid outputs instead and select the appropriated one in `models_from_bodid` instead of mutating models state. you need to make sure you work with `extend_existing=True`.
Not sure what is best

**Comment by procrastinatio** [comment]
@loicgasser I moved the reprojection outside the DB/models, as it has already done for `search`. Maybe not the best approach, but at least it is manageable

See https://github.com/geoadmin/mf-chsdi3/pull/3167

**Comment by procrastinatio** [comment]
Closing as we are now reprojection the `Shapely` features.

**Pull request closed without merging**
