### PR TITLE
[WIP] setup layers for topic schneesport

### PR DESCRIPTION
**Pull request by alcapat**

### CODE REVIEW

**Comment by AFoletti** [comment]
jenkins test

**Comment by AFoletti** [comment]
LGTM, but what's with the "WIP"?

**Comment by gjn** [comment]
@AFoletti What's the jenkins failure about?

**Comment by AFoletti** [comment]
wrote you an email with details. Is about the search

**Comment by gjn** [comment]
If I look at the [link above to jenkins](https://jenkins.ci.bgdi.ch/job/PR_chsdi3/1348/), I see no search related errors.

**Comment by gjn** [comment]
@AFoletti please merge if you think it's ok.

**Pull request merged**
