### PR TITLE
split gisgeol layer

### PR DESCRIPTION
**Pull request by ltclm**
split gisgeol layer ch.swisstopo.geologie-gisgeol-flaechen-10to21000km2 into
ch.swisstopo.geologie-gisgeol-flaechen-1000to21000km2
ch.swisstopo.geologie-gisgeol-flaechen-100to1000km2
ch.swisstopo.geologie-gisgeol-flaechen-10to100km2

https://github.com/geoadmin/service-sphinxsearch/pull/218 has to be deployed first

### CODE REVIEW

**Comment by ltclm** [comment]
@gjn the replaced layer has legend=false in the bod now, this should fix the jenkins error, how can we re-run jenkins without pushing something to this pr?

**Comment by oterral** [comment]
@ltclm  just write `jenkins test` in the message

**Comment by ltclm** [comment]
jenkins test

**Comment by ltclm** [comment]
danke @oterral

**Comment by ltclm** [comment]
please merge for todays deploy

**Pull request merged**
