### PR TITLE
[26.10.2016 ] First integration of ch.bazl.spitallandeplaetze

### PR DESCRIPTION
**Pull request by loicgasser**
Feature attributes are not queryable or searchable -> no sphinx

tt_wrz_* was removed from bod, I removed it as well.

[Test Link](https://mf-geoadmin3.dev.bgdi.ch/ltgal/?layers=ch.bazl.spitallandeplaetze&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=713200.00&zoom=2&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fch_bazl_spitallandeplaetze)

### CODE REVIEW

**Comment by pfanguin** [comment]
LGTM for me!

**Comment by loicgasser** [comment]
Thanks for the review, will merge after this week's deploy!

**Comment by loicgasser** [comment]
Postponed by data owner.

**Comment by gjn** [comment]
Needs rebase.

**Comment by loicgasser** [comment]
Won't be merged before next week's deploy

**Comment by pfanguin** [comment]
It's look good for me.

**Pull request merged**
