### PR TITLE
Fix typeahead version

### PR DESCRIPTION
**Pull request by oterral**
Fix the search example fixing typeahead version

### CODE REVIEW

**Comment by oterral** [comment]
jenkins test

**Comment by ponceta** [comment]
@oterral 
Why don't we use cdnjs on geoadmin?
Why don't we push our api loader on cdnjs?
Would it be a good or a bad idea?
https://github.com/cdnjs/cdnjs

**Comment by oterral** [comment]
I think,  we don't want to be dependent on an external service for geoadmin.

**Comment by ponceta** [comment]
:+1:

**Pull request merged**
