### PR TITLE
Change technames

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by loicgasser** [comment]
Please provide a full list of or changes ASAP

**Comment by loicgasser** [comment]
FYI I just rebased and pushed force to test it again. Thank you for that.

**Comment by daguer** [comment]
ch.swisstopo.lk200-papierkarte.metadata to ch.swisstopo.landeskarte200_papier.metadata
ch.swisstopo.lk500-papierkarte.metadata to ch.swisstopo.landeskarte500_papier.metadata
ch.swisstopo.gk300-papierkarte.metadata to ch.swisstopo.generalkarte300_papier.metadata
ch.swisstopo.wk25-papierkarte-zusammensetzung.metadata to ch.swisstopo.wanderkarte25-zus_papier.metadata
ch.swisstopo.sfk300-papierkarte.metadata to ch.swisstopo.segelflugkarte_papier.metadata
ch.swisstopo.wkt33-papierkarte.metadata to ch.swisstopo.wanderkarte33_papier.metadata
ch.swisstopo.bk200-papierkarte.metadata to ch.swisstopo.burgenkarte200_papier.metadata
ch.swisstopo.stk200-papierkarte.metadata to ch.swisstopo.strassenkarte200_papier.metadata
ch.swisstopo.gkg500-papierkarte.metadata to ch.swisstopo.geologie-geologische_karte_papier.metadata
ch.swisstopo.gkt500-papierkarte.metadata to ch.swisstopo.geologie-tektonische_karte_papier.metadata
ch.swisstopo.gkwvor500-papierkarte.metadata to ch.swisstopo.geologie-grundwasservorkommen_papier.metadata
ch.swisstopo.gkba500-papierkarte.metadata to ch.swisstopo.geologie-geodaesie-bouguer_anomalien_papier.metadata
ch.swisstopo.gklgm500-papierkarte.metadata to ch.swisstopo.geologie-eiszeit-lgm-raster_papier.metadata
ch.swisstopo.gas25-papierkarte.metadata to ch.swisstopo.geologie-geologischer_atlas_papier.metadata
ch.swisstopo.gsk-papierkarte.metadata to ch.swisstopo.geologie-spezialkarten_schweiz_papier.metadata
ch.swisstopo.ggk200-papierkarte.metadata to ch.swisstopo.geologie-generalkarte-ggk200_papier.metadata
ch.swisstopo.swissbuildings3d-2.metadata to ch.swisstopo.swissbuildings3d_2.metadata

**Comment by loicgasser** [comment]
thanks!

**Comment by loicgasser** [comment]
And in bod what table have you adapted?
Did you adapt the catalogs as well?

**Comment by loicgasser** [comment]
Usually, we don't change ids this way as we need to be backward compatible during deploy.
You add a new row with the new id and you remove it after the deploy. We'll have downtimes on all shop layers.

**Comment by daguer** [comment]
dataset, translations, layers_js,...
I have try to update re3.catalog but I think there is an automatic script with Mario Google doc...
His doc have to be updated first.
I have asked Mario to update the catalog. He make that next Monday (he isn't in office today).

**Comment by loicgasser** [comment]
okay sphinx feature search needs to be adapted as well.
Could you also update and translate wms-bgdi?

**Comment by loicgasser** [comment]
Ideally deploy it to dev

**Comment by loicgasser** [comment]
I mean update dev projects

**Comment by loicgasser** [comment]
I preparing the sphinx PR.
Could you put all the related PR the migration names here so that we have a global vision of what has been done, what we still need to update?

**Comment by daguer** [comment]
wms-bod translation:
https://github.com/geoadmin/wms-bod/pull/206

**Comment by daguer** [comment]
wms-bgdi:
https://github.com/geoadmin/wms-bgdi/pull/99

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
This PR is also missing all the translations in empty.po

**Comment by loicgasser** [comment]
I added them here:
https://github.com/geoadmin/mf-chsdi3/pull/2267/commits/82a2d0e5ccd75fcda7d2cfcdb04af9822605c485

**Comment by loicgasser** [comment]
and of course all the legends...

**Comment by loicgasser** [comment]
FYI @daguer you can now do:
`export WMSHOST=wms-bgdi.dev.bgdi.ch/ltgud`
`make legends BODID=ch.swisstopo.swissbuildings3d_2.metadata`

**Comment by loicgasser** [comment]
@daguer in dataset you also need to adapt all the url_portale links

For instance in
"ch.swisstopo.landeskarte200_papier.metadata"
we have
"https://map.geo.admin.ch/?lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.lk200-papierkarte.metadata"

Can you confirm you're doing it?

**Comment by loicgasser** [comment]
Actually this comes from geocat I see:
https://www.geocat.ch/geonetwork/srv/fre/md.viewer#/full_view/4bdecb2b-c692-4050-a08a-45e2041358ed

@mariokeusen please adapt those as well.

**Comment by loicgasser** [comment]
Il semblerait que tu n’as pas mis à jour le champ wms_layers dans layers_js. on est dessus avec @pfanguin

**Comment by loicgasser** [comment]
okay finally...

Here is a test link:
https://mf-chsdi3.dev.bgdi.ch/data_ltgud_change_swisstopo_layers_techname/shorten/6eeed5eae1

Please test the updates.

Not that the get price won't work as the id mapping between products and layers needs to be updated next week when we deploy.
To be syncronized with @pauloamado who prepared a script for that.

**Comment by loicgasser** [comment]
@pauloamado adapted the mapping in dev and is pushing to int.
I tested pretty heavily. Let's have this in master as tests will continue to fail otherwise.

**Pull request merged**
