### PR TITLE
Update sdiservices.rst

### PR DESCRIPTION
**Pull request by mariokeusen**
Adaptations for vectile services as requested by Kartografie

### CODE REVIEW

**Review by rebert — APPROVED** [review]
merci

**Review by deniers — COMMENTED** [review]
looks good, all links correct and working

**Comment by deniers** [comment]
Hi @mariokeusen 
Not sure where those links are in the code but the "description" link is broken:
image

**Comment by deniers** [comment]
Hi @mariokeusen 
After the text "The service provides both tiles and styles that the customer can use." We could may be add the text:
"See [examples](https://maplibre.org/maplibre-gl-js-docs/example/) to use styles in your application."

Oder sowas ähnliches. Gibt dem user halt direkt eine Einsteigshilfe, wie er unsere styles verwenden kann.
Merci & Gruss

**Pull request merged**
