### PR TITLE
Use query only on models where prop is available

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by loicgasser** [comment]
@procrastinatio quick review please this is wanted for tomorrow.

**Comment by gjn** [comment]
Shouldn't it be bad request if we try to use a where clause with an unknown column for at least one layer?

Might be philosophical question.

**Comment by loicgasser** [comment]
> Shouldn't it be bad request if we try to use a where clause with an unknown column for at least one layer?

Here it's to handle the case where we have different models for the same layer with different columns/queryable attributes. Currently you can use the `where` clause where with only one layer at a time.

**Comment by gjn** [comment]
Understood. Thanks for the explanation.

**Pull request merged**
