### PR TITLE
Use production on dev main

### PR DESCRIPTION
**Pull request by loicgasser**
https://github.com/geoadmin/mf-chsdi3/issues/1924

### CODE REVIEW

**Comment by gjn** [comment]
Maybe it would make sense to have an rc_user, which is base for all user specific configs (source rc_user in each user specific)...

**Comment by loicgasser** [comment]
A little excessive just for mod_wsgi parameter, what else could we put there?

**Comment by loicgasser** [comment]
wsgi_config sorry

**Comment by gjn** [comment]
It's more mental help. user != dev.

**Comment by loicgasser** [comment]
ok so actually copy the whole dev config but the wsgi_config? or source rc_dev and source rc_user in rc_example? If anything I would prefer the first.

**Pull request merged**
