### PR TITLE
BGDIINF_SB-2454: Make frankfurt the default Makefile

### PR DESCRIPTION
**Pull request by hansmannj**
Renamed Makefile.frankfurt to Makefile and the former Makefile to Makefile.ireland, so that, when no -f is provided, make is executed defaulting to the Frankfurt setup and is not accidentally run with the Ireland setup. Also adapted Readmes and shell scripts accordingly.

### CODE REVIEW

**Comment by hansmannj** [comment]
I guess the call of `make` in  `/chsdi/static/doc/Makefile:103` for the Sphinx docu is not affected by this renaming of the Makefiles, right?

**Review by ltshb — CHANGES_REQUESTED** [review]
@hansmannj you should rebase on top of master and do this on master branch ! Also remove the milestone of the PR.

**Review by rebert — COMMENTED** [review]
beside of the feedback of brice about making this pr on master branch it lgtm

**Comment by ltshb** [comment]
@hansmannj because you are not working today I allow myself to do the rebase and merge this ;-)

**Comment by ltshb** [comment]
@hansmannj sorry I just realized that your branch were already correctly based on master, just the PR base was wrong. So anything is now OK. Thanks

**Review by ltshb — APPROVED** [review]
👍🏼

**Comment by hansmannj** [comment]
> @hansmannj sorry I just realized that your branch were already correctly based on master, just the PR base was wrong. So anything is now OK. Thanks

@ltshb Yes, the branch was based on master, I just assumed that master was the default branch when I opened the PR and did not double check. So I missed, that the target branch was wrong. Thanks for fixing that and also removing the milestone tagging.

**Pull request merged**
