### PR TITLE
add swissnames to releasenotes 20160525

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by ltclm** [comment]
@rfrancel @daguer @AFoletti @alcapat please add your layers for tomorrow

**Comment by AFoletti** [comment]
a PR with our layers already exist ;)
https://github.com/geoadmin/mf-chsdi3/pull/2077

**Comment by ltclm** [comment]
ok, thank you
@gjn a naming convention for pr's would make sense too

**Comment by gjn** [comment]
yes, especially for release notest. 

I try to establish the use of milestones.

**Pull request closed without merging**
