### PR TITLE
CHSDI ch.bafu.wasser-gebietsauslaesse

### PR DESCRIPTION
**Pull request by Simon1193**
[testlink](https://mf-chsdi3.dev.bgdi.ch/ltbei/shorten/86d9ffc656)

### CODE REVIEW

**Comment by Simon1193** [comment]
> can we drop the old table wasser.outlets after the deploy of this version?
 I would say yes. I create a new one because data structure has changed. I don't know if it's the best way to do?

**Comment by ltclm** [comment]
> I would say yes. I create a new one because data structure has changed. I don't know if it's the best way to do?

the best thing is exactly what you do:
1. create a new table
1. adapt code to new table
1. deploy new table with new code
1. drop old table

**Comment by procrastinatio** [comment]
@Simon1193 Is it OK?

**Comment by Simon1193** [comment]
> @Simon1193 Is it mergeable?

@procrastinatio It it still on acceptance process so I would say no

**Comment by ltclm** [comment]
@Simon1193 can you confirm that all your changes are in this pr, i had to rebase to get rid of the jenkins errors.

**Comment by Simon1193** [comment]
> @Simon1193 can you confirm that all your changes are in this pr, i had to rebase to get rid of the jenkins errors.



> @Simon1193 can you confirm that all your changes are in this pr, i had to rebase to get rid of the jenkins errors.

@ltclm That's ok everything is in it, you can rebase

**Pull request merged**
