### PR TITLE
CHSDI - bafu.wasser-teileinzugsgebiete_2 [UPDATE]

### PR DESCRIPTION
**Pull request by Simon1193**
[testlink](https://mf-chsdi3.dev.bgdi.ch/ltbei_teileinzugsgebiete_2/shorten/8725f14a9d)

### CODE REVIEW

**Comment by Simon1193** [comment]
> [testlink](https://mf-chsdi3.int.bgdi.ch/ltbei_teileinzugsgebiete_2/shorten/871cc3c17a)

link to test chsdi. the symbology is the old one

**Comment by procrastinatio** [comment]
changed base

**Comment by Simon1193** [comment]
Hello @ltclm 

So I could add the geometries to table so that the partial watershed without complet watershed are also highligthable: Here is a exemple: [exemple]( https://mf-chsdi3.dev.bgdi.ch/ltbei_teileinzugsgebiete_2/shorten/874a877552)

However, I'm not sure if it's possible to remove the external tooltips only for theses entities (I think you told me it wasn't). Instead, I place a if condition in the mako so that the external tooltip returns only the name of the layer. Hope it's ok

**Comment by ltclm** [comment]
@AFoletti extended tooltip is either activated or it is not activated. thats a global layer configuration.

**Pull request merged**
